### ISSUE TITLE
ERROR: Failed to initialize theme

### ISSUE THREAD

**Issue by sereby** [DirectoryLister/DirectoryLister#10]
After installation of v2.0.3 I received this error when accessing my root directory - 

ERROR: Failed to initialize theme

Unfortunately, there's no other information. Running XAMPP 1.8.1 (PHP 5.4.7) on Windows 7 Ult. 64-bit

**Comment by blindstitch** [comment]
Having the same issue using:
nginx 1.10.3 
PHP-fpm 7.0.22
Ubuntu 16.04 LTS
