### ISSUE TITLE
Is it possible to add the ability to upload files?

### ISSUE THREAD

**Issue by 1409109991** [DirectoryLister/DirectoryLister#1000]
I need a file upload function for mobile phone and computer to share files in the LAN. Do you have upload function

**Comment by 1409109991** [comment]
![image](https://user-images.githubusercontent.com/79674967/201879251-bb1acd3d-b0fd-49d2-90ae-2bc442401819.png)
感觉翻译的不对劲

**Comment by 1409109991** [comment]
I just want local file sharing, or can you recommend a good file sharing system, one deployed on a local LAN

**Comment by PHLAK** [comment]
File uploading is out of the scope of DirectoryLister and will not be added (see: #263, #231).

Maybe look into something like [Syncthing](https://syncthing.net/) for file syncing or [NextCloud](https://nextcloud.com) if you want a managed web interface to upload/download files.

**Comment by TCB13** [comment]
> File uploading is out of the scope of DirectoryLister and will not be added (see: [#263](https://github.com/DirectoryLister/DirectoryLister/issues/263), [#231](https://github.com/DirectoryLister/DirectoryLister/issues/231)).
> 
> Maybe look into [Syncthing](https://syncthing.net/) for file syncing or [NextCloud](https://nextcloud.com) if you want a managed web interface to upload/download files.

Cmon, there's a ton of people waiting for that "small" feature.
