### ISSUE TITLE
Cache size

### ISSUE THREAD

**Issue by NigelNapier** [DirectoryLister/DirectoryLister#1004]
I'm using this awesome product (Version 3.12.0) and just received a notification from my hosting company that my server was nearly full (150gb, 40gb of data, 32 days uptime).

When I went to check what was up, I realized the cache was getting out of control.

There's files in the APP & VIEW folders, but also files outside of these folders.

Is there something that can be done to maybe delete old cache after a certain time?

**Comment by PHLAK** [comment]
The default `file` cache driver periodically clears the cache of expired items by running a "lottery" every time someone visits your directory listing. By default there's a 2% chance that old cache items (older than one hour) will be expunged with every incoming request.

If you're finding the cache is growing to fast you can adjust these settings with the `CACHE_LIFETIME` and `CACHE_LOTTERY` environment variables. For example try decreasing the `CACHE_LIFETIME` and/or increasing the `CACHE_LOTTERY`.

See the [Cache Config Reference](https://docs.directorylister.com/configuration/cache-config-reference) documentation for more information on the cache and these variables.

**Comment by PHLAK** [comment]
@NigelNapier See the [Config Overview](https://docs.directorylister.com/configuration/configuration-overview) for more information on setting configuration variables.

**Comment by NigelNapier** [comment]
I've pretty much eliminated the cache (thanks), except for the cache that's inside the root of the cache folder. 

Setting everything to zero doesn't allow me to stop this from accumulating.

I'm talking 4 days, then I need to physically delete the cache files off my server (not what I want to be doing).

**Comment by NigelNapier** [comment]
I still don't understand why this is happening.
Every 7-8 days I need to delete all the cache files from the server otherwise it fills up my hdd.
<img width="377" alt="cache" src="https://user-images.githubusercontent.com/1205726/210314935-eafd1cfa-bd50-4170-bb1d-d6c4a03eb4d4.PNG">

**Comment by NigelNapier** [comment]
Going  to have to flag your app  as it's still happening without any explanation as to why.

The cache DOES NOT delete itself like you claim it does.

**Comment by NigelNapier** [comment]
I've reinstalled the App 3 times and this still keeps happening.

I've even uploaded my files above and it still keeps happening.

THIS is definitely an issue for me.

**Comment by PHLAK** [comment]
I just confirmed file caching is working as expected.

Here are the configuration options I used (in `.env`).

```
CACHE_DRIVER=file
CACHE_LIFETIME=1
CACHE_LOTTERY=100
```

Here are the steps I took.

  1. I manually cleared the `app/cache/app` directory
  2. Navigated to my directory listing
  3. Opened a sub-folder
  4. Downloaded the directory using the "Download this Directory" link

At this point I could see a cache file at `app/cache/app/B/P/z2azrDLBnoURaeABYKzg`.

```
app/cache/app/
├── B
│   └── P
│       └── z2azrDLBnoURaeABYKzg
└── [ADDITIONAL FILES OMITTED]
```

Opening the file showed the following contents.

```
1677609335
zip-04d13fd0aa6f0197cf2c999019a607c36c81eb9f
s:27878:"PK [BINARY OMITTED FOR BREVITY]
```

I then waited one minute (as per the `CACHE_LIFETIME` setting) and refreshed my directory listing and the `app/cache/app/B/P/z2azrDLBnoURaeABYKzg` file was gone.

```
app/cache/app/
├── B
│   └── P
└── [ADDITIONAL FILES OMITTED]
```

Repeating these steps with a higher `CACHE_LIFETIME` and/or lower `CACHE_LOTTERY` values caused the cached item to be deleted as well although it took additional time/requests.

Thus we can conclude that file caching is working as expected.

A few things to check/try.

  - Ensure your `CACHE_LIFETIME` and `CACHE_LOTTERY` are not `0`. If either of these values are `0` your cache will never be cleaned.
  - Try lowering the `CACHE_LIFETIME` value
  - Try increasing the `CACHE_LOTTERY` value
  - Check your file permissions and make sure your web server user has permission to delete files.
  - Try an alternative caching driver (i.e. redis)

**Comment by NigelNapier** [comment]
I agree that cache is 100% working.

The problem is, is doesn't DELETE.

Please read my files above, because these are the exact ones that are on my server.

CACHE_LOTTERY = 2
CACHE_LIFETIME = 3600

Every 7 - 10 days I have to physically delete the cache directory.
