### ISSUE TITLE
Blank spaces not showing up on md5 info page.

### ISSUE THREAD

**Issue by timfischbach** [DirectoryLister/DirectoryLister#1006]
My instance is displaying spaces not correctly in the md5 info window. Instead, it shows %20 for a blank space.
![Screenshot_20221123_115612_Chrome.jpg](https://user-images.githubusercontent.com/59933715/203529676-7d93cce5-de19-4315-81e2-2a54ca4bc61c.jpg)![Screenshot_20221123_115616_Chrome.jpg](https://user-images.githubusercontent.com/59933715/203529694-4ff17099-3c98-4543-a592-3abd23cad79c.jpg)

**Comment by PHLAK** [comment]
Thanks, I'll take a look at this.

**Comment by PHLAK** [comment]
Fixed with 1535dc7c5dfe61a71ad9c9ffce7d83d3eef7513f
