### ISSUE TITLE
Code tags in MD documents in dark mode are hard to read

### ISSUE THREAD

**Issue by SierraKomodo** [DirectoryLister/DirectoryLister#1007]
### Directory Lister Version

3.12.1

### PHP Version

8.1.2-1ubuntu2.9

### PHP Extensions

[PHP Modules]
calendar
Core
ctype
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

### Web Server

Apache2 v2.4.52-1ubuntu4.2

### Describe the Bug

The dark mode color scheme uses light text on a light background for code tags in a markdown document, i.e.:

```md
This is a `code` tag
```

An easy example is to look at the default Readme.md present in the repository while using darkmode:

![firefox_IUElHQYZm1](https://user-images.githubusercontent.com/11140088/205333231-eac3dcc9-7f9b-4594-8077-7e7dcb813f8c.png)

**Comment by PHLAK** [comment]
Thank you, will fix this soon.

**Comment by PHLAK** [comment]
Resolved with 0679d967c34c27faa590f131aea6da6c915aa58e
