### ISSUE TITLE
Matomo not working

### ISSUE THREAD

**Issue by Johnnybegood90** [DirectoryLister/DirectoryLister#1022]
### Directory Lister Version

3.12.2

### PHP Version

8.1.13

### PHP Extensions

[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

### Web Server

Apache2

### Describe the Bug

Matomo tracking isn't working, any idea?

.env file:
APP_DEBUG=false
APP_LANGUAGE=en

DARK_MODE=true
DISPLAY_READMES=true
READMES_FIRST=false
ZIP_DOWNLOADS=true

GOOGLE_ANALYTICS_ID=UA-8XXXXX4-6

MATOMO_ANALYTICS_URL="https://matomo.XXXXXXXXXX.YY"
MATOMO_ANALYTICS_ID="1"

SORT_ORDER=type
REVERSE_SORT=false

SITE_TITLE="XXXXXXX XXXXXX"
HIDE_APP_FILES=true
HIDE_VCS_FILES=true

DATE_FORMAT="Y-m-d H:i:s"
TIMEZONE="UTC"

MAX_HASH_SIZE=9223372036854775807
VIEW_CACHE=false

**Comment by jamaa** [comment]
can confirm, almost the same issue again as was fixed previously in #555
