### ISSUE TITLE
Show an indicator when search/zip is being executed

### ISSUE THREAD

**Issue by coniferous1** [DirectoryLister/DirectoryLister#1050]
Both when zipping large files, or searching through a large directory it can take some time depending on the power of the system you are on. 

It would be nice if some user feedback could be shown, beacuse the default loading indicator (looking at you chrome) makes it seem like nothing is happening.

**Comment by PHLAK** [comment]
This is a good idea. I'll look into it.

**Comment by transitriderproductions** [comment]
Hi, I'm new here and I tried to disable the zip in app.config and it wont remove the zip icon. Bug?
