### ISSUE TITLE
Adapt to PHP8.2.3

### ISSUE THREAD

**Issue by cfwl1111** [DirectoryLister/DirectoryLister#1069]
### Directory Lister Version

3.12.3

### PHP Version

8.2.3

### Web Server

nginx

### Describe the Bug

Hi, is there a plan to update the support of PHP8.2.3

**Comment by PHLAK** [comment]
The latest release of Directory Lister should already work with PHP 8.2 and I've started #1043 to bump the minimum supported PHP version to PHP 8 to ensure future compatibility.

If you experiencing any specific issues please open an issue detailing the problem and we can take a look.
