### ISSUE TITLE
Hide @eaDir (for Synology)

### ISSUE THREAD

**Issue by RobbyTown** [DirectoryLister/DirectoryLister#107]
Great script! I try to hide @eaDir (Synology creates this, dont see it normaly in my SMB connection)

I add @eaDir to the Hidden files list like:
@eaDir
@eaDir/*

Still showing @eaDir in a folder. I there any way to hide @eaDir?

I try to creat a folder @eaDir in a folder but @eaDir not allowed to create :/

**Comment by therosss** [comment]
Easy ;)
Open-up /resources/config.php 
On "basic" add:
`'hide_at_files'            => true,`
for it to look like this:
`return array(

    // Basic settings
    'hide_dot_files'            => true,
	'hide_at_files'            => true,
    'list_folders_first'        => true,
    'list_sort_order'           => 'natcasesort',
    'theme_name'                => 'bootstrap',
    'external_links_new_window' => true,
`
After that, open /resources/DirectoryLister.php
and add the block:

`		        // Add at-folders to hidden files array
        if ($this->_config['hide_at_files']) {

            $this->_config['hidden_files'] = array_merge(
                $this->_config['hidden_files'],
                array('@*', '*/@*')
            );

        }`

just after the block of `// Add dot files to hidden files array`

It should look like:
` protected function _isHidden($filePath) {

        // Add dot files to hidden files array
        if ($this->_config['hide_dot_files']) {

            $this->_config['hidden_files'] = array_merge(
                $this->_config['hidden_files'],
                array('.*', '*/.*')
            );

        }
		
		        // Add at-folders to hidden files array
        if ($this->_config['hide_at_files']) {

            $this->_config['hidden_files'] = array_merge(
                $this->_config['hidden_files'],
                array('@*', '*/@*')
            );

        }

        // Compare path array to all hidden file paths
        foreach ($this->_config['hidden_files'] as $hiddenPath) {

            if (fnmatch($hiddenPath, $filePath)) {

                return true;

            }

        }

        return false;

    }

`

I'll attach the 2 files in here.
[resources.zip](https://github.com/DirectoryLister/DirectoryLister/files/170684/resources.zip)



Cheers,
Ross

**Comment by RobbyTown** [comment]
Hmm simple, lots off code :).

Thanks. I tested on my Synology and it works! :+1:
