### ISSUE TITLE
Change date display

### ISSUE THREAD

**Issue by RobbyTown** [DirectoryLister/DirectoryLister#108]
Now it's in DirectoryLister.php date view Y-m-d H:i:s

I made a change to change it in the config file. Some idea to add as new feature?

config.php
'date_display'              => 'd-m-Y H:i:s',

DirectoryLister.php changed to
'mod_time'   => date($this->_config['date_display'], filemtime($realPath)),

**Comment by marcinlawnik** [comment]
@PHLAK can you close this?
