### ISSUE TITLE
Feature request: Sorting by Date AND type

### ISSUE THREAD

**Issue by strlns** [DirectoryLister/DirectoryLister#1090]
I'd love to be able to sort by type and date, the same way it's done when adding multiple ORDER BY clauses in SQL.

Goal: directories at the top, files/directories (nodes with the same type) sorted by modification time.

Maybe as a comma-separated list in the `.env`-file and as an array in PHP?

Thank you for freely sharing your useful project, I realize this is a convenience request for myself which I could try opening a PR for instead of an issue.

Just wanted to hear if I overlooked sth that which already allows this, and if this is feature would be considered useful by others in the first place.

**Comment by PHLAK** [comment]
This could likely be accomplished by

**Comment by PHLAK** [comment]
This could likely be accomplished with a [custom `sort_order` function](https://docs.directorylister.com/configuration/app-config-reference#sort_order).

**Comment by strlns** [comment]
Ah, this was it! Sorry for my laziness, I even saw that the last time I wanted to change my private instance. Was just too lazy to do it in PHP instead of the .env file.

Thanks for the heads up!
