### ISSUE TITLE
renaming index.php to list.php not fully working

### ISSUE THREAD

**Issue by mouro001** [DirectoryLister/DirectoryLister#111]
i changed the index.php to list.php and there is 1 thing that isnt working. when i click on home, it redirects me to to index.php and i want it to redirect me to list.php.
Is that possible to change?

**Comment by chrisschlitt** [comment]
I noticed this issue yesterday while trying to change index.php as well.  Have you made any progress?  I'm currently trying to fix this issue and I'll make a pull request when ready.

**Comment by chrisschlitt** [comment]
I have a created a pull request that solves this issue.  It is located at https://github.com/DirectoryLister/DirectoryLister/pull/119

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
