### ISSUE TITLE
Don't downloads .zip files

### ISSUE THREAD

**Issue by Kaimas** [DirectoryLister/DirectoryLister#114]
Hello,

I faced with problem, when I try download folder in .zip archive it's downloads only folder name.zip file with size 0 bytes. 
I change - "'zip_dirs' => true," from false.

Maybe you know whats can be wrong?

Thanks, until

**Comment by patareco** [comment]
I'm having the same problem. 
After checking the code and permissions to run the zip command, everything seems to be ok, so I have no idea on what's causing this particular problem

**Comment by bsquidwrd** [comment]
I just ran into this issue as well. Was super stoked to be able to have ZIP files created on the fly with this but even with a directory with a small text document containing "test" in it doesn't seem to work.

**Comment by bsquidwrd** [comment]
I found the solution. You need to make sure to have read, write and execute for the folder containing the information as well as the folder you are zipping.

I solved this by running the following:
```shell
sudo chmod -R 777 /path/to/your/directory/here
```

**Comment by marmz** [comment]
I have the same problem. When i download "zipped" directories, i get an "empty/not-valid" archive.
Unfortunately the program doesn't output any error message ...

Setting permissions to 777 doesn't fix that issue.

Please help me guys!

**Comment by TimothyJimothy** [comment]
I am also having the same issue as marmz and I cannot track down the source of it, mostly because it appears most of the zip code in `DirectoryLister.php` is obfuscated

**Comment by aser007** [comment]
Same Problem here. It seems to work but i get an empty file^^.

**Comment by TimothyJimothy** [comment]
Any update on this?

**Comment by andersenthomas** [comment]
Also seeing the same issue as described above. .zip-file is downloaded but is empty/not-valid. Any update on this issue? Would love to have the zip functionality!

**Comment by y-master** [comment]
I had the same issue and the solution was simple : /usr/bin/zip was not installed sot an "apt install zip" solved it :)

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
