### ISSUE TITLE
Protect List?

### ISSUE THREAD

**Issue by maurocarrera** [DirectoryLister/DirectoryLister#115]
Hi guys.

How can i protect the index file, i mean... When i go the the index ask for a username or password?

**Comment by echelontf** [comment]
This can be done using the .htaccess file.

Open .htaccess and input the following code. Note: `AuthUserFile` needs to be change to the location of index.php. But don't forget to put .htpasswd at the end.

```
AuthType Basic
AuthName "Password required"
AuthUserFile /var/www/html/index/.htpasswd
require valid-user
```

Now open the .htpasswd and use the following code. This is an example and the username and password should be changed. Use the format _username:password_

```
maurocarrera:fjEk3jfsoSkl
user2:12345
user3:123456789
```

**Comment by PHLAK** [comment]
@echelontf's solution is really the simplest solution.
