### ISSUE TITLE
ERROR: Failed to initialize theme

### ISSUE THREAD

**Issue by p3-chuck** [DirectoryLister/DirectoryLister#117]
If I navigate to the installed directory through the browser address bar, it works great.  If I navigate to any sub-directory (through the address bar) by typing the url - I get "ERROR: Failed to initialize theme".  

I can navigate through the directory listing to all sub-directories without issue.

It will not recognize any sub-directory if I attempt to change the $themeIndex in the index.php page either.   It fails on the file_exists function for any file outside the directory (yes. I'm using direct addresses such as /home/acct/public_html/filename).

**Comment by PHLAK** [comment]
This sounds like a misconfiguration in your web server (apache/nginx/etc.).  It appears to be pointing subdirectories to the index.php file which it should not.  Check your server configuration files and consult with the appropriate documentation to make sure things are configured correctly.
