### ISSUE TITLE
Feature Request: SEO-friendly URLs

### ISSUE THREAD

**Issue by Concept211** [DirectoryLister/DirectoryLister#118]
It would be great if you could incorporate seo-friendly URLs:

www.domain.com/?dir=folderone/foldertwo 

becomes:

www.domain.com/folderone/foldertwo/

**Comment by bisherbas** [comment]
Please add this feature!

**Comment by bisherbas** [comment]
Can you please at least point me to the right spot in the code so I can make the change myself? Thanks!

**Comment by herohamp** [comment]
I am looking into doing that for nginx. it should require minimal editing of directory listing :D

**Comment by nixmomo** [comment]
FOr Apache
RewriteEngine On
RewriteRule ^([^/]*)$ /?dir=$1 [L]

**Comment by bisherbas** [comment]
@nixmomo thanks but it doesn't work for me. When I add .htaccess file into the directory and copy paste what you posted, the directory is not opening in the browser. This directory is in the same folder where there is a Wordpress installation so when I go to the directory a random page on the Wordpress is opened instead of the directory listing.

**Comment by nixmomo** [comment]
Hmm... ok let me look a bit deeper into this after i'm done with a bit nicer Theme

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
FYI, this is now the default behavior in Directory Lister 3 :slightly_smiling_face:
