### ISSUE TITLE
Is it browser specific ?

### ISSUE THREAD

**Issue by smruti-sahoo** [DirectoryLister/DirectoryLister#122]
Hi, 
Which browser does it support. I tried it on chrome, IE and FF but the format seems very odd 
Chrome - Version 51.0.2704.103 m
FF: 47.0.1
IE: 11.09

[
![directory lister](https://cloud.githubusercontent.com/assets/13956982/16914033/a0e93518-4d0c-11e6-998e-8ba929f953f5.PNG)
](url)

**Comment by PHLAK** [comment]
Directory Lister should work fine on any of the browsers listed.  There seems to be an issue with your style sheets.

**Comment by smruti-sahoo** [comment]
I downloaded the package from github master branch, is not it correct one ?

**Comment by smruti-sahoo** [comment]
Hey it's working now.. thanks.. 
I downloaded and re-install the package again
