### ISSUE TITLE
download a folder (ZIP function)

### ISSUE THREAD

**Issue by computerartsde** [DirectoryLister/DirectoryLister#125]
I have an issue with downloading a folder with larger files (around 4 GB and more). I think it is a general timeout-problem with php-settings of my server. But the increased values (memory, post_max_size, timeouts etc.) haven't any effect. 

So is there a way to optimize your fantastic script to fix this download-problem with large files? (maybe like http://www.mysqldumper.net do it with importing large sql-files ...)

thank you,
Sven

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
