### ISSUE TITLE
How to enable thumb for pictures?

### ISSUE THREAD

**Issue by towerstreet** [DirectoryLister/DirectoryLister#1276]
### Directory Lister Version

4.0.0

### PHP Version

8.3

### PHP Extensions

bcmath
bz2
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
random
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvsem
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

### Web Server

Nginx

### Describe the Bug

How to enable thumb for pictures?

**Comment by PHLAK** [comment]
This is not possible.
