### ISSUE TITLE
403 Forbideen

### ISSUE THREAD

**Issue by tkrn** [DirectoryLister/DirectoryLister#1285]
### Directory Lister Version

4.2.0

### PHP Version

8.2.21

### Web Server

Apache

### Describe the Bug

The script works but when I try to browse to a subdirectory I get "403 Forbidden". 
See 

http://files.tkrn.io
http://files.tkrn.io/?dir=blog

**Comment by PHLAK** [comment]
This is an issue with your web server (e.g. Apache or Nginx) configuration. A `403` is also returned when navigating directly to any of the sub-folders (e.g. http://files.tkrn.io/tkrn/) which is handled entirely by your web server and never calls any Directory Lister code.
