### ISSUE TITLE
ModSecurity - Being tagged as Malware.Expert - ani-shell - php command shell

### ISSUE THREAD

**Issue by tkrn** [DirectoryLister/DirectoryLister#1286]
### Directory Lister Version

4.2.0

### PHP Version

8.2.21

### Web Server

Apache

### Describe the Bug

Just a heads up, DirectoryLister is being tagged by ModSecurity and thus producing a 403 error. This module is in security programs such as cpguard and opsshield (https://opsshield.com/help/cpguard/cpguard-web-application-firewall/)

I dont if there are code changes that can correct this from being picked up.

`[Fri Jul 26 10:22:43.110358 2024] [:error] [pid 1177521:tid 1178252] [client 74.81.197.30:47312] [client 74.81.197.30] ModSecurity: Access denied with code 403 (phase 1). String match "?dir=" at REQUEST_URI. [file "remote server"] [line "-1"] [id "700042"] [msg "Malware.Expert - ani-shell - php command shell"] [hostname "files.tkrn.io"] [uri "/"] [unique_id "ZqO_Q_9ke6Er8W6qWvV41gAAAQM"], referer: http://files.tkrn.io/`

**Comment by PHLAK** [comment]
You should contact ModSecurity support or open an issue with them about this.
