### ISSUE TITLE
Easiest way to list an Amazon S3 bucket?

### ISSUE THREAD

**Issue by echelontf** [DirectoryLister/DirectoryLister#130]
I want to host files on an Amazon S3 bucket instead of my VPS (Amazon is cheaper). How can I show a directory listing of the Amazon bucket instead of a directory on my server?

**Comment by PHLAK** [comment]
Directory Lister doesn't directly support S3.  However, if you were able to mount the contents of your S3 bucket to a directory Directory Lister could list that.
