### ISSUE TITLE
Problems with cache and full disk

### ISSUE THREAD

**Issue by mikysal78** [DirectoryLister/DirectoryLister#1305]
Hi,
I've seen the documentation, I've read the various issues but I keep getting a full disk.
What are the files that can be deleted?
Is there a script to run in cron?

Regards,
Michele

**Comment by PHLAK** [comment]
What version of Directory Lister are you using and which folder is filling up?

Also, what [cache driver](https://docs.directorylister.com/configuration/cache-config-reference#cache_driver) are you using? Have you tried using any other drivers? Decreasing the the [`cache_lifetime`](https://docs.directorylister.com/configuration/cache-config-reference#cache_lifetime) may help. If you're using the `file` driver, increasing the [`cache_lottery`](https://docs.directorylister.com/configuration/cache-config-reference#cache_lottery) may also be a good idea.

**Comment by mikysal78** [comment]
Thank you,
I use version 3.12.3

```
CACHE_DRIVER=file
CACHE_LIFETIME=1
CACHE_LOTTERY=100
```
the directory that fills up is from the cache "app/cache/"

**Comment by PHLAK** [comment]
I'm guessing zip downloads are contributing to this. Prior to v4.0.0 zip files would be bundled on disk (in `app/cache`) before being served to the user for download. In [v4.0.0](https://github.com/DirectoryLister/DirectoryLister/releases/tag/4.0.0) we added "zip streaming" which bundles zip downloads in memory so they never hit the cache folder. I'd recommend upgrading to v4.0.0 or higher and seeing if this resolves your issues.
