### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by venadHD** [DirectoryLister/DirectoryLister#131]
Design a password protect system to access script

**Comment by PHLAK** [comment]
This is outside the scope for Directory Lister.  However, you can always use a [.htpasswd](https://httpd.apache.org/docs/current/programs/htpasswd.html) file to restrict access to a specific directory.

Here's a more in-depth article on accomplishing this: https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-14-04

Note: If you're using Nginx you'l need to enable [auth_basic](https://nginx.org/en/docs/http/ngx_http_auth_basic_module.html) for this to work.
