### ISSUE TITLE
Feature Request: a "README.md" file to generate a summary

### ISSUE THREAD

**Issue by PaulGet** [DirectoryLister/DirectoryLister#135]
It would be great if there was the possibility - similar to github.com - that the content of a "README.md" file in the directory generate a html summary.

**Comment by cramdesign** [comment]
Awesome suggestion. Please?

**Comment by nixmomo** [comment]
At the End of the Site? At the start from the Site? 
Please a bit more info
Take a Look here, is that what you're looking for?
https://directorylister.sugar-camp.com/

**Comment by theraw** [comment]
@nixmomo something like that.

As in page will be alot of empty place in footer it will be nice to place the 'README.md' on it and it will be like github. but there's needed markdown style (http://prismjs.com/)
And it should be done to read the "README.md" of current directly not reading just one readme.md for every page

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
FYI, rendering of READMEs is now available in Directory Lister 3 :slightly_smiling_face:
