### ISSUE TITLE
Feature Request: Search current and child folders for a specifc file name

### ISSUE THREAD

**Issue by styper** [DirectoryLister/DirectoryLister#137]
Title pretty much sums it up, it would be cool to get a box to search for file names in the current + child folders.

**Comment by Nafari** [comment]
Title pretty much sums it up, it would be cool to get a box to search for file names in the current + child folders.
please add this code

**Comment by KaffeMyers** [comment]
I'm interested in this feature as well! :)

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
FYI, search is now available in Directory Lister 3 :slightly_smiling_face:
