### ISSUE TITLE
UTF-8 File Names

### ISSUE THREAD

**Issue by earmin** [DirectoryLister/DirectoryLister#144]
Hi,
My file names are in Persian (IR_fa), and the names wouldn't be shown correctly.

**Comment by kropek4767** [comment]
try add this, ofcourse you must modified this coud. 
`$arrLocale = array( "pl_PL", "polish_pol" );
setlocale(LC_ALL, $arrLocale );`

**Comment by ju0632** [comment]
@kropek4767 I would like to ask which file to add

**Comment by kropek4767** [comment]
to index.php in main folder on start document

**Comment by ju0632** [comment]
You can point in detail, the initial contact with this procedure

**Comment by ju0632** [comment]
@kropek4767 You can point in detail, the initial contact with this procedure

**Comment by kropek4767** [comment]
`	$arrLocale = array( "pl_PL", "polish_pol" );
	setlocale(LC_ALL, $arrLocale );
    
	// Include the DirectoryLister class
    require_once('resources/DirectoryLister.php');
	
	//Dołączamy bibliotekę do kodowania polskich znaków
    require_once('resources/biblioteka_pl.php');
	
    // Initialize the DirectoryLister object
    $lister = new DirectoryLister();

    // Restrict access to current directory
    ini_set('open_basedir', getcwd());

    // Return file hash`
