### ISSUE TITLE
Error with local testing

### ISSUE THREAD

**Issue by cramdesign** [DirectoryLister/DirectoryLister#145]
I am getting this error when running on local php:

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/matt/Dropbox (Personal)/Server/localhost/cmstest/DIR/resources/DirectoryLister.php on line 628

**Comment by PHLAK** [comment]
This is not an issue with Directory Lister.  You need to sete your [`date.timezone`](https://secure.php.net/manual/en/datetime.configuration.php) in your php.ini file as specified in the warning.

See http://stackoverflow.com/a/16765214/27025
