### ISSUE TITLE
it requires several clicks on folders to open them

### ISSUE THREAD

**Issue by alexCea** [DirectoryLister/DirectoryLister#147]
sometimes the script reacts as expected. but mostly I have to click the folder button or the folder-up button 3 or 4 times to get an reaction.
PHP version is 5.4.24
DirectoryLister is 2.6.1

**Comment by PHLAK** [comment]
This sounds like an issue specific to your installation and/or web browser.  Does the problem happen on http://demo.directorylister.com ?

**Comment by alexCea** [comment]
No, it works on your demo. But what could it be? Any suggestions?
