### ISSUE TITLE
not visible fisrt word of folders (Greek)

### ISSUE THREAD

**Issue by dokimiisto** [DirectoryLister/DirectoryLister#148]
I use greek characters and everything works perfect, except this: 

If the name of folder is for example "Ενα Δυο" then the output of listing is "Δυο" => cuts the first word. 
So if a folder has the name of "Ενα" (only one word) then the folder can't displayed 

Please help!

**Comment by PHLAK** [comment]
Maybe PHP's [setlocale()](https://secure.php.net/manual/en/function.setlocale.php) function can help you.

**Comment by dokimiisto** [comment]
Thank you for quick  reply, but please tell me where to set the fuction (which file)

**Comment by xsinger** [comment]
edit resources/DirectoryLister.php line 633

```
$directoryArray[pathinfo($relativePath, PATHINFO_BASENAME)] = array(
```
to
```
 preg_match('/\/([^\/]*)$/', $relativePath, $matches);
 $pathname = isset($matches[1]) ? $matches[1] : $relativePath;
 $directoryArray[$pathname] = array(
```

**Comment by pi3141** [comment]
Thank you very much. I had the problem with folder with a first letter with accent (eg: électrique). The first letter was not displayed. 
Now It works. Could It be possible to merge the change in the code ?

Thanks.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
