### ISSUE TITLE
Unable to access symlink'd folder on /media/card

### ISSUE THREAD

**Issue by TimothyJimothy** [DirectoryLister/DirectoryLister#151]
Hello,

I created a symlink that pointed to a folder on a different drive (/media/card). I am getting the errors
```
Warning: realpath(): open_basedir restriction in effect. File(/media/card/Logs) is not within the allowed path(s): (/var/www/html) in /var/www/html/resources/DirectoryLister.php on line 566

Warning: is_dir(): open_basedir restriction in effect. File(Logs) is not within the allowed path(s): (/var/www/html) in /var/www/html/resources/DirectoryLister.php on line 619

Notice: Undefined offset: -1 in /var/www/html/resources/DirectoryLister.php on line 361
```
Is there a way to disable the open_basedir restriction? This is for use on an embedded system that will only have one client at a time, so i am not worried about security or the user rooting around on an SD card.

**Comment by TimothyJimothy** [comment]
I solved the issue:

In index.php there is a line
```php
// Include the DirectoryLister class
    require_once('resources/DirectoryLister.php');

    // Initialize the DirectoryLister object
    $lister = new DirectoryLister();

    // Restrict access to current directory
    #ini_set('open_basedir', getcwd());

    // Return file hash
    if (isset($_GET['hash'])) {

        // Get file hash array and JSON encode it
        $hashes = $lister->getFileHash($_GET['hash']);
        $data   = json_encode($hashes);

        // Return the data
        die($data);
```

Just had to comment it out :)

**Comment by jjcazau** [comment]
Confirmed this fixed symlinks.

**Comment by PHLAK** [comment]
The fix proposed by @TimothyJimothy will fix your problem, but will also break the security of the script and potentially allow any user to browse to any file on your system. I do not recommend this fix for any public facing installations of Directory Lister.
