### ISSUE TITLE
Instruction File

### ISSUE THREAD

**Issue by ml48603** [DirectoryLister/DirectoryLister#154]
Where can I find instruction on how to customize Directory Lister ?

Website excerpt
Theme support is built in to fit your unique style. Control your listing with custom sort ordering of files/folders.

I want to learn more about some of the options in the config file, but do not see a Instruction/Direction file available at the website.

FILE ./resource/config.php

    // Basic settings
    'hide_dot_files'            => true,
    'list_folders_first'        => true,
    'list_sort_order'           => 'natcasesort',
    'theme_name'                => 'bootstrap',
    'external_links_new_window' => true,

Specifically, what optional selections are available for     'list_sort_order'           => 'natcasesort', ??

Thanks ML

**Comment by PHLAK** [comment]
Directory Lister includes support for themes but I don't know of any themes other than the default provided theme. As for the sorting methods, I don't believe I ever documented these specifically. However, if you [take a look at the code](https://github.com/DirectoryLister/DirectoryLister/blob/master/resources/DirectoryLister.php#L666-L688) you can see the available methods (The quoted strings following the "case" keyword).

**Comment by ml48603** [comment]
What needs to be changed in directory lister to sort files by modified timestamp (linux system) with most recent files at the top of the listing?  If it is easier to make modifications to directory lister to sort files by filename, I do timestamp the filenames as follows:

(Desired order shown)
Filename-2017-04-26_EDT_03:50:00.html
Filename-2017-04-25_EDT_23:50:01.html
Filename-2017-04-25_EDT_20:50:02.html
