### ISSUE TITLE
sort in reverse

### ISSUE THREAD

**Issue by xAphex** [DirectoryLister/DirectoryLister#155]
i'm trying to sort in reverse, i went to **DirectoryLister.php** and set **$reverse** to **true** and went to **config.php** and set the path to **'*'** and it still doesn't work.

why?

**Comment by Mrgts411** [comment]
Update 1: Fixed the issue, turns out u need to put folder path without **/** at front or bottom.

Question: How do i sort the directories themselfs, not the files in them?

**Comment by Mrgts411** [comment]
bump

**Question:** How do i sort the directories themselves, not the files in them, in reverse?

**Comment by OnlyBrakeForRainbows** [comment]
In config.php I changed
`'list_sort_order'           => 'natcasesort',`
to
`'list_sort_order'           => 'arsort',`

**Comment by xAphex** [comment]
yeah i tried this method, didn't work for folders, just files.

i no longer use this Directory Lister, i made a website with all the downloads i need using css buttons, can do more organizations and can host it on GitHub, much better.
