### ISSUE TITLE
Korean file name not visible

### ISSUE THREAD

**Issue by sanvit** [DirectoryLister/DirectoryLister#156]
When a file name is in Korean, file is visible but file name is not shown

**Comment by stevenzhu25** [comment]
What charset do you chose  UTF-8 or sth else ?

**Comment by sanvit** [comment]
UTF-8

**Comment by stevenzhu25** [comment]
then it should be fine... 
Check editor code is utf-8 or not.
Thanks.
Steven Zhu
678-865-3083

https://stevenz.xyz
https://d3x.pw
https://sl0.us


© Copyright 2000-2017 STEVEN ZHU; M&W; Decorate Depot; All rights reserved.



---- On Sun, 28 May 2017 20:04:29 +0800 notifications@github.com wrote ----

UTF-8

**Comment by mariobalanica** [comment]
This is the correct charset for Latin: "ISO-8859-1" .

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
