### ISSUE TITLE
navbar doesnt work

### ISSUE THREAD

**Issue by Mrgts411** [DirectoryLister/DirectoryLister#161]
the navbar has a problem, it doesn't work like it used to do before.

if u go to multiple folders (folder inside a folder) and u click on the second folder, so **Home / Folder1 / Folder2**.

u click on **Folder1**, it says **"ERROR: File path does not exist"**.

i tried to analyze the problem, and found that it adds **%2F** after **?dir=** (%2F = /)

hope u fix this problem, thanks 😄

**Comment by PHLAK** [comment]
Fixed with 2.7.1
