### ISSUE TITLE
Headers on a per directory basis

### ISSUE THREAD

**Issue by scj643** [DirectoryLister/DirectoryLister#162]
Is there a way to make the header change based on what directory is being shown?

**Comment by Mrgts411** [comment]
this repo is dead (or almost dead), so i doubt anyone would help you.

**Comment by nixmomo** [comment]
It's very simple to add.
Do you use the default Theme?

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
