### ISSUE TITLE
Force download files

### ISSUE THREAD

**Issue by Tampa** [DirectoryLister/DirectoryLister#164]
Index.php line 99:

`<a href="<?php echo $fileInfo['url_path']; ?>" class="clearfix" data-name="<?php echo $name; ?>">`

Adding `<?php if(strpos($name, '.') !== false && $name !== ".."){ echo("download");} ?>` to the end makes sure unrecognized filetypes, like .flac, are downloaded instead of opened.

Probably not the best way to force this, but it's a bit annoying when a browser tries to open 2.3Gb of flac into memory.

**Comment by nixmomo** [comment]
Can't reproduce this error. I testet with total unkown file type ".info" and its a text in it but it started download. 
https://directorylister.sugar-camp.com/?dir=web

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
