### ISSUE TITLE
Undefined fnmatch() in Android web servers

### ISSUE THREAD

**Issue by shmshd** [DirectoryLister/DirectoryLister#170]
Tested in [KSWEB](https://play.google.com/store/apps/details?id=ru.kslabs.ksweb) &[ Server for PHP](https://play.google.com/store/apps/details?id=com.esminis.server.php)
PHP: 7.1.5
Below error occurs:
`
Fatal error: Uncaught Error: Call to undefined function fnmatch() in /storage/emulated/0/htdocs/resources/DirectoryLister.php:767 Stack trace: #0 /storage/emulated/0/htdocs/resources/DirectoryLister.php(606): DirectoryLister->_isHidden('directory_liste...') #1 /storage/emulated/0/htdocs/resources/DirectoryLister.php(156): DirectoryLister->_readDirectory('.') #2 /storage/emulated/0/htdocs/index.php(34): DirectoryLister->listDirectory('.') #3 {main} thrown in /storage/emulated/0/htdocs/resources/DirectoryLister.php on line 767`

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
