### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dsouzarohan06** [DirectoryLister/DirectoryLister#171]
Hello,

Request you to add the following features.

1. Option to upload files to the current directory/path you are working on.
2. A delete button beside every file/directory so that you can delete unwanted stuff.
3. A button to create a new directory(should give me a prompt to for the name)

Awaiting your response.

Regards,
Rohan Dsouza

**Comment by Travis-Owens** [comment]
Sounds like you want something like OwnCloud/NextCloud. 

I think the developers of this project want to keep things simple.
