### ISSUE TITLE
Container Size Issue

### ISSUE THREAD

**Issue by Travis-Owens** [DirectoryLister/DirectoryLister#172]
I changed the background-color and noticed the container isn't large enough to contain the buttons on the right side.

Here is my lazy solution:
File: styles.css

.container {
    max-width: 960px;
    **padding-right: 40px;**
}

**Comment by nixmomo** [comment]
better use 35px. Fixed in #177

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
