### ISSUE TITLE
Search feature.

### ISSUE THREAD

**Issue by Nafari** [DirectoryLister/DirectoryLister#173]
please add a search feature.
folder and subfoler

**Comment by Tampa** [comment]
Best would be using js for getting the results as it would show them interactively, but js has no way to read files so the whole directory and filetree would need to exist as an array somewhere first.

Would need to write a searchinit to fetch that data write it to a file, then use js to go over that and generate the links to view said files or directories.

I don't know js at all though.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
FYI, search is now available in Directory Lister 3 :slightly_smiling_face:
