### ISSUE TITLE
How do we change the directory to list?

### ISSUE THREAD

**Issue by Gibigbig** [DirectoryLister/DirectoryLister#174]
If the install directory and the files you want to list are in different directories, which settings to you update?

**Comment by googlemusic** [comment]
yes please tell me i want to change this

**Comment by Muraro** [comment]
(1TB) /dev/sda4 /mnt/Storage1  symbolic link NAS1 -> /mnt/Storage1/
(1TB) /dev/sda5 /mnt/Storage2  symbolic link   NAS2 -> /mnt/Storage2/
(1TB) /dev/sdb1 /mnt/Storage3  symbolic link NAS3 -> /mnt/Storage3/

Alias /discovery "/var/www/DirectoryLister"
<Directory /var/www/DirectoryLister>
Options +FollowSymLinks
AllowOverride ALL
Order Deny,Allow
Allow from 192.168.25.
</Directory>

**Installation**
**3.** Upload  index.php and the resources folder to the folder you want listed

**Comment by Gibigbig** [comment]
This works for apache, but nginx with php isn't so simple as an alias

Sent from my iPhone

On 11 Sep 2017, at 10:30 AM, Muraro <notifications@github.com<mailto:notifications@github.com>> wrote:


(1TB) /dev/sda4 /mnt/Storage1 symbolic link NAS1 -> /mnt/Storage1/
(1TB) /dev/sda5 /mnt/Storage2 symbolic link NAS2 -> /mnt/Storage2/
(1TB) /dev/sdb1 /mnt/Storage3 symbolic link NAS3 -> /mnt/Storage3/

Alias /discovery "/var/www/DirectoryLister"
<Directory /var/www/DirectoryLister>
Options +FollowSymLinks
AllowOverride ALL
Order Deny,Allow
Allow from 192.168.25.

Installation
3. Upload index.php and the resources folder to the folder you want listed

**Comment by PHLAK** [comment]
https://stackoverflow.com/a/21401899/27025

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
