### ISSUE TITLE
File directory contains Chinese display error, how can I fix it?

### ISSUE THREAD

**Issue by ju0632** [DirectoryLister/DirectoryLister#176]
File directory contains Chinese display error, how can I fix it?

**Comment by nixmomo** [comment]
Can you post a link so that i can look at it?

**Comment by CHN-STUDENT** [comment]
![tim 20171114183131](https://user-images.githubusercontent.com/21209416/32775359-32fcef6e-c96a-11e7-8885-ce5ec6c1d2f1.png)

![tim 20171114183154](https://user-images.githubusercontent.com/21209416/32775360-336235ea-c96a-11e7-93de-73050c5d30d2.png)

@nixmomo  Our Chinese usually use Chinese as files or directories 's name,but the Chinese name files or directories name can not display normal on the file directory.

As you see,i created a txt file named 中文测试.txt ,but it can not display normal on the file directory.

**Comment by CHN-STUDENT** [comment]
And i see people meet same issues on https://github.com/DirectoryLister/DirectoryLister/issues/121 ,but another people told file name need to use UTF-8.I guess my OS Windows using gb2132,so who can tell me how to fix it?

**Comment by nixmomo** [comment]
you can set your iso on two ways
1. Webserver config.
If in your config your is set correctly, you can set the iso in script too
2. set it in your Script theme
in ressources/theme/bootstrap/index.php is the iso set in line 3
It looks something like
```
 <!DOCTYPE html>
<?php
header('Content-Type: text/html; charset=UTF-8');
?>
<html>

    <head>
....

```
i can't test any chinese languages

**Comment by yimingriyue** [comment]
> you can set your iso on two ways
> 
> 1. Webserver config.
>    If in your config your is set correctly, you can set the iso in script too
> 2. set it in your Script theme
>    in ressources/theme/bootstrap/index.php is the iso set in line 3
>    It looks something like
> 
> ```
>  <!DOCTYPE html>
> <?php
> header('Content-Type: text/html; charset=UTF-8');
> ?>
> <html>
> 
>     <head>
> ....
> ```
> 
> i can't test any chinese languages

because chinese system chcp is 936 ，is gbk，not utf-8

**Comment by yimingriyue** [comment]
> ![tim 20171114183131](https://user-images.githubusercontent.com/21209416/32775359-32fcef6e-c96a-11e7-8885-ce5ec6c1d2f1.png)
> 
> ![tim 20171114183154](https://user-images.githubusercontent.com/21209416/32775360-336235ea-c96a-11e7-93de-73050c5d30d2.png)
> 
> @nixmomo Our Chinese usually use Chinese as files or directories 's name,but the Chinese name files or directories name can not display normal on the file directory.
> 
> As you see,i created a txt file named 中文测试.txt ,but it can not display normal on the file directory.
除了php文件添加代码外，还需要设置：
控制面板，区域，管理，更改系统区域设置，勾选 Beta版：使用 Unicode UTF-8提供全球语言支持（U）。重启。试过可以。

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
