### ISSUE TITLE
Can not work normally on webroot second-level directory

### ISSUE THREAD

**Issue by CHN-STUDENT** [DirectoryLister/DirectoryLister#178]
I want to have a download website(e.g `www.domain.com/download` )on my server webroot second-level directory.

But now i find it is not work when i visit `www.domain.com/download` and download file,because the file url is wrong.

The right url is `www.domain.com/download/file` but the wrong url is  `www.domain.com/file`,so the sever tell me 404 error.

Also,when i want to download the file from `www.domain.com/download/dir/file` (the file is on my server), but the url is also wrong.

But when i visit  `www.domain.com/download/` and download file,it can download normally.

Please do not understand my poor English and hope you can help me.

Thanks.

PS:My web sever is using `nginx 1.12` and `php 5.7`.

**Comment by nixmomo** [comment]
Hmm sounds like some rewrite rules from your nginx breaks the directorylister.

The Script works fine in subdirs, see on www.dl-host.info/downloads/

Can you post your configs from nginx?

**Comment by nixmomo** [comment]
can you comment out this line for testing
 include typecho.conf;

**Comment by CHN-STUDENT** [comment]
@nixmomo but the `typecho.conf` is a config about my blog system ‘s pseudo-static,i donot know how to do,can you give me some idea?Thanks.

**Comment by nixmomo** [comment]
sry but no idea yet. This config tells nginx that it always redirect file access to root /index.php and that's what your directorylister breaks.
Can you put the typecho.conf into a location block?
Something like:
location /home/www {
if (-f $request_filename/index.html) {
        rewrite (.*) $1/index.html break;
         }
        if (-f $request_filename/index.php) {
        rewrite (.*) $1/index.php;
         }
        if (!-f $request_filename) {
        rewrite (.*) /index.php;
         }
}

After that put your directorylister outside from your web directory and setup a new Location blog for it

location ^~ /downloads(/.*) {
root /home/directorylister;
}

not tested but should work to get the new location without your typecho.conf
where /downloads is, is your url path after domain... change it if needed.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
