### ISSUE TITLE
Problem with ZIP

### ISSUE THREAD

**Issue by fmohican** [DirectoryLister/DirectoryLister#179]
I can't download folder zip archive
There are log
```
2017/11/14 22:58:38 [error] 7884#14344: *1 FastCGI sent in stderr: "PHP Warning:  tempnam(): open_basedir restriction in effect. File(C:\WINDOWS\SERVIC~2\LOCALS~1\AppData\Local\Temp) is not within the allowed path(s): (D:\share) in D:\share\resources\DirectoryLister.php on line 130
PHP Warning:  filesize(): stat failed for .zip in D:\share\resources\DirectoryLister.php on line 136
PHP Warning:  fopen(.zip): failed to open stream: No such file or directory in D:\share\resources\DirectoryLister.php on line 140
PHP Warning:  fpassthru() expects parameter 1 to be resource, boolean given in D:\share\resources\DirectoryLister.php on line 141
PHP Warning:  unlink(.zip): No such file or directory in D:\share\resources\DirectoryLister.php on line 144" while reading response header from upstream, client: 86.121.***.***, server: s02.*****.ga, request: "GET /?zip=Sandboxie%205.10 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9123", host: "s02.*****.ga:2053", referrer: "https://s02.******.ga:2053/?dir=Sandboxie%205.10"
```

Is there something can i do? or need to wait for patch ?

**Comment by nixmomo** [comment]
its not a directorylister bug its more a error in your php config

`open_basedir restriction in effect. File(C:\WINDOWS\SERVIC~2\LOCALS~1\AppData\Local\Temp) is not within the allowed path(s):`

**Comment by nixmomo** [comment]
check your php.ini
there is a part called open_basedir
Can you post it here?

**Comment by fmohican** [comment]
"
;open_basedir =
"
yes it's not public webserver, they are hosted on my machine.

**Comment by nixmomo** [comment]
Sry im in Germany here it was night :) 
Are you sure you have the right php.ini?
Cann you create a file called info.php with this content
`<?php
phpinfo();
?>`
There is a line which php.ini is loaded.
if it really is this php.ini, uncomment your open_basedir like so
`open_basedir =`
Be sure the first ";" is deleted

**Comment by fmohican** [comment]
https://gist.github.com/fmohican/ab04917abc240cd73dc54ce14e8b2934

Here its is.

**Comment by nixmomo** [comment]
Ok..
go to C:\nginx\php\php.ini search for "open_basedir" and change it from
`;open_basedir`
to
`open_basedir="C:\;D:\"`
that should work

**Comment by fmohican** [comment]
Still isn't work.
[phpInfo-new](https://gist.github.com/fmohican/5b9453968ffcc1ca83c38974523b3996)

**Comment by nixmomo** [comment]
How looks your open_basedir line in the ini?

**Comment by fmohican** [comment]
`serialize_precision = 17

; open_basedir, if set, limits all file operations to the defined directory
; and below.  This directive makes most sense if used in a per-directory
; or per-virtualhost web server configuration file.
; http://php.net/open-basedir
;open_basedir = "D:\BitTorrent Download;E:\anime;G:\anime"
open_basedir = "C:\;D:\;E:\;G:\;"

; This directive allows you to disable certain functions for security reasons.
; It receives a comma-delimited list of function names.
; http://php.net/disable-functions
disable_functions =`

**Comment by nixmomo** [comment]
change it to
`open_basedir = "C:\;D:\;E:\;G:\"`

**Comment by fmohican** [comment]
Still isn't work
yes i restart php&nginx
[PhpInfo-3](https://gist.github.com/fmohican/8920b93d351cb97c1555bbe2208bfc80)

Logs from Nginx
`0.0.0.0 - - [26/Nov/2017:15:36:24 +0200] "GET /?zip=ePUB%20Dump%2006%20January%202013 HTTP/1.1" 200 5 "https://s02.AnonymousUser.ga:2053/?dir=ePUB%20Dump%2006%20January%202013" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
0.0.0.0 - - [26/Nov/2017:15:36:28 +0200] "GET /?dir=ePUB%20Dump%2006%20January%202013/Moore%2C%20Sir%20Roger HTTP/1.1" 200 1553 "https://s02.AnonymousUser.ga:2053/?dir=ePUB%20Dump%2006%20January%202013" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
0.0.0.0 - - [26/Nov/2017:15:36:29 +0200] "GET /?dir=ePUB%20Dump%2006%20January%202013/Moore%2C%20Sir%20Roger/Bond%20on%20Bond_%20Reflections%20on%2050%20Years%20of%20James%20Bond%20Movies HTTP/1.1" 200 1734 "https://s02.AnonymousUser.ga:2053/?dir=ePUB%20Dump%2006%20January%202013/Moore%2C%20Sir%20Roger" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
0.0.0.0 - - [26/Nov/2017:15:36:30 +0200] "GET /?zip=ePUB%20Dump%2006%20January%202013/Moore,%20Sir%20Roger/Bond%20on%20Bond_%20Reflections%20on%2050%20Years%20of%20James%20Bond%20Movies HTTP/1.1" 200 5 "https://s02.AnonymousUser.ga:2053/?dir=ePUB%20Dump%2006%20January%202013/Moore%2C%20Sir%20Roger/Bond%20on%20Bond_%20Reflections%20on%2050%20Years%20of%20James%20Bond%20Movies" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"`

**Comment by nixmomo** [comment]
hmm is don't see errors in this log... status 200 is the normal status for access

**Comment by fmohican** [comment]
Yes, but downloaded file still have 0 bytes and return "Damaged or Unknown format"

**Comment by nixmomo** [comment]
windows.... can you try to rename one zip into a filename without blank in and then test this...

**Comment by fmohican** [comment]
The zip have correct name and format but they have as size 0 Bytes

**Comment by nixmomo** [comment]
in your log is see "%20" and that is a blank... can you use a "-" instead a empty sign

**Comment by fmohican** [comment]
Sure. i will try

**Comment by fmohican** [comment]
```
0.0.0.0.0 - - [26/Nov/2017:15:48:50 +0200] "GET /?dir=JamesBond HTTP/1.1" 200 1465 "https://s02.SomeInternetUser:2053/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
0.0.0.0 - - [26/Nov/2017:15:48:52 +0200] "GET /?zip=JamesBond HTTP/1.1" 200 5 "https://s02.SomeInternetUser:2053/?dir=JamesBond" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
```

**Comment by nixmomo** [comment]
are we talking about zip files or the function to download a whole dir in zip format?

**Comment by fmohican** [comment]
whole dir in zip format via your [top right] button

**Comment by fmohican** [comment]
rest work fine.

**Comment by nixmomo** [comment]
can you post your config.php

**Comment by fmohican** [comment]
[config.php](https://gist.github.com/fmohican/40bc399a763e5407034eba470559ad5f)

**Comment by nixmomo** [comment]
Hmm... is it possible that you try to open the file before the stream / download is completed?
i tried both... blanks in name, stream and compression
https://directorylister.sugar-camp.com/?dir=web 

Can you test 
`    'zip_stream' => false,`

I have no Windows Server to test ... Windows is not a Serversystem for me...not for a webserver.. it is possible that php or webserver itself works different with the files itself

**Comment by fmohican** [comment]
I just tryed with `'zip_stream' => false,` but without success, same result...

**Comment by nixmomo** [comment]
hmm strange... do you get the same result from my testinstance? 
i have no idea how i can help you more cause i have not testsystems for windows and i can't reproduce your error :-(

**Comment by fmohican** [comment]
don't know, i will download your instance and i will test

**Comment by fmohican** [comment]
@nixmomo isn't work. (with your fork)
