### ISSUE TITLE
Bootstrap theme row element won't fill the container

### ISSUE THREAD

**Issue by bisherbas** [DirectoryLister/DirectoryLister#180]
I don't know how to properly describe the problem so I am including a screenshot. See that the elements on the right (header, file size) are not filling the container. They are aligned perfectly all the way to the right only when the window size is size; that is, col-lg class is induced. Any idea how to get around this problem? Thank you.

![Image](https://i.imgur.com/PBLH9Eu.png)

**Comment by nixmomo** [comment]
do you have a link where i can inspect?

**Comment by bisherbas** [comment]
I don't have a public link unfortunately. However I was able to fix the problem by eliminating different col sizes. In other words, all class options are set to 12. Now it looks much better.

**Comment by bisherbas** [comment]
Issue resolved back in Nov '17. Just learned that I could close issues myself!
