### ISSUE TITLE
Converting to WP Plugin

### ISSUE THREAD

**Issue by bisherbas** [DirectoryLister/DirectoryLister#181]
I am a newbie so I apologize asking this question here. How can I convert this beautiful directory lister to a WP plugin so I can easily display a directory on a WP page using a shortcode.

I used to use <iframe> but I converted my site from HTTP to HTTPS with proper SSL certificates. However, the major browsers do not like the fact that I am embedding another page on my own domain. For example, Chrome blocks the <iframe> object even though the SRC element points to HTTPS. Not HTTP. I can embed youtube videos with HTTPS without any problems but I cannot embed another page on my own domain. I don't know why.

So I am thinking if I can convert it to WP plugin I won't need to embed this script. Any thoughts?

**Comment by nixmomo** [comment]
Google isn't blocking iframe but it blocks http content on a https site.. All browsers doing this.

it isnt possible to migrate this Tool in a WP Plugin cause wordpress use a totaly different structure and totaly different eco system. They're many plugins for wordpress to list a directory but what is wrong with a link to the downloads?

**Comment by bisherbas** [comment]
Hey nixmomo. Thanks for your reply. Simple link doesn't work for me because the page doesn't look aesthetically pleasing. Anyhow, I was able to find a workaround. If I use a full link to folder in the SRC, then everybody is happy. Not sure why but it works!

**Comment by stevenzhu25** [comment]
Well.. You can link like this.

Use my site for example:
d.stevenz.xyz (root)
https://d.stevenz.xyz/?dir=server (that's d.stevenz.xyz/server folder)

@bisherbas  Hope this is what you want (i'm not good at English lol)

**Comment by nixmomo** [comment]
that is not a solution to migrate it into a wp plugin... 
That is a simple link which wasn't working for him...

**Comment by stevenzhu25** [comment]
@nixmomo I know, I can't really understand why he thought it's not pleasing/

**Comment by bisherbas** [comment]
Closing since it's not an issue with the DirectoryLister. Thanks for all the help.
