### ISSUE TITLE
Document analytics.inc

### ISSUE THREAD

**Issue by PHLAK** [DirectoryLister/DirectoryLister#186]
Add some document about the `analytics.inc` file and how it's supposed to be used.

**Comment by xAphex** [comment]
the project is dead, isn't it?

hasn't been updated since June 24, 2017.

**Comment by PHLAK** [comment]
@xAphex I don't want to call it dead, more like dormant. The code we have today is pretty old, messy and certainly not up to my current standards making it not very extensible or maintainable. I also have a full-time job, a family with two young children and many other items on my to-do list. All these things make it difficult for me to work on the existing version of Directory Lister. I do have plans to do a re-write from the ground up but that would require even more time which as you can see is sparse.

**Comment by xAphex** [comment]
oh, i never knew you have a full time job and two beautiful young children, hope it works out for you man, sorry if i came out as rude.

**Comment by nixmomo** [comment]
@PHLAK welcome back :+1:

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
