### ISSUE TITLE
Accessible?

### ISSUE THREAD

**Issue by llahnoraa** [DirectoryLister/DirectoryLister#187]
Is this plugin accessible? I've noticed there's no `"a" tag` in there but `"span" tag` so I wasn't even sure. I was able to navigate with keyboard but I need clarification first. Thank you!!

P.S. This plugin look flippin' cool!

**Comment by PHLAK** [comment]
Directory Lister has not bee specifically developed with accessibility in mind, sorry. Hopefully it can work for your needs anyway.
