### ISSUE TITLE
Warning: is_dir(): open_basedir restriction in effect. File FILENAME_IS_HERE   is not within the allowed path(s): 

### ISSUE THREAD

**Issue by nchapkanski** [DirectoryLister/DirectoryLister#190]
Hi,can youfix this error,Thanks
Warning: is_dir(): open_basedir restriction in effect. File(travolta/dance/?????�?? ??????N??�, F.O., D-ZastA & 42 - ??N?N??�N??????� (Official Video).mp3) is not within the allowed path(s): (D:\chsrvpld\srv\htdocs) in D:\chsrvpld\srv\htdocs\resources\DirectoryLister.php on line 628

Notice: Undefined offset: -1 in D:\chsrvpld\srv\htdocs\resources\DirectoryLister.php on line 370

Warning: is_dir(): open_basedir restriction in effect. File(travolta/dance/EMO feat. SANNY ALEXA - ???? ???? ?? ???? ?????? _ TQ NE E ZA MEN (Official Video).mp3) is not within the allowed path(s): (D:\chsrvpld\srv\htdocs) in D:\chsrvpld\srv\htdocs\resources\DirectoryLister.php on line 628

Notice: Undefined offset: -1 in D:\chsrvpld\srv\htdocs\resources\DirectoryLister.php on line 370

**Comment by nixmomo** [comment]
Did you read the message??
Warning: is_dir(): open_basedir restriction in effect. File( (Official Video).mp3) is not within the allowed path(s): (D:\chsrvpld\srv\htdocs) in D:\chsrvpld\srv\htdocs\resources\DirectoryLister.php

Its not a Bug in the script, its a missconfigured php installation...
see here to resolve it by yourself on your own server
https://github.com/DirectoryLister/DirectoryLister/issues/179
