### ISSUE TITLE
Sort "last modified"

### ISSUE THREAD

**Issue by TheSoulrester** [DirectoryLister/DirectoryLister#191]
how is it possible to sort to "last modified"?

**Comment by brendenb96** [comment]
Interested

**Comment by turbolift** [comment]
Interested

**Comment by Tampa** [comment]
So I forked from a fork that had the beginnings of this done and simply fixed an issue I encountered having the system in a subdirectory of the host, appears this now works properly. I have the code in my fork.

**Comment by PHLAK** [comment]
Feel free to open a PR.

**Comment by Tampa** [comment]
It's not all my code though...

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
