### ISSUE TITLE
Add Support with Bootstrap 4.0.0 Final

### ISSUE THREAD

**Issue by Azhe403** [DirectoryLister/DirectoryLister#192]
Bootstrap has now finall. please add support with Bootstrap 4.0.0 Final.

Thanks

**Comment by shmshd12** [comment]
Currently, Directory Lister doesn't have any major design flaw. Upgrading of the theme to the latest version can be done by yourself.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
