### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by Mottel** [DirectoryLister/DirectoryLister#194]
Where should I place the Google Analytics script to track my audience ?

 `<script async src="https://www.googletagmanager.com/gtag/js?id=mycode"></script>`
`<script>   window.dataLayer = window.dataLayer || [];   function gtag(){dataLayer.push(arguments);}   gtag('js', new Date());    gtag('config', 'mycode'); </script>`

**Comment by PHLAK** [comment]
You can place it in a file named `analytics.inc` in the same folder as your `index.php` and it will be automatically included.

**Comment by Mottel** [comment]
Thanks! Worked
