### ISSUE TITLE
upload files with header.php

### ISSUE THREAD

**Issue by kuzco1** [DirectoryLister/DirectoryLister#200]
Hello,
I have an issue to write an "add-on" to this great script.
Have created a header.php (inside the root directory) to allow me to upload files on the webserver.

When using /.../header.php I can do upload file into the folder, but when using the /../index.php which will call automatically header.php I am failing.
Error message is:
Warning: move_uploaded_file(): open_basedir restriction in effect. File(/tmp/phpPPMdZc) is not within the allowed path(s): (/home/dms/data) in /home/dms/data/header.php on line 34.

Line 34 is:
if(move_uploaded_file($tmpFilePath, $filePath)) {

Checking google, it seems I have to edit the open_basedir - have done this with: 
session_save_path('/home/dms/dmsdata/tmp');
Directory has permission 777.

Any hint how to solve this is welcome.

Regards
kuzco

**Comment by nixmomo** [comment]
Check your php.ini
/tmp/phpPPMdZc
is not
/home/dms/dmsdata/tmp
Add the correct path into your ini file
open_basedir = /tmp:/rest/of/your/paths

**Comment by kuzco1** [comment]
Thanks. This solved my issue.
