### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by TomHsiung** [DirectoryLister/DirectoryLister#203]
I edited the style.css file, adding following codes:

`body {
    padding: 70px 0 0;
    background-image: url("Greater_coat_of_arms_of_the_United_States.tif"), url("1st_Marine_Division_insignia.tif"), url("Seal_of_the_United_States_Department_of_the_Navy.tif"), url("United_States_Department_of_Defense_Seal.tif"), url("Seal_of_the_United_States_Marine_Corps.tif");
    background-repeat: no-repeat;
    background-position: 50% 50%, 95% 90%, 5% 90%, 5% 10%, 95% 10%;
    background-size: 40%, 15%, 15%, 15%, 15%;
    background-attachment: fixed, fixed, fixed, fixed, fixed;
}`

I uploaded the images to the directory where style.css located.

However, it did not work.

Tom

**Comment by PHLAK** [comment]
TIFF Images are [not supported in most browsers](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support).

**Comment by TomHsiung** [comment]
But, I could access those images via my Safari. Check that page: https://toms-therapeutics.site:50443/documents/Statistic%20Tools/statistical_calculator.html
