### ISSUE TITLE
password

### ISSUE THREAD

**Issue by peekaa** [DirectoryLister/DirectoryLister#206]
Feature request: to be able to protect listing with password. Thank you.

**Comment by rvalitov** [comment]
Really important feature!

**Comment by masumonline** [comment]
i need it too

**Comment by dev-aitch** [comment]
yeah nice feature,
but how the password should be handled? maybe in a classic `.htpasswd` file ?
or maybe you could just tell the script to ignore `the secret directory`, using the `config` file.

**Comment by Tampa** [comment]
.htpasswd wouldn't really require a change and is probably the most secure way. Problem is nginx does not support that sort of thing and it will always ask for a username even if none is specified. Password protection would mean a database and various security measures and there is still ways to get in. I don't see how this would also be any different from setting up say an owncloud, seafile or freenas system.

**Comment by PHLAK** [comment]
Actually Nginx does support this: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
