### ISSUE TITLE
Error greek lang

### ISSUE THREAD

**Issue by ghost** [DirectoryLister/DirectoryLister#211]
Hello,  error full name file greek lang

example

full name file ΒΟΗΘΟΣ%20ΦΑΡΜΑΚΕΙΟΥ.pdf
but do not show full name directory
only  ΦΑΡΜΑΚΕΙΟΥ.pdf

how to fix full name file ?

thanks

**Comment by wpCache** [comment]
ok i fix it

edit resources/DirectoryLister.php line 633

$directoryArray[pathinfo($relativePath, PATHINFO_BASENAME)] = array(

to

 preg_match('/\/([^\/]*)$/', $relativePath, $matches);
 $pathname = isset($matches[1]) ? $matches[1] : $relativePath;
 $directoryArray[$pathname] = array(

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
