### ISSUE TITLE
Disable zip downloads for particular directories doesn't work

### ISSUE THREAD

**Issue by ghost** [DirectoryLister/DirectoryLister#212]
I can't get it to function, the only 2 that actually worked was '*' which is no zips in any dirs and '*/*' which is no zip in the end dir. Neither of those are actually what im trying to achieve but the only 2 that appear to work.
This is running on its own drive which is on a volume named Raid or (/Volumes/Raid/)
Ive tried all sorts, */Raid, /Volumes/Raid/, /Volumes/Raid/(folder name I want to exclude) but none of it works

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
