### ISSUE TITLE
Change primary directory 

### ISSUE THREAD

**Issue by nubearm** [DirectoryLister/DirectoryLister#214]
the script is in: "/local/files/index.php"
and create a list of this folder "/files/"

I need to see that list from the file "/local/web1/lista.php" where I add an include_once ('../ files / index.php');

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
