### ISSUE TITLE
Icons not working using Fontawesome 5

### ISSUE THREAD

**Issue by ChacalYanqui88** [DirectoryLister/DirectoryLister#217]
The syntax `<i class="far <?php echo $fileInfo['icon_class']; ?> fa-fw"></i>` is not working using the new Fontawesome (v. 5.7.2). Any sugerence? Thank you all.

**Comment by ChacalYanqui88** [comment]
Syntax `<i class="far <?php echo $fileInfo['icon_class']; ?> fa-fw"></i>`

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
FYI, Directory Lister 3 uses Font Awesome 5 :slightly_smiling_face:
