### ISSUE TITLE
Use FilesystemIterator for better performance?

### ISSUE THREAD

**Issue by ArknightsTexas** [DirectoryLister/DirectoryLister#218]
Use ```FilesystemIterator``` to loop through directory can get better performance

**Comment by Tampa** [comment]
Elaborate? What exactly did you change and what is the measured performance increase?

**Comment by ArknightsTexas** [comment]
> Elaborate? What exactly did you change and what is the measured performance increase?

I used it in a directory with huge tons of files. And I got full CPU usage when I try to browse that directory with DirectoryLister, Webpage was stuck too. But when I use ```FilesystemIterator```, it's faster and won't get stuck again.

**Comment by Tampa** [comment]
You can fork this repo and apply your changes to the fork, then create a merge request for the code to be put into this repo. Though I am not sure how well this repo is maintained so you may not get a response on the request. I would certainly like to see what you changed in code to gather some data on page loading and system resource requirements to verify your claims.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
FYI, Directory Lister 3 utilizes the `syfony/finder` package under the hood which use an iterator. :slightly_smiling_face:
