### ISSUE TITLE
German umlauts

### ISSUE THREAD

**Issue by darkskyhp** [DirectoryLister/DirectoryLister#219]
Im using the Directory Listener for a school project but it doesn´t display german umlauts e.g. äöüß. Where schould i change the utf-8 format?

thanks in advance
darkskyhp

**Comment by bukowski12** [comment]
I have same problem with czech characters.
Problem is in pathinfo in method _readDirectory.

pathinfo() is locale aware, so for it to parse a path containing multibyte characters correctly, the matching locale must be set using the setlocale() function

So i add:    setlocale(LC_ALL, "cs_CZ.UTF-8"); in __construct
but better will be get locale from enviroment.

**Comment by Tampa** [comment]
For showing the files sure, but since the system supports wget, which itself struggles with umlauts I would say sticking to strict uft-8 might be the best option, it is the most compatible.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
