### ISSUE TITLE
'Too few arugment' error is PHP7.2

### ISSUE THREAD

**Issue by kmpatel** [DirectoryLister/DirectoryLister#220]
I'm not familiar with PHP, but apparently as of 7.1, failing to providing too few argument to a user defined function has been [promoted from warning to error](https://www.php.net/manual/en/migration71.incompatible.php).  As such, the following, on line 25, fails to initialize directory array:
    `$dirArray = $lister->listDirectory();`

The following fixes the problem:
   `$dirArray = $lister->listDirectory('.');`

**Comment by PHLAK** [comment]
Line 25 of what file?

**Comment by kmpatel** [comment]
Index.php

**Comment by PHLAK** [comment]
Maybe you're using an old version because this isn't an issue with the current version. Try updating your installation.
