### ISSUE TITLE
Cannot display directory contents because of two different error pages

### ISSUE THREAD

**Issue by gsoftwares** [DirectoryLister/DirectoryLister#221]
When I try to go into a subdir of the directory where the DirectoryLister PHP index is located I get two different error pages, one the first time then the other when i refresh.
![Screenshot at mag 05 22-00-32](https://user-images.githubusercontent.com/28053717/57199617-82f3f080-6f81-11e9-878f-b28e0c7d2789.png)
![Screenshot at mag 05 22-00-54](https://user-images.githubusercontent.com/28053717/57199618-82f3f080-6f81-11e9-95af-68a85439f927.png)
They change randomly between each other.

**Comment by SierraKomodo** [comment]
Quick bit of googling tells me the errors regarding `open_basedir` is due to a PHP configuration issue. This thread has some details on it including how to fix it in the second post: https://forum.joomla.org/viewtopic.php?t=710302

The remaining errors should clear up once that's corrected from my understanding.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
