### ISSUE TITLE
Cannot download a sql file

### ISSUE THREAD

**Issue by GeoTuxMan** [DirectoryLister/DirectoryLister#222]
Hi,

When I try to download a sql file, I got the message:
"The connection was reset"
But, works fine, with other type of files (txt, png,...)

I look forward for your tips/ideas.

**Comment by Tampa** [comment]
I'd say zip it up, makes it smaller too.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
