### ISSUE TITLE
How to sort by "Last Modified" in descending order as default?

### ISSUE THREAD

**Issue by grzegorzso** [DirectoryLister/DirectoryLister#227]
Hi

I really like DirectoryLister, but I can't manage to set the default sorting of files in a folder base on the "Last Modified" column in descending order. I just want to make, that every time I enter the directory the newest modified files show up on top, and the oldest on the bottom. 

Could someone help what to change to make that modification possible?

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
