### ISSUE TITLE
Android WebView bug

### ISSUE THREAD

**Issue by Unl12** [DirectoryLister/DirectoryLister#230]
hello,
i am making app for my class and i want to people can list informations. In chrome it looks normal and everything is working, but in android app webview it shows this:
![image](https://user-images.githubusercontent.com/34772045/64918324-e21e0900-d79c-11e9-86fd-0605bd13915e.png)
sorry for my bad english, i am not in english country

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
FYI, Directory Lister 3 now has full responsive support.
