### ISSUE TITLE
Upload feature request

### ISSUE THREAD

**Issue by andy9a9** [DirectoryLister/DirectoryLister#231]
Hello developers!

I would like to add a upload feature there. I think it would be great if users can upload some files into server. Integrate interface to upload files without additional connection like, ftp, scp... . If users want to add some file, they don't need to use additional system.

What do you think about it?

**Comment by PHLAK** [comment]
This is a great thought, however, file uploading is out of the scope for this project. While the idea of adding uploads to Directory Lister sounds like a good idea it would add a lot of complexity for the developers (i.e. me) and the users. Additionally, uploads would increase the chance of security risks substantially. The intent of Directory Lister has always been to keep things simple, straight forward and as secure as possible and file uploads does not fit this intent.
