### ISSUE TITLE
Problem With Bootstrap 4

### ISSUE THREAD

**Issue by moizkhanyousafzai** [DirectoryLister/DirectoryLister#232]
When i try to use Bootstap 4 cdn at default_header.php the design gets messed.

**Comment by PHLAK** [comment]
This wont work. Bootstrap 4 was a major change from Bootstrap 3 and would therefor require a rework to the design.

**Comment by moizkhanyousafzai** [comment]
I Changed the UI with bootstrap 4 and working fine, Thanks for this amazing Project.
