### ISSUE TITLE
http code for inexistent paths should be 404 instead of 200

### ISSUE THREAD

**Issue by amo13** [DirectoryLister/DirectoryLister#234]
Even though the page correctly states that the "File path does not exist", the http code is 200. It should be a 404.

https://demo.directorylister.com/?dir=inexistent

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
FYI, this has been addressed in Directory Lister 3.
