### ISSUE TITLE
got error 404

### ISSUE THREAD

**Issue by securiteinfo** [DirectoryLister/DirectoryLister#245]
Hello,

After installation from ZIP v3.0.0-beta.1 in a directory, when I call this directory in a browser, I got error 404.
I can call LICENSE, README.md and even .env files and get the content of these files.
But calling index.php, explicitely or not, I always get 404 error.

Any other users have this problem ?

Regards

**Comment by PHLAK** [comment]
Thanks for the feedback. Can I get some additional information to help troubleshoot?


**What version of PHP do you have installed?**

You can run `php --version` on the command line to find out.

**What HTTP server are you using to serve Directory Lister?**

e.g Apache, NGINX, etc...

Are you able to provide any error logs with more information?

**Comment by securiteinfo** [comment]
PHP is from Debian stable :
php --version
PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

I use Apache 2.4.38

There is no error log, only access log that shows a 404 response with no other information : 
[22/Jan/2020:19:46:26 +0100] "GET /masked/index.php HTTP/1.1" **404** 2751 "https://domain/masked/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"

**Comment by PHLAK** [comment]
Can you share your Apache site config? Look for this in `/etc/apache2/sites-available/your-site-name.conf`

**Comment by securiteinfo** [comment]
Hello Phlak,

I think I have found a solution : in your archives (DirectoryLister-3.0.0-beta.1.tar.gz and DirectoryLister-3.0.0-beta.1.zip) there is no .htaccess included. If I include the one in your repository (https://github.com/DirectoryLister/DirectoryLister/blob/3.0.0-beta.1/.htaccess) Apache does not return 404 error.
Did you forget this file in your releases ?

**Comment by PHLAK** [comment]
DOH! Yes, that's exactly the problem @securiteinfo, I forgot to include the `.htaccess` in the release builds. Thank you for figuring that out!

**Comment by securiteinfo** [comment]
You are welcome :)

**Comment by PHLAK** [comment]
This is now fixed in the [second beta release](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.0.0-beta.2).
