### ISSUE TITLE
3.0.0 Beta 2 installation is not working 

### ISSUE THREAD

**Issue by securiteinfo** [DirectoryLister/DirectoryLister#249]
Hello FLACK,

Using DirectoryLister-3.0.0-beta.2 and doing fresh installation from tar.gz archive, it still does not work.
I had done : 
cp .env.example .env
and
chown -R www-data:www-data *
and even to be sure it is not a permission problem : 
chmod -R 777 *

Please see below the result : 
![dl](https://user-images.githubusercontent.com/12692146/73052138-ab5faa00-3e84-11ea-9428-403d9dc6fd7a.png)
On the left, the render in a browser
On the right, the 404 errors with browser in dev mod

Here are my server logs : 
[Fri Jan 24 08:38:44.840085 2020] [core:info] [pid 744] [client 192.168.xx.xx:59178] AH00128: File does not exist: /var/www/html/app/dist/app.css, referer: http://192.168.xx.xx/DirectoryLister-3.0.0-beta.2/index.php
[Fri Jan 24 08:38:44.840804 2020] [core:info] [pid 744] [client 192.168.xx.xx:59178] AH00128: File does not exist: /var/www/html/app/dist/app.js, referer: http://192.168.xx.xx/DirectoryLister-3.0.0-beta.2/index.php
[Fri Jan 24 08:38:44.930498 2020] [core:info] [pid 744] [client 192.168.xx.xx:59178] AH00128: File does not exist: /var/www/html/app/dist/app.js
[Fri Jan 24 08:38:44.947563 2020] [core:info] [pid 744] [client 192.168.xx.xx:59178] AH00128: File does not exist: /var/www/html/app/resources/images/favicon.light.png

As far as I know, app folder is *NOT* in my root webserver, but in /DirectoryLister-3.0.0-beta.2/ (or /var/www/html/DirectoryLister-3.0.0-beta.2/ for full path on my server)
This is the cause of the 404 errors.

FLACK, Did you tried to install Directory Lister on your side on a regular Apache installation ?

Regards,
Arnaud

**Comment by PHLAK** [comment]
Did you perhaps download `Source code (tar.gz)` instead of [`DirectoryLister-3.0.0-beta.2.tar.gz`](https://github.com/DirectoryLister/DirectoryLister/releases/download/3.0.0-beta.2/DirectoryLister-3.0.0-beta.2.tar.gz)?

The `Source code (tar.gz)` is auto-generated by GitHub and does not contain all the necessary files for Directory Lister to run.

**Comment by securiteinfo** [comment]
Hi,
No, I downloaded and installed from DirectoryLister-3.0.0-beta.2.tar.gz (md5 : 8d033cfbfb8d07790c8bb40e3bc8e7cc)

**Comment by PHLAK** [comment]
I see all the files you're missing in the archive:

```shell
$ md5sum DirectoryLister-3.0.0-beta.2.tar.gz 
8d033cfbfb8d07790c8bb40e3bc8e7cc  DirectoryLister-3.0.0-beta.2.tar.gz

$ tar --list --verbose --file=DirectoryLister-3.0.0-beta.2.tar.gz
drwxr-xr-x chris/chris       0 2020-01-21 23:29 app/
drwxr-xr-x chris/chris       0 2020-01-23 08:16 app/dist/
-rw-r--r-- chris/chris   67896 2020-01-23 08:16 app/dist/app.css
drwxr-xr-x chris/chris       0 2020-01-23 08:16 app/dist/webfonts/
-rw-r--r-- chris/chris   76084 2020-01-23 08:16 app/dist/webfonts/fa-solid-900.woff2
-rw-r--r-- chris/chris   13576 2020-01-23 08:16 app/dist/webfonts/fa-regular-400.woff2
-rw-r--r-- chris/chris   16800 2020-01-23 08:16 app/dist/webfonts/fa-regular-400.woff
-rw-r--r-- chris/chris   34390 2020-01-23 08:16 app/dist/webfonts/fa-regular-400.eot
-rw-r--r-- chris/chris  131624 2020-01-23 08:16 app/dist/webfonts/fa-brands-400.ttf
-rw-r--r-- chris/chris  708706 2020-01-23 08:16 app/dist/webfonts/fa-brands-400.svg
-rw-r--r-- chris/chris  144322 2020-01-23 08:16 app/dist/webfonts/fa-regular-400.svg
-rw-r--r-- chris/chris  194066 2020-01-23 08:16 app/dist/webfonts/fa-solid-900.eot
-rw-r--r-- chris/chris   75936 2020-01-23 08:16 app/dist/webfonts/fa-brands-400.woff2
-rw-r--r-- chris/chris   98996 2020-01-23 08:16 app/dist/webfonts/fa-solid-900.woff
-rw-r--r-- chris/chris  131930 2020-01-23 08:16 app/dist/webfonts/fa-brands-400.eot
-rw-r--r-- chris/chris  849145 2020-01-23 08:16 app/dist/webfonts/fa-solid-900.svg
-rw-r--r-- chris/chris  193780 2020-01-23 08:16 app/dist/webfonts/fa-solid-900.ttf
-rw-r--r-- chris/chris   89100 2020-01-23 08:16 app/dist/webfonts/fa-brands-400.woff
-rw-r--r-- chris/chris   34092 2020-01-23 08:16 app/dist/webfonts/fa-regular-400.ttf
-rw-r--r-- chris/chris  123566 2020-01-23 08:16 app/dist/app.js
-rw-r--r-- chris/chris      87 2020-01-23 08:16 app/dist/app.js.LICENSE
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/resources/
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/resources/images/
-rw-r--r-- chris/chris    1928 2020-01-21 23:28 app/resources/images/favicon.dark.png
-rw-r--r-- chris/chris    1889 2020-01-21 23:28 app/resources/images/favicon.light.png
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/resources/sass/
-rw-r--r-- chris/chris    1771 2020-01-21 23:28 app/resources/sass/dark-mode.scss
-rw-r--r-- chris/chris    1500 2020-01-21 23:28 app/resources/sass/markdown.scss
-rw-r--r-- chris/chris     477 2020-01-21 23:28 app/resources/sass/app.scss
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/resources/views/
-rw-r--r-- chris/chris     364 2020-01-21 23:28 app/resources/views/404.twig
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/resources/views/layouts/
-rw-r--r-- chris/chris     550 2020-01-21 23:28 app/resources/views/layouts/app.twig
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/resources/views/components/
-rw-r--r-- chris/chris     963 2020-01-21 23:28 app/resources/views/components/footer.twig
-rw-r--r-- chris/chris    1564 2020-01-21 23:28 app/resources/views/components/header.twig
-rw-r--r-- chris/chris     559 2020-01-21 23:28 app/resources/views/components/readme.twig
-rw-r--r-- chris/chris    1490 2020-01-21 23:28 app/resources/views/components/file.twig
-rw-r--r-- chris/chris     528 2020-01-21 23:28 app/resources/views/components/scroll-to-top.twig
-rw-r--r-- chris/chris    1386 2020-01-21 23:28 app/resources/views/index.twig
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/resources/js/
-rw-r--r-- chris/chris     705 2020-01-21 23:28 app/resources/js/app.js
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/resources/js/components/
-rw-r--r-- chris/chris    3431 2020-01-21 23:28 app/resources/js/components/file-info-modal.vue
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/Support/
-rw-r--r-- chris/chris     750 2020-01-21 23:28 app/Support/Helpers.php
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/cache/
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/SortMethods/
-rw-r--r-- chris/chris     353 2020-01-21 23:28 app/SortMethods/Accessed.php
-rw-r--r-- chris/chris     332 2020-01-21 23:28 app/SortMethods/Type.php
-rw-r--r-- chris/chris     350 2020-01-21 23:28 app/SortMethods/Changed.php
-rw-r--r-- chris/chris     353 2020-01-21 23:28 app/SortMethods/Modified.php
-rw-r--r-- chris/chris     349 2020-01-21 23:28 app/SortMethods/Natural.php
-rw-r--r-- chris/chris     332 2020-01-21 23:28 app/SortMethods/Name.php
-rw-r--r-- chris/chris     297 2020-01-21 23:28 app/SortMethods/SortMethod.php
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/Providers/
-rw-r--r-- chris/chris    3214 2020-01-21 23:28 app/Providers/FinderProvider.php
-rw-r--r-- chris/chris     626 2020-01-21 23:28 app/Providers/ConfigProvider.php
-rw-r--r-- chris/chris    1870 2020-01-21 23:28 app/Providers/TwigProvider.php
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/Bootstrap/
-rw-r--r-- chris/chris    1664 2020-01-21 23:28 app/Bootstrap/AppManager.php
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/config/
-rw-r--r-- chris/chris    3287 2020-01-21 23:28 app/config/icons.php
-rw-r--r-- chris/chris     609 2020-01-21 23:28 app/config/view.php
-rw-r--r-- chris/chris    1516 2020-01-21 23:28 app/config/app.php
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/ViewFunctions/
-rw-r--r-- chris/chris     475 2020-01-21 23:28 app/ViewFunctions/Config.php
-rw-r--r-- chris/chris     799 2020-01-21 23:28 app/ViewFunctions/Breadcrumbs.php
-rw-r--r-- chris/chris     747 2020-01-21 23:28 app/ViewFunctions/ViewFunction.php
-rw-r--r-- chris/chris    1116 2020-01-21 23:28 app/ViewFunctions/Asset.php
-rw-r--r-- chris/chris     407 2020-01-21 23:28 app/ViewFunctions/Markdown.php
-rw-r--r-- chris/chris     497 2020-01-21 23:28 app/ViewFunctions/ParentDir.php
-rw-r--r-- chris/chris     640 2020-01-21 23:28 app/ViewFunctions/Icon.php
-rw-r--r-- chris/chris     670 2020-01-21 23:28 app/ViewFunctions/SizeForHumans.php
drwxr-xr-x chris/chris       0 2020-01-21 23:28 app/Controllers/
-rw-r--r-- chris/chris    3706 2020-01-21 23:28 app/Controllers/DirectoryController.php
-rw-r--r-- chris/chris    1659 2020-01-21 23:28 app/Controllers/FileInfoController.php
drwxr-xr-x chris/chris       0 2020-01-23 08:16 node_modules/
[Omitted node_modules/* subdirectories for brevity]
drwxr-xr-x chris/chris       0 2020-01-23 08:15 vendor/
[Omitted vendor/* subdirectories for brevity]
-rw-r--r-- chris/chris     168 2020-01-21 23:28 .env.example
-rw-r--r-- chris/chris     325 2020-01-21 23:28 .htaccess
-rw-r--r-- chris/chris   16650 2020-01-21 23:28 directory-lister.svg
-rw-r--r-- chris/chris    1101 2020-01-21 23:28 LICENSE
-rw-r--r-- chris/chris     141 2020-01-23 08:16 mix-manifest.json
-rw-r--r-- chris/chris    2590 2020-01-21 23:28 README.md
-rw-r--r-- chris/chris     656 2020-01-21 23:28 index.php
```

Make sure all the files have been uploaded to the installation location. If they're there and you're still getting missing file errors try restarting your webserver (i.e. something like `sudo service apache2 restart`).

**Comment by PHLAK** [comment]
I may have identified the issue. Are you running DirectoryLister from a sub-directory (e.g. `https://example.com/some-directory`)?

**Comment by securiteinfo** [comment]
Yes, it is running from a subdir : /var/www/html/DirectoryLister-3.0.0-beta.2 means https://exemple.com/DirectoryLister-3.0.0-beta.2

**Comment by PHLAK** [comment]
So at this point I'm pretty sure this is (mostly) an issue with the included `.htaccess` configuration and I need to figure out the proper configuration to get this working from a sub-directory. I'll read up on Apache (and Nginx) configs and keep working on this but if anyone has any recommendations I'm all ears.

**Comment by Tampa** [comment]
In a sub-directory RewriteCond %{REQUEST_URI} (.+)/$ is not going to be met, the problem is then it tries to go to the domain/ instead of the subdirectory. htaccess however has no way to tell where it is in, there are some workarounds for this to make it work inside the subdirectory, unfortunately that cannot work on nginx. I have not dug in the code yet, mainly cause goodness me this thing got way too complex for a more advanced "indexes", but the missing reference should be set in the code as ../ and not a direct reference that ignores potential subdirectory installations, because that is far easier to accomplish in php than it is in htaccess and nginx(despite that proper server configuration would fix this here the idea is not to have to touch the server config to get this installed and working).

I'll hear about what I can find, I know someone who could write you a kernel in nginx configs if there was a way to do that, so may be able to fix this.

**Comment by PHLAK** [comment]
I spent last night fixing most of the issues related to running Directory Lister from a sub-directory. I believe the only remaining issue is the file info pop up. I'll continue to work on this shortly and hopefully push a new beta release soon.

**Comment by PHLAK** [comment]
I think I've fixed the info pop up and will try to get a new release out later today.

**Comment by PHLAK** [comment]
@securiteinfo [Beta 3](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.0.0-beta.3) is available and should fix running Directory Lister from a sub-directory. Please try this out when you have a moment and let me know if it's working for you.

**Comment by securiteinfo** [comment]
Hello,

Yes, it seems to work now !
Thank you and good job !

Le 27/01/2020 à 22:54, Chris Kankiewicz a écrit :
