### ISSUE TITLE
DefaultRoot

### ISSUE THREAD

**Issue by Mikopet** [DirectoryLister/DirectoryLister#25]
I think, it's been a good feature, to add a config parameter, called default root.
In that line u can set the directory.

For example, i made a symlink near the index.php. I want only list this folder. And if i can set that, that would be great :D

**Comment by insink71** [comment]
this or baseurl in config.php would be great.  2.5.5 seems to be broken out of the box on our site.  https://files.teamblueridge.org .. choose a dir, then try to go back to parent.  It can't find baseurl; so, its redirecting to http:/// .  Not good.

**Comment by muuvmuuv** [comment]
Is there already a solution ?

**Comment by ddanna** [comment]
Anyone find a fix? I'd like to list files in the parent of my www directory...

**Comment by alexander255** [comment]
Well, my "fix" for this was to just use my code and not update any longer. No going to do any more work on this, unless I'm being guaranteed that it's going to be merge…

**Comment by jeevanmp** [comment]
Hey, its been 3 years and I see no solution to this issue.
I am using xampp and I want my dropbox to be the content of my directory which will then be displayed on the list. How am I be able to do that?

**Comment by TimothyJimothy** [comment]
I'm hoping to use this, however I need it to point to a different drive (an SD card on a  Raspberry Pi/Arduino). basically the main drive will have have the www/html folder, and I need  to point to the SD card to be able to view the .log files stored there. Is this possible?

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
Starting with the [v5.0.0 release](https://github.com/DirectoryLister/DirectoryLister/releases/tag/5.0.0) it is now possible to list any directory (even one outside of the application installation path) via the [`FILE_PATH` environment variable](https://docs.directorylister.com/configuration/app-config-reference#files_path).
