### ISSUE TITLE
Bloat

### ISSUE THREAD

**Issue by Tampa** [DirectoryLister/DirectoryLister#250]
The issue of fixing up the subdirectory handling prompted me to look at quite a few files and frankly I am somewhat in shock. What was a small set of files and a folder easily stuffed into a directory to make it less ugly than simple indexes has turned into such a massive project it might as well come as its own webserver.

I compared various metrics, main size, loading times and load order. All in all it increased ten-fold.

Loading times of the old version on ten folders and ten files in view is 139ms on average.
The same in the new version is over 1000ms with a tolerance of 100ms.

The old version was zipped not 20kb, the new is almost 4mb in size. This is because of the many different files, unzipped over 10mb with the result that the page starts loading things randomly down the line, because so much needs to be loaded.

I also checked browser compatibility and basically anything before 2010 will end up rendering slightly differently and in case someone is still using browsers or apps from before that to access may be greeted with a page not obeying half the css and freaking out with js errors. The old version, according to the tests anyway is only not compatible with browsers from the time netscape was a thing.

Honestly, we have come full circle here, it went from nice and lean to total bloat. I am not sure what framework it was that made you jump up with glee or what library you really desperately wanted to use despite only doing a single thing, but frankly said this has become so bloated it would make more sense install owncloud or whatever and present files that way. This is farther away from the old version in the important metrics than it ever was from webserver index, which is not making it look good.

I know pretty design is what drives people to use it and the features are useful, but to use a complex framework, various libraries and includes all for showing some files and folders is just over the top, surely you must see how crazy that actually is when you think about it. There is more "framework" here than in some content management systems I have seen.

For what it's worth I really think you either need to take a hacksaw to this thing and gut it as much as possible, rewriting some bloated libraries with only the stuff you actually need or simply go back to the roots and aim for some true lightweight design. Think of it as a challenge, all it is now in a file and a folder and not, well this. That's my closing statement, I think I will depart and work on my fork or maybe look for a different similar project. Sorry, but yikes what happened here...

**Comment by PHLAK** [comment]
Hey @Tampa, I'm sorry you feel this way. However, please remember, **Directory Lister 3 is still in beta and we are working on improving things where possible** and will continue that work even after stable release.

Hopepefully I can address your concerns here but first let's gather some statistics. For this I will be using `phploc` to compare the last stable release (`v2.7.1`) against the latest beta code on `master` (as of right now that is the [`e1c6f1b`](https://github.com/DirectoryLister/DirectoryLister/tree/e1c6f1b85c7c3532cdf7839e440bc8429c0e2398) commit). Let's take a look (expand the sections below for the details).

<details>
<summary>DirectoryLister v2.7.1</summary>

```
DirectoryLister (2.7.1) $ phploc .
phploc 5.0.0 by Sebastian Bergmann.

Directories                                          2
Files                                                7

Size
  Lines of Code (LOC)                             1338
  Comment Lines of Code (CLOC)                     324 (24.22%)
  Non-Comment Lines of Code (NCLOC)               1014 (75.78%)
  Logical Lines of Code (LLOC)                     224 (16.74%)
    Classes                                        180 (80.36%)
      Average Class Length                         180
        Minimum Class Length                       180
        Maximum Class Length                       180
      Average Method Length                          7
        Minimum Method Length                        1
        Maximum Method Length                       28
    Functions                                        0 (0.00%)
      Average Function Length                        0
    Not in classes or functions                     44 (19.64%)

Cyclomatic Complexity
  Average Complexity per LLOC                     0.51
  Average Complexity per Class                  100.00
    Minimum Class Complexity                    100.00
    Maximum Class Complexity                    100.00
  Average Complexity per Method                   5.30
    Minimum Method Complexity                     1.00
    Maximum Method Complexity                    24.00

Dependencies
  Global Accesses                                   23
    Global Constants                                11 (47.83%)
    Global Variables                                 0 (0.00%)
    Super-Global Variables                          12 (52.17%)
  Attribute Accesses                                63
    Non-Static                                      63 (100.00%)
    Static                                           0 (0.00%)
  Method Calls                                      31
    Non-Static                                      31 (100.00%)
    Static                                           0 (0.00%)

Structure
  Namespaces                                         0
  Interfaces                                         0
  Traits                                             0
  Classes                                            1
    Abstract Classes                                 0 (0.00%)
    Concrete Classes                                 1 (100.00%)
  Methods                                           23
    Scope
      Non-Static Methods                            23 (100.00%)
      Static Methods                                 0 (0.00%)
    Visibility
      Public Methods                                17 (73.91%)
      Non-Public Methods                             6 (26.09%)
  Functions                                          0
    Named Functions                                  0 (0.00%)
    Anonymous Functions                              0 (0.00%)
  Constants                                          4
    Global Constants                                 3 (75.00%)
    Class Constants                                  1 (25.00%)
```
</details>


<details>
<summary>Directory Lister 3 (beta)</summary>

```
DirectoryLister (e1c6f1b) $ phploc --exclude app/cache/ app/
phploc 5.0.0 by Sebastian Bergmann.

Directories                                         16
Files                                               36

Size
  Lines of Code (LOC)                             2103
  Comment Lines of Code (CLOC)                     438 (20.83%)
  Non-Comment Lines of Code (NCLOC)               1665 (79.17%)
  Logical Lines of Code (LLOC)                     532 (25.30%)
    Classes                                        349 (65.60%)
      Average Class Length                          10
        Minimum Class Length                         1
        Maximum Class Length                        50
      Average Method Length                          3
        Minimum Method Length                        1
        Maximum Method Length                       37
    Functions                                        0 (0.00%)
      Average Function Length                        0
    Not in classes or functions                    183 (34.40%)

Cyclomatic Complexity
  Average Complexity per LLOC                     0.08
  Average Complexity per Class                    2.30
    Minimum Class Complexity                      1.00
    Maximum Class Complexity                     10.00
  Average Complexity per Method                   1.40
    Minimum Method Complexity                     1.00
    Maximum Method Complexity                    10.00

Dependencies
  Global Accesses                                    5
    Global Constants                                 0 (0.00%)
    Global Variables                                 0 (0.00%)
    Super-Global Variables                           5 (100.00%)
  Attribute Accesses                               134
    Non-Static                                     134 (100.00%)
    Static                                           0 (0.00%)
  Method Calls                                     186
    Non-Static                                     158 (84.95%)
    Static                                          28 (15.05%)

Structure
  Namespaces                                         7
  Interfaces                                         0
  Traits                                             0
  Classes                                           33
    Abstract Classes                                 2 (6.06%)
    Concrete Classes                                31 (93.94%)
  Methods                                           95
    Scope
      Non-Static Methods                            94 (98.95%)
      Static Methods                                 1 (1.05%)
    Visibility
      Public Methods                                78 (82.11%)
      Non-Public Methods                            17 (17.89%)
  Functions                                         11
    Named Functions                                  0 (0.00%)
    Anonymous Functions                             11 (100.00%)
  Constants                                          6
    Global Constants                                 0 (0.00%)
    Class Constants                                  6 (100.00%)
```
</details>

Now onto your concerns...

> What was a small set of files and a folder ... has turned into such a massive project

So let's start by comparing files and logical lines of code (that is any line of code that has any content other than a comment or whitespace). According to `phploc` here's the breakdown:

|        | v2.7.1 | v3 beta |
| ------ | ------ | ------- |
| Files  | 7      | 36      |
| LLOC  | 224    | 532     |

From these stats you're not wrong. Directory Lister 3 has a lot more files and lines of code. However, this isn't the complete story. Let's look at some of the other statistics.

|                               | v2.7.1 | v3 beta |
| ----------------------------- | ------ | ------- |
| Average Class Length          | 180    | 10      |
| Average Complexity per LLOC   | 0.51   | 0.08    |
| Average Complexity per Class  | 100.00 | 2.30    |
| Average Complexity per Method | 5.30   | 1.40    |

As you can see, by applying modern design principles, we've managed to vastly reduce the complexity of code. This will in turn make for a more managable and maintainable code base going forward.

On the other hand, with v3 we have pulled in several external dependencies (found in the `node_modules` and `vendor` directories). These are libraries written by others we then use to make Directory Lister work. I can understand how these can make the project seem much larger than it actually is, however, this is all code we do not have to maintain and are not required to understand the inner workings of to use. Also, I plan on moving the dependencies into the `app` directory to better hide them from the end users.

> I compared various metrics, main size, loading times and load order. All in all it increased ten-fold.

This seems a bit unsubstantiated and in my own anecdotal tests when comparing https://demo.directorylister.com to https://demo-beta.directorylister.com I'm seeing v2.7.1 load in ~500-700ms and v3 load in ~600-800ms, that's a difference of 100ms on average. Keep in mind, this is with new functionality that v2 didn't have.

More interestingly though is I've spent little to no time actually trying to optimize v3 yet. Up until now it's been mostly about getting it working first which means there's likely room for improvement. I have some ideas (e.g. improved caching) that will hopefully improve performance that I will be applying in the future.

> The old version was zipped not 20kb, the new is almost 4mb in size.

Most of this size comes from the few images and web fonts (Font Awesome). We will continue working to minimize the size and amount of files but in our opinion a few dozen megabytes isn't a big concern.

> I also checked browser compatibility and basically anything before 2010 will end up rendering slightly differently

Having spent little time attempting to optimize v3 for maximum browser compatibility that fact that it works with anything up to **A DECADE** old is great news! If there are any _specific_ compatibility issuses you feel should be addressed please open an issue for it and we'll go from there.

> ...it would make more sense install owncloud or whatever and present files that way.

You're more than welcome to do that and you wouldn't hurt my feelings. One of the great things about open source software is the freedom of choice.

> I think I will depart and work on my fork or maybe look for a different similar project.

Again, I'd like reiterate, Directory Lister is currently in beta and we'll continue working to make it better. Unfortunately, in this instance, I don't think "better" means the same thing to you and I. Either way I wish you the best in whatever you decide.

**Comment by PHLAK** [comment]
For what it's worth, the [beta.3](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.0.0-beta.3) release has reduced the release archive size and removed/hid a many files from the project root.

**Comment by bmuessig** [comment]
I do like the project a lot, but over 1500 files for a 'simple' PHP directory listing is insane.

**Comment by PHLAK** [comment]
Where are you getting the number 1500?

    $ git ls-files | wc -l
    153

There is 153 files checked into source control (i.e. git).

    $ find -type f | wc -l
    1325
    
    $ find -type f ! -path './app/vendor/*' ! -path './app/assets/webfonts/*' | wc -l
    72

The final build is a little over 1300 files **including dependencies** and under 75 without.

Sure there's lots of other files used during development but the vast majority of these files are of little concern to developers and **zero** concern to the end-users.

**Comment by bmuessig** [comment]
My download of the latest version includes over 1500 files. Most of them are included in the external packages in the vendor folder. Having that many large dependencies means that any one of these can have more than one security vulnerability. But yeah, keeping that many dependencies updated is going to require a lot of effort on your side and makes updating on the server side cumbersome, which will make a lot of people think twice before updating. So it is a concern to both.
Don't get me wrong, I do like your software, it works well and looks good, but it's a lot larger than it has to be.

**Comment by PHLAK** [comment]
We use [Dependabot]() to automate dependency updates (see an example of that in action [here](https://github.com/DirectoryLister/DirectoryLister/pull/385)) and also have a convenient [`make update`](https://github.com/DirectoryLister/DirectoryLister/blob/master/Makefile#L12-L13) command for updating all dependencies locally.
