### ISSUE TITLE
how to exclude 1 or more extension to show in directory 

### ISSUE THREAD

**Issue by buio2005** [DirectoryLister/DirectoryLister#254]
Hi ! and congrats for your project 
I would to know if there is a possibility to hide some extension from the file list showing on directory 
Eg : I had to upload some files .zip into a folder/directory whre there is index.php 
I would not to show index.php so I presume i should hide .php extension 

Is that possible and how ? 
thank you !

**Comment by PHLAK** [comment]
When the [`hide_app_files`](https://github.com/DirectoryLister/DirectoryLister/wiki/App-Config-Reference#hide_app_files) option is enabled (it is by default) `index.php` should be hidden.

If you'd like to hide additional files you can modify the [`hidden_files`](https://github.com/DirectoryLister/DirectoryLister/wiki/App-Config-Reference#hidden_files) option in your app config located at `app/config/app.php`.

To hide all php files in the parent directory this should work:

```php
'hidden_files' => [
    '*.php'
]
```

**Comment by webmaster-sites** [comment]
i used '*.jpg' but it did not work
