### ISSUE TITLE
error on simbolic link

### ISSUE THREAD

**Issue by mikysal78** [DirectoryLister/DirectoryLister#256]
Directory Lister Version 2.7.1 (stable)
PHP Version 7.3.11-1
System Debian Buster with ispconfig (stable) and apache2

in my web root i have 2 simbolic link and i have 2 error

- date error: see "Last Modified: 1970"
- click link i have classic index/of

See http://downloads.nnxx.ninux.org/

**Comment by PHLAK** [comment]
Hey @mikysal78, thanks for reporting this. However, at this time all work on Directory Lister 2.X has ceased so we can concentrate on Directory Lister 3 (now available in beta). If you'd like, please try the beta and let us know if this issue is still a problem. See https://beta.directorylister.com/ for more info about Directory Lister 3 beta.

**Comment by mikysal78** [comment]
@PHLAK i testing beta but i have error 500.
this is log error apache

[Sat Feb 08 16:53:03.220667 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./firmware) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220703 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./firmware) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220707 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./openwisp-config) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220709 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./openwisp-config) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220712 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./firmware) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220714 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./firmware) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220716 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./openwisp-config) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220719 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./openwisp-config) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 76, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220721 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./firmware) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/SortableIterator.php on line 91, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220732 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Warning:  RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./openwisp-config) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/SortableIterator.php on line 91, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220762 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: PHP Fatal error:  Uncaught RuntimeException: SplFileInfo::isDir(): open_basedir restriction in effect. File(./firmware) is not within the allowed path(s): (/var/www/clients/client3/web18/web) in /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/SortableIterator.php:55, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220768 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: Stack trace:, referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220770 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: #0 /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/SortableIterator.php(55): SplFileInfo->isDir(), referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220772 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: #1 [internal function]: Symfony\\Component\\Finder\\Iterator\\SortableIterator::Symfony\\Component\\Finder\\Iterator\\{closure}(Object(Symfony\\Component\\Finder\\SplFileInfo), Object(Symfony\\Component\\Finder\\SplFileInfo)), referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220774 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: #2 /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Iterator/SortableIterator.php(96): uasort(Array, Object(Closure)), referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220776 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: #3 /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Finder.php(772): Symfony\\Component\\Finder\\Iterator\\SortableIterator->getIterator(), referer: http://downloads.nnxx.ninux.org/firmware/
[Sat Feb 08 16:53:03.220777 2020] [fcgid:warn] [pid 14696] [client 79.42.154.133:55586] mod_fcgid: stderr: #4 /var/www/clients/client3/web18/web/app/vendor/symfony/finder/Finder.php(614): Symfony\\Component\\Finder\\Finder->searchInDirectory in /var/www/clients/client3/web18/web/app/views/index.twig on line 30, referer: http://downloads.nnxx.ninux.org/firmware/

**Comment by PHLAK** [comment]
For security Directory Lister uses [`open_basedir`](https://www.php.net/manual/en/ini.core.php#ini.open-basedir) to prevent directory traversal attacks. Because of this symlinks to files outside of the application root folder will cause this error.
