### ISSUE TITLE
Nginx rewrite

### ISSUE THREAD

**Issue by 1orz** [DirectoryLister/DirectoryLister#258]
I had some porblems when using beta3

How to set rewrite rules in Nginx?

**Comment by PHLAK** [comment]
[Here's the NGINX config](
https://github.com/DirectoryLister/DirectoryLister/blob/983d050476fa6aee87ad79b4a3c55afc62abe9ee/.docker/nginx/config/default.conf) I've been using for development, in particular check out the `location /` block.

```
location / {
    try_files $uri /index.php$is_args$args;
}
```

Hopefully this this helps.
