### ISSUE TITLE
Matomo

### ISSUE THREAD

**Issue by igeofr** [DirectoryLister/DirectoryLister#260]
Add a way to track site analytics via [Matomo](https://matomo.org).

**Comment by PHLAK** [comment]
Thanks @igeofr, I'll look into this.

For what it's worth, the ability to enable [Google Analytics tracking](https://github.com/DirectoryLister/DirectoryLister/wiki/.env-Config-Reference#google_analytics_id) will be coming in the next beta release.

**Comment by PHLAK** [comment]
This has been added with e062214 and will be available in the next release.
