### ISSUE TITLE
Subdirectory cannot be opened normally

### ISSUE THREAD

**Issue by amilys** [DirectoryLister/DirectoryLister#267]
Hello, I found that after my installation, only the home page can be displayed normally, and the following directory cannot be displayed

![QQ截图20200210114321](https://user-images.githubusercontent.com/11211624/74119599-1803d400-4bfb-11ea-9390-22ab826cb49d.png)
![QQ截图20200210114337](https://user-images.githubusercontent.com/11211624/74119605-19350100-4bfb-11ea-9728-c5f47600be5e.png)

**Comment by PHLAK** [comment]
This should be fixed in [beta.5](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.0.0-beta.5) (just released). Please test this and if the problem remains, let us know.

**Comment by amilys** [comment]
Sorry, sometimes it's bad, so the reply is not very timely.
The latest version still reports an error. You can visit my website to check it
[demo](http://ssr0.cn)

**Comment by PHLAK** [comment]
> Fatal error: Uncaught Error: Class 'DOMDocument' not found

The good news is this means your original problem is fixed. The bad news is you have a new problem.

This error occurs when you're missing the PHP [DOM extension](https://www.php.net/en/dom). This is required for rendering README files. You will need to install that extension.

**Ubuntu / Debian**

    sudo apt install php-dom

**Fedora / Redhat**

    sudo yum install php-xml

Alternatively you can disable READMEs by setting `DISPLAY_READMES` to `false` in your `.env` file.

**Comment by amilys** [comment]
Thanks,No problems have been found
