### ISSUE TITLE
Improved rendering of README

### ISSUE THREAD

**Issue by yAgeron** [DirectoryLister/DirectoryLister#270]
Not all markdown formatting is supported.
Would it be possible to support the following styles? 
https://markdown-it.github.io/

Thanks

**Comment by PHLAK** [comment]
What in particular isn't supported?

Directory Lister is using [Parsedown](https://parsedown.org) for fast, [GitHub flavored markdown](https://github.github.com/gfm/) processing. This limits support to the full markdown spec + GitHub specific markdown which I believe is sufficient. However, we may have missed some styling and would be happy to fix it if so.

**Comment by PHLAK** [comment]
After a quick look I just found [Parsedown Extra](https://github.com/erusev/parsedown-extra). This may be a drop-in replacement that will accomplish a lot of the extra features. I will look into this.

**Comment by PHLAK** [comment]
I have implemented the change to Parsedown Extra and this is now available in the [beta.5](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.0.0-beta.5) release. Please try this out and let me know of any specific issues you still have.

**Comment by yAgeron** [comment]
It's clean! Thank you very much for your reactivity and your work.

**Comment by PHLAK** [comment]
You're welcome!
