### ISSUE TITLE
Can you add zip Download

### ISSUE THREAD

**Issue by amilys** [DirectoryLister/DirectoryLister#271]
No zip download option found in the beta version

**Comment by PHLAK** [comment]
Thank you. Yes, this is a planned feature though when exactly it will land I'm not sure of yet.

**Comment by PHLAK** [comment]
Zip downloads is now available in [beta.6](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.0.0-beta.6). Please download and test this feature and report any issues.
