### ISSUE TITLE
DirectoryLister fails when symlinks are present

### ISSUE THREAD

**Issue by danieldietsch** [DirectoryLister/DirectoryLister#276]
**Directory Lister Version**
v3.0.0-beta.8

**PHP Version**
PHP 7.3.14 

**PHP Extensions**
```
[PHP Modules]
bz2
Core
ctype
curl
date
dba
dom
fileinfo
filter
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```
**HTTP Server**
Apache 2.4.41

**Describe the bug**
If I try to list a directory with a symlink to an outside directory, DirectoryListener crashes with an Uncaught RuntimeException. 
```
 PHP Fatal error:  Uncaught RuntimeException: SplFileInfo::isFile(): open_basedir restriction in effect. File(./<dir-symlink>) is not within the allowed path(s): (<webroot>/logs) in <webroot>/logs/app/vendor/symfony/finder/Iterator/SortableIterator.php:53\nStack trace:\n#0 <webroot>/logs/app/vendor/symfony/finder/Iterator/SortableIterator.php(53): SplFileInfo->isFile()\n#1 [internal function]: Symfony\\Component\\Finder\\Iterator\\SortableIterator::Symfony\\Component\\Finder\\Iterator\\{closure}(Object(Symfony\\Component\\Finder\\SplFileInfo), Object(Symfony\\Component\\Finder\\SplFileInfo))\n#2 <webroot>/logs/app/vendor/symfony/finder/Iterator/SortableIterator.php(96): uasort(Array, Object(Closure))\n#3 <webroot>/logs/app/vendor/symfony/finder/Finder.php(772): Symfony\\Component\\Finder\\Iterator\\SortableIterator->getIterator()\n#4 /var/www/st in <webroot>/_dirlist/app/views/index.twig on line 30
```

**Steps To Reproduce**
  1. Create directory with symlink to somewhere outside the webroot. 
  2. Try to load page
  3. See error

**Expected behavior**
It would be nice to show a symlink as not accessible or simply hide it from the directory listing without crashing. I want to use DirectoryListener to show a large log file repository with HTML summaries per log directory. From the HTML view, I can access the symlinked fiels (and need them), but I also like to have the download directory and the search features.

**Comment by PHLAK** [comment]
I've just added a "Common Issues" section to the [Troubleshooting](https://github.com/DirectoryLister/DirectoryLister/wiki/Troubleshooting) documentation page that explains this issue.

> It would be nice to show a symlink as not accessible or simply hide it from the directory listing without crashing.

This is a good idea though. Perhaps we can have inaccessible symlinks show up greyed out with a lock icon or something. Perhaps have an option to just remove any inaccessible link altogether. I'll see what I can do.

**Comment by danieldietsch** [comment]
Thank you for the Troubleshooting page!

For me, it would already be really helpful if the links do not show at all. I do not know how hard it is to add that though.

**Comment by PHLAK** [comment]
Opened #320 to track just the graying out of symlinks.
