### ISSUE TITLE
Server reported error 500

### ISSUE THREAD

**Issue by Sak94664** [DirectoryLister/DirectoryLister#278]
**Directory Lister Version**

The version of directory lister you're using.
3.0 beta8 (from directorylister.com)

**PHP Version**
php7.3.14-1

**PHP Extensions**

What PHP extensions do you have installed?
[PHP Modules]
calendar                                                                         Core
ctype                                                                            date
exif                                                                             fileinfo
filter                                                                           
ftp
gettext                                                                          hash                                                                             iconv                                                                            json                                                                             libxml                                                                           openssl                                                                          pcntl                                                                            pcre                                                                             PDO                                                                              Phar                                                                             posix                                                                            readline
Reflection                                                                       session
shmop                                                                            sockets
sodium                                                                           SPL
standard                                                                         sysvmsg                                                                          sysvsem                                                                          sysvshm
tokenizer                                                                        Zend OPcache                                                                     zip                                                                              
zlib                                                                                                                                                              [Zend Modules]                                                                   Zend OPcache

**HTTP Server**
NGINX 1.14.2

**Describe the bug**
After setting it up,I can only see HTTP Error 500.

**Steps To Reproduce**
Here is my setup steps:
1. Firstly download the .tar.gz archive from directorylister.com
2. untar it.
3. set ownership recursively to www-data,which is the same as nginx and php-fpm
4. reload nginx and php-fpm

**Expected behavior**
It should work fine.

**Additional context**
Here's the error log taken from /var/log/nginx/error.log

`
2020/02/21 19:06:59 [error] 14366#14366: *63 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/dirlist/app/vendor/erusev/parsedown-extra/ParsedownExtra.php:477                    Stack trace:                                                                    
 #0 /var/www/dirlist/app/vendor/erusev/parsedown-extra/ParsedownExtra.php(232): ParsedownExtra->processTag('<p align="cente...')                                   #1 /var/www/dirlist/app/vendor/erusev/parsedown/Parsedown.php(206): ParsedownExtra->blockMarkupComplete(Array)                                                    
#2 /var/www/dirlist/app/vendor/erusev/parsedown/Parsedown.php(39): Parsedown->lines(Array)
#3 /var/www/dirlist/app/vendor/erusev/parsedown-extra/ParsedownExtra.php(46): Parsedown->text('<p align="cente...')  
#4 /var/www/dirlist/app/vendor/erusev/parsedown/Parsedown.php(1580): ParsedownExtra->text('<p align="cente...')
#5 /var/www/dirlist/app/src/ViewFunctions/Markdown.php(21): Parsedown->parse('<p align="cente...')                                                                
#6 /var/www/dirlist/app/cache/views/44/448a9f26a9e40294fedf15482816de7334c463807d0704e2d8e1092ff8cbac65.php(52): App\ViewFunctions\Markdown->__invoke('<p align="cente...')      
 #7 /var/www/dirl" while reading response header from upstream, client: 172.24.1.114, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-dirlist.sock:", host: "172.24.1.227:8048"
`

**Comment by PHLAK** [comment]
See: https://github.com/DirectoryLister/DirectoryLister/wiki/Common-Issues#class-domdocument-not-found
