### ISSUE TITLE
file extension filter exclude

### ISSUE THREAD

**Issue by webmaster-sites** [DirectoryLister/DirectoryLister#279]
in the hidden_file filter is not any extension filter to hide all files with specific extension 

i want to hide all jpg files for example
i tried *.jpg as input but it does not work

please add this feature or help me if it  exists

**Comment by PHLAK** [comment]
Try this

```php
'hidden_files' => [
    *.jpg
    **/*.jpg
]
```

**Comment by webmaster-sites** [comment]
thanks, it worked!
