### ISSUE TITLE
Add inBrowser download for like Mega.nz has

### ISSUE THREAD

**Issue by veso266** [DirectoryLister/DirectoryLister#280]
**Is your feature request related to a problem? Please describe.**

Is it possible to add InBrowser download as an option, something like Mega.co.nz has

![alt text](https://i.ytimg.com/vi/ZvKVS77Qnm0/maxresdefault.jpg)

 when downloading files a separate page is opened that shows download progress on page and then when file is downloaded it triggers browser save as dialog

you could use this script for that: https://github.com/rndme/download

that would be a neat oportunity to count downloads as well and maybe show total downloads for files

**Comment by PHLAK** [comment]
Is it the in-browser downloads you want or a download counter or both? I can the desire for a download counter but what would be the advantage of an in-browser download page?

**Comment by veso266** [comment]
I Think inBrowser download looks cool (I always loved what mega did 😄 
as for the Download Counter I think its a neat thing for people that host files

so yea if you could add Both that would be great, but I think Download Counter is more useful

**Comment by PHLAK** [comment]
A download counter is something that's been requested a lot. However, this would require some type of permanent storage (i.e. a database) to store the download counts. I have some ideas to make this work with minimal setup/configuration from the user but there's no way to eliminate it all together. I will be investigating this further in the future but I can't say when. It might not happen until after the 3.0.0 final release.

The download page seems a lot less likely to happen but I may look into it at some point even further in the future.

**Comment by veso266** [comment]
The download counter I implemented in version 2 days: https://github.com/veso266/DirectoryLister/commit/1f2995f9bb1a3be9ab45173d78d04da8def0e7d4

used a text file stored in resource folder (log) where it stored the filename and number of downloads of that file and to determine total downloads just added all the numbers together

no database required, no extra setup required file is auto created, user doesn't know it exists :smile: 

I would create a pull request but the project got so much :cry: big (sometimes for small apps like directory Lister its just easier to stuff it into one file and call it quit :smile: but hey you know why you did that although you are the one that understand where stuff is now :smile: ) that I don't even know anymore how to adapt my nice theme: https://github.com/veso266/DirectoryLister/tree/master/resources/themes/dxingslo

for it anymore :cry:  

but thats maybe just me that gets confused over projects with a lot of files with small lines of code (I like something in the middle not too much code in one file, but not much files with 3 lines of code (I saw that one too (not here but it happens :smile: ) and it makes me go crazy because I have to dig through files so much

Just wondering what framework did you use to write this with, its not Laravel, its not Phalcon, what could it be, Symfony?

Can I suggest a reorganization? Do you think you could move Docker and composer and unit tests and npm stuff into a seperate folder so users and geeks know immediately where is the juice that you upload to a server or add a feature or change something and have a nice directory listing 

that would be great something like before where you had 1 file and one folder and you immediately know that this 2 is the onlything you need

because now you have 24 files, and 5 folders and you don't even need all of them for normal operation

yea thats my 2 cents, hope you could maybe add a download counter now you know you don't need a database (it could be optional if people want it) because I think one more file that gets auto created should not be a problem for end user :smile:

**Comment by PHLAK** [comment]
> Can I suggest a reorganization? Do you think you could move Docker and composer and unit tests and npm stuff into a seperate folder...
> 
> that would be great something like before where you had 1 file and one folder and you immediately know that this 2 is the onlything you need
> 
> because now you have 24 files, and 5 folders and you don't even need all of them for normal operation

Most of these files are not included in the release [tar.gz](https://github.com/DirectoryLister/DirectoryLister/releases/download/3.0.0-beta.8/DirectoryLister-3.0.0-beta.8.tar.gz) and [zip](https://github.com/DirectoryLister/DirectoryLister/releases/download/3.0.0-beta.8/DirectoryLister-3.0.0-beta.8.zip) files which contain only 5 files and one folder in the root directory. These are the files you get if you download directly from <https://www.directorylister.com> as well. However, every file has a use and most of them are short to keep their purpose focused on that one use. This helps development for various reasons I wont go into here.
