### ISSUE TITLE
why no composer package?

### ISSUE THREAD

**Issue by rvwoens** [DirectoryLister/DirectoryLister#286]
downloading zip files? Isn't that a bit too 2005? 
Is there a reason that it is not available as a composer package?

**Comment by PHLAK** [comment]
> downloading zip files? Isn't that a bit too 2005?

The large portion of the target audience for Directory Lister is less-than-technical and zip downloads is their preferred method of installation.

> Is there a reason that it is not available as a composer package?

Directory Lister is a fully-fledged application and wouldn't work as a composer package.

That being said I'm considering a one-liner install you can run on your server that will pull the archive and extract it to the current directory. Maybe this could do some sanity checking to insure all necessary dependencies (e.g. PHP version, PHP extensions, etc.) are met. Something like this

    curl -sSL https://install.directorylister.com | bash
