### ISSUE TITLE
problems with backslash in ?dir=\

### ISSUE THREAD

**Issue by marioene** [DirectoryLister/DirectoryLister#288]
**Directory Lister Version**
v3.0.0-beta.9

**PHP Version**
PHP 7.2.2

**PHP Extensions**
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
gd
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

**HTTP Server**
Apache v2.4.35 (Laragon 4.0.10 = Apache, PHP, MySQL)

**OS Version**
Windows 2012 Server Standard

**Describe the bug**
Only in the root of the folder is this behaviour, not in subfolders.

Put me a backslash ("\\") after ?dir= in root like this:

?dir=\\name-of-folder

The project DirectoryLister is installed in a subfolder on the www.local-domain.com (local domain on my intranet, not public), not in the root (C:\laragon\www).

So, when click on a folder I receive the error "Directory does not exist"

**Comment by PHLAK** [comment]
Can you enable [debug](https://github.com/DirectoryLister/DirectoryLister/wiki/Config-Reference#debug) and copy/paste the error message you see?

**Comment by marioene** [comment]
Not returning a real error. Just appear a sign backslash  to the url ?dir=\folder-name-from-the-root and after clicking on it give me normal interface with message  Directory not ...

**Comment by PHLAK** [comment]
I think I've identified the problem.

**Comment by PHLAK** [comment]
I believe I've fixed this, can you please download and test this build: [DirectoryLister-8fa15cf.zip](https://github.com/DirectoryLister/DirectoryLister/files/4257433/DirectoryLister-8fa15cf.zip)

**Comment by PHLAK** [comment]
Another test build with some additional Windows-specific fixes: 
[DirectoryLister-ad37a46.zip](https://github.com/DirectoryLister/DirectoryLister/files/4257539/DirectoryLister-ad37a46.zip)

**Comment by marioene** [comment]
@PHLAK It is working! Thanks! Great work!
