### ISSUE TITLE
Download + Counter.

### ISSUE THREAD

**Issue by Hime-Dev** [DirectoryLister/DirectoryLister#304]
mp4 - mp3 - .ass - .srt ... etc. this and same file type dosen't direct download. I want to see 1 click direct download and you can add  Download Counter.

can you look this repo:
https://github.com/nixmomo/DirectoryLister

all file directly download. But now offical DirectoryLister mp4 or .ass ... file type directly open dosen't download.

**Comment by PHLAK** [comment]
> mp4 - mp3 - .ass - .srt ... etc. this and same file type dosen't direct download.

You can configure your web server to force specific (or all) file types to download.

If you're using Apache you can use the [ForceType directive](https://httpd.apache.org/docs/2.4/mod/core.html#forcetype). Example:

```
AddType application/octet-stream .ass
AddType application/octet-stream .mp3
AddType application/octet-stream .mp4
AddType application/octet-stream .srt
```

Some more information on doing this in Apache and NGINX here: https://210mike.com/force-file-download-nginx-apache/

**Comment by PHLAK** [comment]
As for a download counter, this is something we've considered but haven't found a good way of accomplishing this without adding additional configuration requirements.

**Comment by Hime-Dev** [comment]
> As for a download counter, this is something we've considered but haven't found a good way of accomplishing this without adding additional configuration requirements, but we're thinking about it.

okey i understand but i send link repo this repo have a 1 folder and keep all download. 1 txt file. than show front-end.

**Comment by Hime-Dev** [comment]
and you can maybe add switch dark-light better than now .env only 1 theme 
to decide but switch is better allways.
