### ISSUE TITLE
Live Dark-Light Theme

### ISSUE THREAD

**Issue by Hime-Dev** [DirectoryLister/DirectoryLister#309]
hi i know .env chose dark or light theme but i want example sun and moon icon i click sun icon theme light click moon theme dark how to make this function?

**Comment by PHLAK** [comment]
This is not currently possible but will be taken into consideration. Thank you for the suggestion.

**Comment by adamwarrenRIT** [comment]
It would also make sense to respect the user's operating system/browser-level dark mode toggle by default. Light or dark preference is exposed by a [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) in all modern browsers now.

**Comment by UltraHR** [comment]
It would also make sense to respect the user's operating system/browser-level dark mode toggle by default. Light or dark preference is exposed by a [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) in all modern browsers now.

**Comment by PHLAK** [comment]
https://tailwindcss.com/docs/dark-mode

**Comment by PHLAK** [comment]
Resolved with [v3.7.0](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.7.0)
