### ISSUE TITLE
How to make only subfolder list.

### ISSUE THREAD

**Issue by Hime-Dev** [DirectoryLister/DirectoryLister#310]
hello my question: how to make only subfolder list. 

example my directory: newfolder->subfolder i want only show subfolder (i don't want resource move. Beacuse i have a many file.) 

i want people try newfolder auto block website or show error page.
Example:
directorylister.com/?dir= (people try this link show error page) but people try this link -> directorylister.com/?dir=newfolder or subfolder show 

so i m how to block parent directory but sub directory not blocked can you help me?

Example This Link work: https://srv09.erai-ddl3.info/2017/Spring/Boruto%20-%20Naruto%20Next%20Generations/index.php 

but 

This link dosen't work: https://srv09.erai-ddl3.info/2017/

i want this.

**Comment by PHLAK** [comment]
Install Directory Lister in `subfolder`.

**Comment by Hime-Dev** [comment]
good advice : " (i don't want resource move. Beacuse i have a many file.)"
