### ISSUE TITLE
Add a config to search the current directory

### ISSUE THREAD

**Issue by SSgumS** [DirectoryLister/DirectoryLister#312]
The search field searchs all directories. For my website, it takes very very long time to give me results. I have more than 10 TB files in my site.
It will be so good if you add a config to just search the current directory not all directories from root! or at least search just current directory and it's own sub directories.

**Comment by PHLAK** [comment]
Interesting idea, thanks for the suggestion.

**Comment by SSgumS** [comment]
Thank you for your great app
