### ISSUE TITLE
Unable to get DirectoryLister running on a simple php based webserver (free space) ?

### ISSUE THREAD

**Issue by roboirc** [DirectoryLister/DirectoryLister#314]
Hi
I am trying to run your DirectoryLister on uwebweb.com but unable to do so. 
What are the minimum specs for getting your script running on a web server? i.e. What has to be installed?
Thanks

**Comment by roboirc** [comment]
Your script is mentioned on this website too: 
https://www.evoluted.net/thinktank/web-development/php-directory-listing-script

It mentions requiring GD2 library to be installed also which your documentation doesn't mention. Please clarify.

**Comment by PHLAK** [comment]
First off, the link you provided is **NOT** this application. See https://www.directorylister.com for more information about _this_ application.

If you are in fact using this application, which version are you attempting to install? You can find [Installation requirements and instructions](https://github.com/DirectoryLister/DirectoryLister/wiki/Installation) can be found in the documentation wiki.

**Comment by leeuwtjex** [comment]
Assuming you run a debian like server: 
use 2 command at the fileserver root folder :
(just go to the webserver directory where the files are stored you wish to share on the net)

wget https://github.com/DirectoryLister/DirectoryLister/releases/download/3.0.0-rc.1/DirectoryLister-3.0.0-rc.1.tar.gz

tar -xvf  DirectoryLister-3.0.0-rc.1.tar.gz

**Comment by roboirc** [comment]
Thanks for the reply. So only Php is required for Directory Lister to work?

**Comment by PHLAK** [comment]
PHP with the required extensions, yes.

**Comment by leeuwtjex** [comment]
Roboirc,

Below advice is based on a debian like linux o.s. webserver. It could be of use for you with possible modifications.
In my findings yesterday,  you can just follow the manual below to install php 4.7.
It will result in a complete php 7.4 installation at your server with all the extensions you need for the directorylister php script.

https://computingforgeeks.com/how-to-install-latest-php-on-debian/ 

If there would be an error with wget gpg key like I had, first download the key any way possible and than register the key with a command like: sudo apt-key add
My system was Debian 9

Have fun!

**Comment by roboirc** [comment]
Thanks
