### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by leeuwtjex** [DirectoryLister/DirectoryLister#315]
-newest version!

php 7.4:

libapache2-mod-php7.4/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed,automatic]
php/unknown,now 2:7.4+73+0~20200221.21+debian9~1.gbp29416a all [installed]
php-cgi/unknown,now 2:7.4+73+0~20200221.21+debian9~1.gbp29416a all [installed]
php-common/unknown,now 2:73+0~20200221.21+debian9~1.gbp29416a all [installed]
php-pear/unknown,now 1:1.10.9+submodules+notgz-1+0~20191119.13+debian9~1.gbp296d25 all [installed]
php-sqlite3/unknown,now 2:7.4+73+0~20200221.21+debian9~1.gbp29416a all [installed]
php7.0/unknown,now 7.0.33-26+0~20200320.33+debian9~1.gbp746b8e all [installed]
php7.0-cgi/unknown,now 7.0.33-26+0~20200320.33+debian9~1.gbp746b8e amd64 [installed,automatic]
php7.0-cli/unknown,now 7.0.33-26+0~20200320.33+debian9~1.gbp746b8e amd64 [installed,automatic]
php7.0-common/unknown,now 7.0.33-26+0~20200320.33+debian9~1.gbp746b8e amd64 [installed,automatic]
php7.0-gd/unknown,now 7.0.33-26+0~20200320.33+debian9~1.gbp746b8e amd64 [installed]
php7.0-json/unknown,now 7.0.33-26+0~20200320.33+debian9~1.gbp746b8e amd64 [installed,automatic]
php7.0-opcache/unknown,now 7.0.33-26+0~20200320.33+debian9~1.gbp746b8e amd64 [installed,automatic]
php7.0-readline/unknown,now 7.0.33-26+0~20200320.33+debian9~1.gbp746b8e amd64 [installed,automatic]
php7.4/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 all [installed,automatic]
php7.4-bcmath/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-cgi/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed,automatic]
php7.4-cli/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-common/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed,automatic]
php7.4-curl/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-fpm/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-gd/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-intl/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-json/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-mbstring/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-mysql/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-opcache/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-readline/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed,automatic]
php7.4-sqlite3/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-xml/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]
php7.4-zip/unknown,now 7.4.4-1+0~20200320.15+debian9~1.gbpf8dc20 amd64 [installed]

bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

Examples: Apache, NGINX, Lighttpd, etc.

LIGHTTTPD:   lighttpd/oldstable,now 1.4.45-1 amd64 [installed]

BUG REPORT:  Where are these '/app/vendor/autoload.php' ??? How to get?
The requirements do not say anything about it. I cloned the newest github file collection today?

In the browser just: 'This page isn't working'......

running by terminal:
php index.php
PHP Warning:  require(/var/www/html/admin/publiek_files/fileserver/app/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/admin/publiek_files/fileserver/index.php on line 8
PHP Fatal error:  require(): Failed opening required '/var/www/html/admin/publiek_files/fileserver/app/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/admin/publiek_files/fileserver/index.php on line 8

----------------------------------------------------------------------
The beginning of your index.php:

<?php

use App\Bootstrap\AppManager;
use App\Controllers;
use DI\Container;
use Dotenv\Dotenv;

require __DIR__ . '/app/vendor/autoload.php';
------------------------------------------

Took me much more than 1 minute to analyse! (I updated to php 7.4 firstly...

Can you help?

.

**Comment by PHLAK** [comment]
Cloning the repo directly wont work without installing all the dependencies. I recommend you download the latest `zip` or `tar.gz` files from https://www.directorylister.com directly. These are the release artifacts that contain all the pre-compiled files necessary.

**Comment by leeuwtjex** [comment]
Thank you, installing from here:

https://github.com/DirectoryLister/DirectoryLister/releases/download/3.0.0-rc.1/DirectoryLister-3.0.0-rc.1.tar.gz


Solved all problems!
