### ISSUE TITLE
How can I remove GLOB_BRACE code?

### ISSUE THREAD

**Issue by HamedSepehr** [DirectoryLister/DirectoryLister#333]
I have the same problem as #289 but on different file, here is a screenshot of what I get (directory lister v3.0.0-rc.4)

[![directorylister-error.jpg](https://i.postimg.cc/QMB41L0J/directorylister-error.jpg)](https://postimg.cc/3yTFQqMk)

I'm using [linuxserver/letsencrypt](https://hub.docker.com/r/linuxserver/letsencrypt) as my webserver which is based on alpine and I'm aware this error is caused by alpine. Because I'm using directory lister only on my personal vps and no one else has access to it I don't mind changing it a little as long as it can list all of my files/directories. My question is, is there any way to remove parts of code where it needs GLOBE_BRACE and have direcory lister still working? I'm not a php programer please guide me with details.

**Comment by PHLAK** [comment]
You can remove `GLOB_BRACE` from the [`hiddenFiles()` method in `app/src/Factories/FinderFactory.php`](https://github.com/DirectoryLister/DirectoryLister/blob/master/app/src/Factories/FinderFactory.php#L92). Keep in mind this will likely break the hidden file functionality.

**Comment by PHLAK** [comment]
FYI, I've refactored the hidden file code to improve functionality and eliminate the reliance on `GLOB_BRACE`. This change will be included in the next release.

**Comment by HamedSepehr** [comment]
Thanks for letting me know, waiting for next release.
