### ISSUE TITLE
Click on a php file will run it

### ISSUE THREAD

**Issue by adrian3d** [DirectoryLister/DirectoryLister#334]
**Directory Lister Version**
`v3.0.0-beta.1`

I simply used the demo to reproduce this bug.

**Describe the bug**

When I click on a php file, the server interprets it. Example with that file: https://demo.directorylister.com/tests/Controllers/FileInfoControllerTest.php

This could be a security issue in some case.

**Expected behavior**

The php file should be downloaded.

**Comment by PHLAK** [comment]
Directory Lister isn't intended to server files, it only lists them and leaves serving them up to the web server. In this case PHP files are interpreted by the PHP engine. For the demo we're just hosing the raw application files and thus it contains PHP files. I wouldn't recommend this in general. Perhaps we could make a better demo to avoid confusion.
