### ISSUE TITLE
update content

### ISSUE THREAD

**Issue by marioene** [DirectoryLister/DirectoryLister#336]
Hi. First, great package!

I have a small problem:

If I create a new folder on the physical server (Windows 2012 Server) in the root or in another subfolder and populated with files, I can see the folder and files (in browser) only if I remove the cookies for the site and refresh again!

How can I configure your project to update at every access the list of folders or files?

**Comment by marioene** [comment]
This behaviour is only on Firefox. I will use Google Chrome instead.

**Comment by marioene** [comment]
The same problem reappears. Not updated content even in Chrome.

**Comment by PHLAK** [comment]
This sounds like browser caching, what browser are you using? Sometimes when I don't see changes on the page immediately I'll "force reload" the page using `Ctrl`+ `Shift` + `R` (in Firefox).

Various ways of force reloading from other browsers can be found [here](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/).

**Comment by marioene** [comment]
@PHLAK 

I hoped to find with Laravel code this kind of udapte. Thanks, anyway!
