### ISSUE TITLE
Issues with directories and certain characters.

### ISSUE THREAD

**Issue by CatBox360** [DirectoryLister/DirectoryLister#338]
Using 3.0.0 on NGINX with PHP 7.3.15. Any directory with #, &, and + characters returns a blank page with directory does not exist. Any files will return a 404.

Using the search function (awesome by the way!) for those characters returns results. The URL shows the encode? number for the character, ie %23 for #, but none of the results work.

I also tried this on a Windows machine and got the same results.

Thanks

**Comment by PHLAK** [comment]
Thank you, I will look into this.

**Comment by PHLAK** [comment]
I believe I've fixed this. Please download the following and test it out.

[DirectoryLister-aef71d0.zip](https://github.com/DirectoryLister/DirectoryLister/files/4440015/DirectoryLister-aef71d0.zip)

**Comment by CatBox360** [comment]
That appears to have fixed directory browsing. I can't make it break.

Files are broken. Examples;
/TestDir/TEST.txt gives /?dir=TestDir/TEST.txt 
Removing the ?dir= allows it to work.

/TestDir/Second Test/Test.txt gives /?dir=TestDir/Second+Test/TEST.txt
Removing the ?dir= and + allows it to work. Chrome auto changed the space to %20

/TestDir/Stuff & Things/Track #1 - Guilty pleasure song.txt gives /?dir=TestDir/Stuff+%26+Things/Track+%231+-+Guilty+pleasure+song.txt
Removing the ?dir= results in a 404 error.

**Comment by PHLAK** [comment]
Thanks, I noticed that and already fixed that in another updated. I'm going to try to release these fixes in the next few days.

**Comment by CatBox360** [comment]
Don't want to be a pain or know if I should open another issue, but I've tried a bunch of other special characters with the update you provided and 3.0.1

Not sure if this is some oddity with my setup or not, but everything works except filenames with spaces. This only impacts what the actual URL would be to the file. 

http://coffee.is.awesome/Test Dir/Test.txt = 404
http://coffee.is.awesome/DirWithA+/Test.txt = works

Thanks again

**Comment by PHLAK** [comment]
Not a pain at all. Feel free to open another issue. I'm looking into this.
