### ISSUE TITLE
Files links with target _blank

### ISSUE THREAD

**Issue by pjrfigueiredo** [DirectoryLister/DirectoryLister#34]
Links to 'everything' except directories should have target blank :)

**Comment by meisemma** [comment]
Hello

I think the code is really really cool...thanks. Sorry for opening up this one again...but I'm stuck.  I'd like to use the target _blank feature as I want to use it in an iframe, and when I click say on a PDF it opens it within the iframe.  I hope that's ok. I've read the readme and have made sure that the link to Directory lister is still showing.

Many thanks for your hard work

Emma
