### ISSUE TITLE
hidden files

### ISSUE THREAD

**Issue by LaMpiR** [DirectoryLister/DirectoryLister#343]
Hi.

I have downloaded the latest 3.0 version. It looks amazing.
So I have create a file .hidden and inside I have

*.txt
*.png

png is not shown, txt file is?

I have tried *.txt, *.png and so on.

I have few more questions.
1) Google Analytics ID, but it's not GDPR ready? I cannot use the google in Europe, unless I have GDPR consent.
2) Any way to disable search console?
3) Any way to count downloads?

Thank you very much.

Best regards
2)

**Comment by LaMpiR** [comment]
Updated to version 3.0.2.

Tried .hidden file:

robots.txt, *.png - not working

robots.txt,
*.png - not working

**Comment by PHLAK** [comment]
I am able to hide all `txt` and `png` files in the root folder and all sub-folders with the following `.hidden` file:


    *.txt
    **/*.txt
    *.png
    **/*.png

After adding these entries you may need to perform a "[hard refresh](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/)" of the page to clear the browser cache. I do this in Firefox with `Ctrl` + `Shift` + `R`.

As for your other questions:

  - Google Analytics is not enabled by default so there should not be any issues with GDPR as long as you keep it disabled
  - There is no way to disable search at the moment. I will consider adding an option for this in the future
  - It is not possible to count downloads
