### ISSUE TITLE
Hidden Files, Font Size and App Color Mode

### ISSUE THREAD

**Issue by haizen007** [DirectoryLister/DirectoryLister#354]
Hey, first thanks for the app, very useful.

1. I'd like to know the best way to "hide" files like "directory-lister.svg" to be favicon and so on since they are not hidden by default, at least not here...
2. How to edit the font size, it's so big on my screen, I would be great to change to a smaller size like 2.x version for example.
3. Also if it's possible to let the user chose from default to dark mode and vise-versa, like a switch button?

**Comment by PHLAK** [comment]
1.  The easiest way to hide files is to create a file named `.hidden` in the root project directory (same place as `index.php`) and add a list of files to be hidden there.

      Example:

          directory-lister.svg
          LICENSE
          README
          ...
 
      Additional documentation for this can be found here: https://github.com/DirectoryLister/DirectoryLister/wiki/Config-Reference#hidden_files

  2. There's no configuration option to edit the font size. The recommended way to change this would be to use your browsers built in [zoom controls](https://www.wikihow.com/Zoom-With-a-Web-Browser) to zoom out (`Ctrl` + `-` by default). This way the font size only changes for you and will remain the defaults for other users. If you must change it for everyone then you'll have to edit the view files (in `app/views`) directly.

  3. User theme choice has been requested before (#309) and has been taken into consideration, however, I cannot promise if (or when) this will ever be implemented.
