### ISSUE TITLE
Runtime Error on Solaris Server (GLOB_BRACE)

### ISSUE THREAD

**Issue by rexut** [DirectoryLister/DirectoryLister#355]
https://github.com/DirectoryLister/DirectoryLister/blob/b553b58de21f58cb0e9ff20a535f62659d4cbe4f/app/src/Factories/FinderFactory.php#L92

GLOB_BRACE is not available on Solaris, see also the note for glob (): https://www.php.net/manual/en/function.glob.php#refsect1-function.glob-notes

Similar to the GLOB_BRACE handling in the symfony source code (https://github.com/symfony/symfony/blob/4c1ca329a440fbf98ac90208a79292606d4cd92c/src/Symfony/Component/Finder/Finder.php#L585) the following change was needed to get the DirectoryLister running in a Solaris based PHP 7.3 environment:

```
--- app/src/Factories/FinderFactory.php.orig	2020-04-13 22:53:43.000000000 +0200
+++ app/src/Factories/FinderFactory.php	2020-04-19 23:32:56.295995121 +0200
@@ -89,7 +89,7 @@ class FinderFactory
         })->map(function (string $file): array {
             return glob(
                 $this->container->get('base_path') . '/' . $file,
-                GLOB_BRACE | GLOB_NOSORT
+                (\defined('GLOB_BRACE') ? GLOB_BRACE : 0) | GLOB_NOSORT
             );
         })->flatten()->map(static function (string $file): string {
             return realpath($file);
```

This could be related to issue #289

**Comment by PHLAK** [comment]
Unfortunately `GLOB_BRACE` is required for the hidden file patterns to work for now. I'm looking into alternatives but until then any OS without `GLOB_BRACE` support will not work.

**Comment by PHLAK** [comment]
I spent today refactoring the hidden file code to improve functionality and eliminate the reliance on `GLOB_BRACE`. Not sure when I'll make a release but it'll be in the next one.
