### ISSUE TITLE
personalize font type and size of file list

### ISSUE THREAD

**Issue by alexlovar** [DirectoryLister/DirectoryLister#358]
Hello, this is a great work and help me a lot,  i'll like to use a minimal version of this lister, to include in my personal project(into div or iframe). i search in the css to change the default font size and style of the file list for other small, but i didn't found, culd you help me to locate this?
thanks a lot

**Comment by PHLAK** [comment]
Directory Lister used the [Tailwind CSS Framework](https://tailwindcss.com/) which uses [predefined classes](https://tailwindcss.com/docs/font-size/#app) to set the font size. Unfortunately when generating the Directory Lister release archives unused classes are stripped from the compiled CSS files (to reduce distribution size and improve application performance). Therefor, many of the font size classes will not be available unless you re-compile from source.

The file list styles are applied the same way (predefined classes) in the `app/views/components/file.twig` file.

**Comment by MedGaSToN** [comment]
Hello, @PHLAK thank for  your great work .
@alexlovar you just need to make your modification in SC and then just re-compile it. ASAT :D

**Comment by alexlovar** [comment]
thank you so much!!

**Comment by ormaur** [comment]
@PHLAK thank you very much!
@alexlovar I have the same problem. I need a small font size and line spacing. I'm not an expert and I don't know how change and re-compile. Can you help or send me the file? Thanks.

**Comment by PHLAK** [comment]
@ormaur Unfortunately this is not an easy change without modifying the source and recompiling.

**Comment by ormaur** [comment]
> @ormaur Unfortunately this is not an easy change without modifying the source and recompiling.

Ok, thanks anyway. ;)
