### ISSUE TITLE
Configuration Option: Default open links in new tab

### ISSUE THREAD

**Issue by alexlovar** [DirectoryLister/DirectoryLister#361]
**Is your feature request related to a problem? Please describe.**
Not
A description of what the problem is. Ex. I'm always frustrated when...
if i want to keep the file list in place, i need to use right click to open the file  in new window,  or keep going history back if i forget the 'open in new window' to open the files

**Describe the solution you'd like**
add a default configuration in app/configure/app.php to setting the default behavior of open links  in  a new window

A description of what you want to happen.
when i click in a link of the file list, i like to see the file in a new window

**Describe alternatives you've considered**

A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by PHLAK** [comment]
Thanks for the suggestion but this is not something we will likely add. Opening a new tab for every link would rapidly clutter the user's browser tabs, especially when navigating to a file or folder several levels deep. This would also prevent the browser's back button from being useful.

> **NOTE:** You can always use one of the following shortcuts to open a link in a new tab.
>
>  - <kbd>Middle Mouse</kbd>
>  - <kbd>Ctrl</kbd> + <kbd>Click</kbd>
>  - <kbd>⌘</kbd> + <kbd>Click</kbd> (on Mac)
