### ISSUE TITLE
nexpected error occurred

### ISSUE THREAD

**Issue by SkipperWP** [DirectoryLister/DirectoryLister#364]
it doesnt show any file in the directory and it says"An unexpected error occurred Enable debugging for additional information" but if i search for the file it shows up.
Any fix?

**Comment by PHLAK** [comment]
Take a look at our [Troubleshooting guide](https://github.com/DirectoryLister/DirectoryLister/wiki/Troubleshooting). Be sure to enable debugging message and share any relevant error messages.

**Comment by SkipperWP** [comment]
Thanks, there was a problem with the PHP module now it works.
