### ISSUE TITLE
Option to change the installation folder

### ISSUE THREAD

**Issue by Mayccoll** [DirectoryLister/DirectoryLister#365]
Option to change the installation folder even in a hidden folder (.app) 
Thanks for this app, works great

**Comment by PHLAK** [comment]
If you're asking to install Directory Lister to a folder separate from the one it's listing that's not currently possible. For a little insight into why see [this response](https://github.com/DirectoryLister/DirectoryLister/issues/266#issuecomment-610699596) from another issue.

If I've misunderstood the request please let me know.

**Comment by Mayccoll** [comment]
yea. sorry .. i mean something like this:
```bash
# ACTUTAL (this is how its work right now)
├── app
├── .env
└── index.php

# DESIRE
├── .app
├── .env
└── index.php

# Ex:
├── CUSTOM_FOLDER
├── .env
└── index.php
```

**Comment by PHLAK** [comment]
Unfortunately this isn't an easy change. In order for this to work you would have to grab the source code, modify the app path in a few places and build the application manually.

**Comment by PHLAK** [comment]
Is there a particular reason you want to change the `app` folder path?

**Comment by Mayccoll** [comment]
Yea 2 reasons, This type of programs I prefer to have them in hidden folders since they are not applications in which one works.
The other reason is that in the `www` folder it is very common to have a folder called `app`.
Thanks for the time :)

**Comment by olfek** [comment]
I have submitted my PR #541
