### ISSUE TITLE
Display README at the top and language selection.

### ISSUE THREAD

**Issue by groschialeux** [DirectoryLister/DirectoryLister#370]
I just upgraded from 2.7 to the latest version.  I really like it, it looks very very nice and I like the ability to display the README files but I would like it to be at the top of my page, before the directly lists, is there a way to do this ?  I don't see an option for that in the .env file.

I am also wondering if there is an easy way to put a language selector somewhere on the page.

Thank you !

**Comment by PHLAK** [comment]
Glad you like Directory Lister 3! Unfortunately neither of your requests are possible at the moment but both are good ideas worth considering.

**Comment by groschialeux** [comment]
Thanks Phlak.  These are no deal breakers but would be nice to have.

Here's my page.
https://expedimaps.com/

The reason I would put the readme at the top is that I have a no liability clause in mine and I know most people won't bother scrolling down to read before downloading but if they see the text in red at the top maybe they'll read it :)

Thanks for your work.  I'm an ERP developer, I don't know much about web development but I will try and see if I can contribute.

**Comment by PHLAK** [comment]
Resolved with 78108ec. This will be available in the next release.

**Comment by groschialeux** [comment]
This is great.  I did not expect it so quick.  Thanks, it looks really  nice.
