### ISSUE TITLE
Hide Applications Files

### ISSUE THREAD

**Issue by devinharrison8** [DirectoryLister/DirectoryLister#386]
Hide Applications Files Command in .env file DOESN'T WORK! (Of course in 3.1.0 release but in 3.0.5 worked)

**Comment by PHLAK** [comment]
I don't see this behavior. It's working fine both locally and on the [demo](https://demo.directorylister.com) (running v3.1.0). Please provide some additional information.

  - What version of PHP do you have installed?
  - What PHP extensions do you have installed? Run `php -m` from a command line.
  - What HTTP server are you using to serve Directory Lister?
  - Can you provide some steps to reproduce the problem?

**Comment by devinharrison8** [comment]
I reported the problem, you can ignore it.  I don't care.

Using XAMPP

**Comment by PHLAK** [comment]
> Using XAMPP

So this is on a Windows machine?

**Comment by devinharrison8** [comment]
Yes, I tested on both of Windows Server 2016 and Windows 10.

**Comment by PHLAK** [comment]
I believe I've identified the problem and am working on a fix.

**Comment by PHLAK** [comment]
I believe I've resolved this issue. Can you please try installing the following and let me know if you still have issues?

[DirectoryLister-81f9343.zip](https://github.com/DirectoryLister/DirectoryLister/files/4596838/DirectoryLister-81f9343.zip)

**Comment by devinharrison8** [comment]
Solved. (Successful in Win Server 2016 and Win 10)
