### ISSUE TITLE
Page title / description

### ISSUE THREAD

**Issue by LaMpiR** [DirectoryLister/DirectoryLister#394]
Hi,

would be nice to able to add the webpage Title and Description at least for SEO purposes.

Best regards

**Comment by PHLAK** [comment]
Thanks for the suggestion. This will be taken into consideration.

Just to clarify, do you mean the `<title>` tag? Also, what level of customization would you like?

**Comment by LaMpiR** [comment]
Yes, exactly. Simple as that :) Since I am sure that people are running only the script, like I am. Don't have a website and then pointing to a repository or something like this.

Thank you very much. 

Best regards

**Comment by LaMpiR** [comment]
Thank you for implementing the description option. Is tittle to be expected as well?

Would be nice to update the readme on .env files for the meta description.

**Comment by PHLAK** [comment]
@LaMpiR The description is configurable via the [`META_DESCRIPTION`](https://github.com/DirectoryLister/DirectoryLister/wiki/App-Config-Reference#meta_description) configuration option.
