### ISSUE TITLE
Evoluted Theme & Toggle Details

### ISSUE THREAD

**Issue by ArmynC** [DirectoryLister/DirectoryLister#395]
**Hello**! Could you add in the near future a theme like the [Evoluted Directory](https://www.evoluted.net/thinktank/web-development/php-directory-listing-script) one? I intend to use it not just for file uploads but for easy to use submenus with some redirects to other links and that theme isn't very appropiate for anything than upload/download, in my honest opinion.

![Capture](https://user-images.githubusercontent.com/16375271/82752033-19c96000-9dc4-11ea-9567-b9d9e19d3c85.PNG)

Also, could you (if not already) add a toggle to disable the _Size and Date_ of folders & files? And select specific cases too, like which subdirectories/files could should show that details...

**Thank you**!

**Comment by PHLAK** [comment]
With Directory Lister 3 we have chosen to include one theme only to minimize development efforts and focus on making that theme as great as it can be.

As for the ability to toggle columns, this will be taken into consideration but I can't make any promises.
