### ISSUE TITLE
Replace Home with the current folder name OR with a custom text

### ISSUE THREAD

**Issue by SubZero5** [DirectoryLister/DirectoryLister#401]
**Is your feature request related to a problem? Please describe.**

On the top of the page, it says Home and as I enter a folder, it becomes Home / Folder 1 etc.

**Describe the solution you'd like**

I would like to replace Home with the current subdirectory that I am in with the DirectoryLister or a custom setting

ie:

**http://www.blah.com/DLFolder** should look like **DLFolder** on the top bar, so that the sub directories look like: DLFolder / subFolder1 etc.

**Describe alternatives you've considered**

Or maby I would like to call and/or name **http://www.blah.com/DLFolder** as **Directory Lister Folder** instead of **Home** so that the sub directories look like: **Directory Lister Folder / subFolder1** etc.

**Note**

**Directory Lister** is installed at **http://www.blah.com/DLFolder**

**Comment by PHLAK** [comment]
To confirm, you would like to be able to customize this

![Screenshot_2020-06-02 tests Controllers • Directory Lister](https://user-images.githubusercontent.com/53531/83552494-ba073f00-a4be-11ea-9407-2359015c12e6.png)

so it becomes something like this?

![Screenshot_2020-06-02 tests Controllers • Directory Lister(1)](https://user-images.githubusercontent.com/53531/83552506-be335c80-a4be-11ea-8e2e-db549c679fa4.png)

**Comment by SubZero5** [comment]
Yes, that is what I want.
Home is the / directory of the hosting.
Your "Home" is the DirectoryLister install folder...

**Comment by PHLAK** [comment]
Thanks, I'll see what I can do.

**Comment by PHLAK** [comment]
Implemented with 23ae169e528dfe320a1bc66eb8d70c23a643e6d9

**Comment by SubZero5** [comment]
How to configure this?
How to modify the `.env` file?

**Comment by PHLAK** [comment]
Check out the [Configuration documentation](https://github.com/DirectoryLister/DirectoryLister/wiki/Configuration) for more info.
