### ISSUE TITLE
some type of IP allow/deny

### ISSUE THREAD

**Issue by SubZero5** [DirectoryLister/DirectoryLister#402]
**Is your feature request related to a problem? Please describe.**

I want to allow/deny the DirectoryLister to show/hide the index by certain IPv4s or partial IPv4s like:

aaa.bbb.ccc.ddd like 1.1.1.1 which would allow/deny 1.1.1.1
aa.bb.cc. like 8.8.4. which would allow/deny 8.8.4.*
a.b. like 192.168. which would allow/deny 192.168.*.*
a. like 10. which would allow/deny 10.*.*.*

**Describe alternatives you've considered**

Alternatively, if the IPv4 matches, the DirectoryLister would show its normal Index but if it won't, either maby a username/password prompt might do some good or show some HTTP 403 Forbidden error to reject the user.

**Comment by PHLAK** [comment]
This is out of scope for Directory Lister and would be better suited to implement at the web server or firewall level.
