### ISSUE TITLE
Version upgrade

### ISSUE THREAD

**Issue by imchivaa** [DirectoryLister/DirectoryLister#404]
Ask your question. Please provide as much detail as possible.
Hi there, is there a documentation for me to refer on how to upgrade the version of the script? 

Thanks.

**Comment by PHLAK** [comment]
To upgrade from one 3.X release to the next:

  1. Download the latest version from https://www.directorylister.com
  2. Extract the zip/tar archive
  3. Copy `index.php` and the `app` folder to your web server replacing any existing files
  4. Clear the cache by deleting all files in the `app/cache` directory

Instructions for upgrading from the 2.X version can be found in the [Upgrade Guide](https://github.com/DirectoryLister/DirectoryLister/wiki/Upgrade-Guide).

I will add the 3.X upgrade instructions to that guide as well.
