### ISSUE TITLE
Can I set the root directory of DirectoryLiser?

### ISSUE THREAD

**Issue by zlf341** [DirectoryLister/DirectoryLister#410]
Thank you for your great work.

I have a situation:
directorylister is under a folder, but I want to list file in other folder
e.g.
webroot/
     directorylister-folder/
     files-to-list-folder/

is it possible to set the root folder of listing?

Thank you
Jerry Zhang

**Comment by PHLAK** [comment]
This is not possible, see [here](https://github.com/DirectoryLister/DirectoryLister/issues/266#issuecomment-610699596) for a little more information as to why.
However, if you install Directory Lister to the folder you wish to list (i.e.`files-to-list-folder`) it should work as expected.

**Comment by zlf341** [comment]
thank you, 

how about this 
app/config/container.php
'base_path' => dirname(__DIR__, 2),
if I update the base_path, does it work?

Regards
JZ

**Comment by PHLAK** [comment]
Unfortunately no, that will not work.

**Comment by olfek** [comment]
I have submitted my PR #541
