### ISSUE TITLE
hide directory lister url 2

### ISSUE THREAD

**Issue by leeuwtjex** [DirectoryLister/DirectoryLister#419]
Chris,

Thanks for your reply. I understand that copy the directory lister folder inside another folder
will move the complete application, however, I like to hide the part of the url which is the directory lister folder.  It should be accessed only form the other application, and not visible directly to the real url link. 

Well, I guess that is asked too much.
I am still happy with your works, thank you.

Dirk

--------------------------------------------------------------------------
If you want your site URL to be "https://site.com/applicationx/" install Directory Lister in the applicationx folder. 

Chris
------------------------------------------------------------------------
Hi team,

First of all thanks for this very handy piece of software.
I am very happy to use it. I am a student php and I have a question.
I have developed a php application (only student purpose) which refers to
your directorylister app url on my system like this:

header("Location: https://site.com/applicationx/directorylister");
exit;
very simple, I know. What I am trying to do, when my application forwards
to this link, it exposes the hard url. I am trying to find a way where only
"https://site.com/applicationx/" is exposed and further nothing, to have some security.
Would there be a way to get this behaviour with directorylister 3.0? a Hide ?
I know this is a webserver job, but the problem is I am forced to use lighttpd and this has no htaccess comfig like apache2 or similar.....

Thanks for helping.

Dirk.

**Comment by PHLAK** [comment]
> I like to hide the part of the url which is the directory lister folder. It should be accessed only form the other application, and not visible directly to the real url link

You might be able to accomplish this via your web server URL rewrite rules or perhaps even via an `iframe`. However, this is not something Directory Lister can do natively.

Also, please respond to the original question instead of creating a new one in the future.
