### ISSUE TITLE
How can I remove "? Dir =" from the URL

### ISSUE THREAD

**Issue by HCARX** [DirectoryLister/DirectoryLister#425]
How can I remove "? Dir =" from the URL
For example: https://domain.com?Dir=A/B/C
Display as: https://domain.com/A/B/C

The latter will show 403 Forbidden
For example: https://demo.directorylister.com/tests/Bootstrap/

**Comment by PHLAK** [comment]
You may be able to accomplish this via your web server's configuration. That is by using [Apache `mod_rewrite`](https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html) or [NGINX Rewrite Rules](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html). This is not something Directory Lister can do out of the box.

**Comment by flatblowfish** [comment]
Need this feature? Check out my modification. Its  very easy.
[flatblowfish/modify-directory-lister](https://github.com/flatblowfish/modify-directory-lister)
