### ISSUE TITLE
Add a config that allows ZIP-downloads only in sub-directories

### ISSUE THREAD

**Issue by gonztest** [DirectoryLister/DirectoryLister#432]
there is no need for displaying the ZIP-download button in the root directory, if lot of data is hosted, and/or if u dont want users to download a copy of all you host. i want the users on my website to only be able to zip download in sub directories.

i used to disable the zip-download button in the root directory in your very old directory lister version by not showing it if the current url (e.g. $currenturl = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";) equals index, or root directory.

however, this simple approach cant be manifested anymore. do you have a suggestion how i could achieve my goal?

**Comment by PHLAK** [comment]
I am unable to reproduce this with a fresh installation of v3.5.0.

Try clearing your cache (`rm -rf app/cache/*`) and see if the problem is resolved. If not, you may need to delete `index.php` and the entire `app` folder and re-add them from a fresh v3.5.0 download.
