### ISSUE TITLE
Remove "Download this Directory"

### ISSUE THREAD

**Issue by pjrfigueiredo** [DirectoryLister/DirectoryLister#436]
I'm frustrated to see "Download this Directory". :)

We should be able do disable the action/link on .env.
We might face errors like this  "Allowed memory size of 134217728 bytes exhausted (tried to allocate 2214846256 bytes)"

<img width="321" alt="Captura de ecrã 2020-07-27, às 10 38 24" src="https://user-images.githubusercontent.com/4716199/88527709-8e539180-cff5-11ea-8706-1a7091c4b60c.png">

<img width="398" alt="Captura de ecrã 2020-07-27, às 10 38 16" src="https://user-images.githubusercontent.com/4716199/88527714-8eec2800-cff5-11ea-9828-5ff265c52a17.png">

tnks for DL!!

**Comment by PHLAK** [comment]
This can be disabled via the [`ZIP_DOWNLOADS`](https://github.com/DirectoryLister/DirectoryLister/wiki/App-Config-Reference#zip_downloads) configuration option in your `.env` file.
