### ISSUE TITLE
<head> & <body>

### ISSUE THREAD

**Issue by FrangaL** [DirectoryLister/DirectoryLister#447]
Are the `<head>` and `<body>` tags unnecessary?

Isn't it a problem with older browsers?

**Comment by PHLAK** [comment]
The `<html>`, `<head>` and `<body>` tags are optional acording to the HTML 5 spec and the [Google HTML/CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags) recommends omitting them entirely (as I've done here).

**Comment by koxo** [comment]
Thank you for your response.

Even if we can omit the tags, I don't find it very clean.

Best regards

KoXo

**Comment by PHLAK** [comment]
I guess that's a matter of personal preference then because I find it cleaner.
