### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by PHLAK** [DirectoryLister/DirectoryLister#46]
Add the ability to sort files by modified date.

**Comment by bentech4u** [comment]
HI,

is this feature added?

**Comment by acrolink** [comment]
This **is** the reason I installed this tool. No sorting by date?

**Comment by squadjot** [comment]
I'd like this aswell =)

**Comment by aser007** [comment]
I want to sort after Last Modified Category is it possible?
'list_sort_order'           => '?????',

**Comment by squadjot** [comment]
bump

**Comment by Jack3113** [comment]
I made a fork with sort by date, name and size [on my github](https://github.com/Jack3113/DirectoryLister)

**Comment by nixmomo** [comment]
Can you push your changes into my master ? 

Von meinem iPhone gesendet

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).

**Comment by PHLAK** [comment]
FYI, this is available in Directory Lister 3 :slightly_smiling_face:
