### ISSUE TITLE
How do you add AdSense code?

### ISSUE THREAD

**Issue by unixandria-xda** [DirectoryLister/DirectoryLister#485]
I see a bunch of .twig and .php files.

Adding code within a div under components/{file,header}.twig doesn't seem to do the trick.

I'm trying to display a banner ad in the top of the page

**Comment by PHLAK** [comment]
You can add a Google or Matomo Analytics ID via the [`.env` configuration file](https://github.com/DirectoryLister/DirectoryLister/wiki/Configuration)

**Comment by unixandria-xda** [comment]
That's not what I want z I want AdSense not Analytics

**Comment by PHLAK** [comment]
Directory Lister does not support AdSense out-of-the box.

**Comment by unixandria-xda** [comment]
I know this but where would I even add said code? I'm getting > 170 hits/day on my download site, figured might as well monetize it

**Comment by PHLAK** [comment]
To accomplish this you would need to manually edit the view files in `app/views`. You'd probably want to put the code in [`app/views/layouts/app.twig`](https://github.com/DirectoryLister/DirectoryLister/blob/master/app/views/layouts/app.twig) specifically. Once you've made your changes be sure to clear the cache (`rm -rf app/cache/*`) for your change to take effect.

**Comment by unixandria-xda** [comment]
Thanks, it was the clear cache part I was missing :p
