### ISSUE TITLE
Include php file in twig file?

### ISSUE THREAD

**Issue by scriptzteam** [DirectoryLister/DirectoryLister#492]
Hello, so how to include php file into twig template file, or do i need write component file and then add the function into twig?

Sample would be cool too :-D

**Comment by PHLAK** [comment]
You can include a file in a Twig file with the [include function](https://twig.symfony.com/doc/3.x/functions/include.html).

    {{ include('path/to/file.php') }}

The full Twig documentation can be found at <https://twig.symfony.com> if you have additional questions.

**Comment by scriptzteam** [comment]
Oh that simple, thx!
