### ISSUE TITLE
How to hide multiple type?

### ISSUE THREAD

**Issue by Fastmancz** [DirectoryLister/DirectoryLister#493]
Hello,

I need show only a file with type: .dem.bz2 and i need hide .dem type.

Unfortunately, this didn't work:
`
    'app_files' => ['app', 'index.php', '.hidden', '*.dem.[^bz2]'],
`

This will hide all files *.dem.bz2 and *.dem.
`
    'app_files' => ['app', 'index.php', '.hidden', '*.dem'],
`

Thanks for answer.

**Comment by PHLAK** [comment]
I don't believe this is possible with our current implementation but would definitely be worth adding.

Feel free to take a look at the [Hiding Files](https://github.com/DirectoryLister/DirectoryLister/wiki/Hiding-Files) documentation and see if you can come up with something that works though.

**Comment by PHLAK** [comment]
I'm thinking of adding "lookaheads" so something like this would work, what do you think?

```
**.dem(?!.bz2)
```

This would match all files containing `.dem` (e.g. `file.dem`, `file.dem.gz`, `file.dem.tar.gz`, etc.)  BUT NOT `file.dem.bz2`

**Comment by Fastmancz** [comment]
Yes, that sounds like a good idea.

**Comment by PHLAK** [comment]
Resolved with [v3.7.0](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.7.0)
