### ISSUE TITLE
Multibyte-safe case-insensitive order and on-page media play?

### ISSUE THREAD

**Issue by rampageX** [DirectoryLister/DirectoryLister#512]
1. Can we have a option to ignore case when using name sorting or natural sorting;

2. Furthermore, can we have multibyte-safe when 1;

3. Can we play/preview some video/audio files direct in browser like picture?

**Comment by PHLAK** [comment]
1. Directory Lister uses the [sorting methods](https://symfony.com/doc/current/components/finder.html#sorting-results) provided by `symfony/finder`. If you need something custom you can use an [anonymous function](https://www.php.net/manual/en/functions.anonymous.php) to specify a [custom sort order](https://github.com/DirectoryLister/DirectoryLister/wiki/App-Config-Reference#sort_order).

2. Same as above

3. This is not something we'll likely be adding.
