### ISSUE TITLE
Add lightbox to images

### ISSUE THREAD

**Issue by studiomycel** [DirectoryLister/DirectoryLister#513]
Hello,
I'm running an older version of DirectoryLister (2.7.0) where I've implemented Chocolat.js (Responsive Lightbox) for viewing images. All files ending with an image-format would open up the viewer.

I love DirectoryLister and would love to update to the latest version, but I couldn't figure out how to implement this Lightbox. My coding is getting a bit rusty so I had a harder time understanding the new structure. 

I would greatly appreciate if you could point in a direction where I could get started. Where would I install it? And how would I begin to implement it?

Best regards,
Christopher

**Comment by PHLAK** [comment]
This isn't officially supported and would require manually carrying any changes forward between updates.

However, check in the `app/views` directory for the view templates and the `app/resources` directory for JavaScript and CSS (Sass) files. The files you'd likely want to modify are almost certainly going to be found in one of these places.
