### ISSUE TITLE
Very large pagefile.sys on Windows drive causes problem

### ISSUE THREAD

**Issue by w4edp** [DirectoryLister/DirectoryLister#515]
Am running this just fine in most cases but on a few servers where there is a large pagefile.sys (15+ Gig), it causes problems for DirectoryLister.  Any solution?

**Comment by PHLAK** [comment]
First, I believe the `pagefile.sys` lives in the root of the `C:\` drive by default. It is **NOT** recommended to list the entire drive as it would expose all of the data on that drive including personal and system files. Try listing a more specific directory instead.

Also, what kinds of problems is it causing? Please provide additional details (e.g. error messages) so we can attempt to understand and solve the problem.

**Comment by w4edp** [comment]
This server has multiple drives.  DirectoryLister is on the D drive, where the page file also is.  I want to list the drive starting at the root of D as there are 4 apps on the D drive.

The page error is:
An unexpected error occurred Enable debugging for additional information.

When enabling debug I get:
Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("SplFileInfo::getSize(): stat failed for .\pagefile.sys").
Previous exceptions
SplFileInfo::getSize(): stat failed for .\pagefile.sys (0)

And the following is displayed:

![image001](https://user-images.githubusercontent.com/62666443/99128659-60608000-25d9-11eb-8293-f4f927c38300.png)

**Comment by PHLAK** [comment]
This might be a permissions issue. Try adding `pagefile.sys` to your [hidden files](https://github.com/DirectoryLister/DirectoryLister/wiki/Hiding-Files) and see if the problem persists.

**Comment by w4edp** [comment]
Adding pagefile.sys to the hidden files does not work.

**Comment by w4edp** [comment]
I just noticed that .hidden doesn't seem to be working.  The app folder and index.php as well as anything I place in .hidden is NOT hidden.  

I have the following in .hidden which is located in the same dir as app and .env
'hidden_files' => [
    'AdoptOpenJDK',
    'pagefile.sys',
]

**Comment by PHLAK** [comment]
Make sure Explorer is configured to [show file extensions](https://support.winzip.com/hc/en-us/articles/115011457948-How-to-configure-Windows-to-show-file-extensions-and-hidden-files). I suspect the `.hidden` file is being created with an extension which it should not be.

**Comment by w4edp** [comment]
Doubled checked, no extension.  .env and .hidden are just as shown, no extension.

**Comment by w4edp** [comment]
This is running on Server 2012R2 64bit and PHP is 7.4.12

**Comment by PHLAK** [comment]
I don't have Windows server to test on but everything is working as expected on Windows 10.

**Comment by w4edp** [comment]
Everything works fine except for hiding files and the pagefile.sys issue.  I'll continue to try things on this end.  My biggest need is a workaround for the pagefile issue.  Thanks.

**Comment by w4edp** [comment]
I believe that the issue is not with the pagefile itself, I have run into this same issue in other directories and it seems that DirectoryLister doesn't like locked files.

In every situation, there is 1 or more locked files in the directory where DL chokes.  If you shutdown the application that has those file locked/open, the problem goes away.

What can be done about that, what are my options?  Not being able to have DL deal with open/locked files is a no go for me.

Thanks for your app and your help!

**Comment by PHLAK** [comment]
> there is 1 or more locked files in the directory where DL chokes

If an application puts a lock on a file then other applications (not just Directory Lister) wouldn't be allowed to access those file and wouldn't be a problem with Directory Lister.

Being that `pagefile.sys` is a system file it may be locked or have special permissions that prevent Directory Lister from accessing it.

**Comment by w4edp** [comment]
Thanks, I still do not understand why hidden files won't work.  I have triple checked everything and according to all instructions I have it correct, but yet no go.  Maybe I'll load things up on a non Windows server OS and see if it's something with server OS.  Thanks
