### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by davidjmorin** [DirectoryLister/DirectoryLister#517]
**Directory Lister Version**
Latest

**PHP Version**
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**PHP Extensions**
[PHP Modules]
apcu
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libsmbclient
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
smbclient
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**HTTP Server**
Apache

**Describe the bug**

getting 500 error on load. 

**Steps To Reproduce**

visit page

**Expected behavior**

show files or atleast some output. 

**Additional context**

![image](https://user-images.githubusercontent.com/9400895/99461018-f6a8e480-28fe-11eb-9a9a-36eb15ce33d9.png)

![image](https://user-images.githubusercontent.com/9400895/99461354-abdb9c80-28ff-11eb-8863-a3b14a3782d6.png)

**Comment by davidjmorin** [comment]
It says easy install, just drag and drop and edit the .env file.  This has all been done.  Still not working.

**Comment by davidjmorin** [comment]
and when trying to install with composer.

![image](https://user-images.githubusercontent.com/9400895/99461975-c82c0900-2900-11eb-85fb-0d494806606b.png)

**Comment by PHLAK** [comment]
The 500 error screenshot is not from Directory Lister and the screenshot from `composer create-project ...` is throwing an error from a file on your host (`/usr/share/php/...`), not from Directory Lister. It seems like your host and/or web server are not properly installed/configured and you should ensure those are working first before attempting to install Directory Lister.

**Comment by davidjmorin** [comment]
I have tried this on 3 different servers with the same result.  I gave up and went with another setup. THanks
