### ISSUE TITLE
New option to always download files

### ISSUE THREAD

**Issue by LumitoLuma** [DirectoryLister/DirectoryLister#518]
**Is your feature request related to a problem? Please describe.**
I use Directory Lister to show some downloads on my website. The problem is that there are some file formats that some browsers don't recognize as a download (example: Firefox with .7z). 

**Describe the solution you'd like**
Add an optional feature that forces the download of all the files.

**Comment by PHLAK** [comment]
This can be controlled via your web server configuration. Search for something like `apache` or `nginx` + `force download file` or `file content type`.

**Comment by williannasc** [comment]
in file.twig I put this in the <a> tag at the beginning of the file 
```
    {%if file.isFile %}
        download
    {% endif %}
```
