### ISSUE TITLE
Directory Lister v2.7.1 / Bootstrap 4.5.3

### ISSUE THREAD

**Issue by DmitrysXYZ** [DirectoryLister/DirectoryLister#520]
Directory Lister v2.7.1 / Bootstrap 5

Directory Lister v2.7.1 / Bootstrap 5 is not working

how to change Bootstrap 3.4.1  to Bootstrap   v4.5.3  ?

**Comment by DmitrysXYZ** [comment]
test version Directory Lister v2.7.1

Font Awesome verion  5.14  OK 
Bootstrap version 3.4.1  OK
jQuery  version 3.5.1  OK


Bootstrap  version v4.5.3 NOT SUPPORT

**Comment by PHLAK** [comment]
Directory Lister 2.X is no longer supported.
