### ISSUE TITLE
How to add as default Apache Index Listing?

### ISSUE THREAD

**Issue by Some1OnLine** [DirectoryLister/DirectoryLister#533]
Is there any how-to/guide on making DirectoryLister the default index list viewer for all my folder that I would otherwise list files/folders? Currently it only shows the files in the main DirectoryLister root folder.

Thanks,

~SOL

**Comment by PHLAK** [comment]
I'm not sure this is possible and isn't the intent of Directory Lister. To my knowledge you'd have to manually install Directory Lister wherever you want to list files.
