### ISSUE TITLE
Preview files

### ISSUE THREAD

**Issue by Miosame** [DirectoryLister/DirectoryLister#538]
Currently files, even .php files are executed instead of safely previewed/downloaded, where could I hook into in the code to 
display files instead - if matching a certain file extension, otherwise force a download?

Edit:
I see this is related to: https://github.com/DirectoryLister/DirectoryLister/issues/334 since indeed I saw the demo doing that too. 
I suppose one should hook into here: https://github.com/DirectoryLister/DirectoryLister/blob/84b15e5c35923e5b9a67dae04470742e99cd19e2/app/src/ViewFunctions/FileUrl.php then?

**Comment by PHLAK** [comment]
As stated in #334 Directory Lister doesn't handle file downloads/previews but hands that off to the web server (Apache, NGINX, etc.). Unfortunately there's no way to disable processing PHP files in the web server and still have PHP applications (Directory Lister included) work.
