### ISSUE TITLE
Possibility to change home folder

### ISSUE THREAD

**Issue by SantaHey** [DirectoryLister/DirectoryLister#540]
Maybe I missed something but now it seems that application files have to be in the root folder.

Maybe it could be good to add possibility to choose a home folder in the configuration file, is it something possible ?

(sorry for my bad english)

**Comment by olfek** [comment]
Hello, @PHLAK mentioned in #410 that it was not possible, but I think I have something that works, I will submit the PR in a few days hopefully 😊️

**Comment by olfek** [comment]
@SantaHey Feel free to assign this issue to me

**Comment by SantaHey** [comment]
> 
> 
> @SantaHey Feel free to assign this issue to me

thank you for your answer

only the owner can assign an issue to another user

**Comment by PHLAK** [comment]
@olfek is correct, this is not currently possible for technical and security reasons.

I am interested in what you have though @olfek, but keep in mind that we will not be implementing anything that compromises security for the out-of-box installation.

Closing this issue for now.

**Comment by olfek** [comment]
@PHLAK Maybe you could keep this issue open to host our discussion while the PR doesn't exist?

**Comment by PHLAK** [comment]
@olfek Feel free to start a discussion over in the [Discussions](https://github.com/DirectoryLister/DirectoryLister/discussions). I prefer to keep this issue closed since it's not technically an issue (helps me track things better).

**Comment by olfek** [comment]
I have submitted my PR #541

**Comment by PHLAK** [comment]
Starting with the [v5.0.0 release](https://github.com/DirectoryLister/DirectoryLister/releases/tag/5.0.0) it is now possible to list any directory (even one outside of the application installation path) via the [`FILE_PATH` environment variable](https://docs.directorylister.com/configuration/app-config-reference#files_path).
