### ISSUE TITLE
Matomo tracking code references wrong script

### ISSUE THREAD

**Issue by jamaa** [DirectoryLister/DirectoryLister#555]
**Directory Lister Version**

3.7.2

**PHP Version**

PHP 7.2+

**Describe the bug**

The Matomo tracking code in matomo.twig has a hardcoded reference to https://cdn.matomo.cloud/directorylister.matomo.cloud/matomo.js, which causes a 403 Forbidden error for me. 

The tracking code from my Matomo admin interface provides a script which references matomo.js from my own installation.

To fix this, replace 
```g.src='//cdn.matomo.cloud/directorylister.matomo.cloud/matomo.js';```  
with
```g.src=u+'matomo.js';```
in matomo.twig

**Steps To Reproduce**

Activate Matomo tracking and inspect the console in the browser.

**Expected behavior**

Reference the matomo script from my own Matomo installation.

**Additional context**

Browser console:
![grafik](https://user-images.githubusercontent.com/90166/105475805-1a422f80-5ca0-11eb-8ba1-4e4a9cb78339.png)

**Comment by PHLAK** [comment]
Good catch, thanks. I'll try to fix this and get a release out this weekend.

**Comment by PHLAK** [comment]
Fixed with [v3.7.3](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.7.3)
