### ISSUE TITLE
File inside directory has broken path, file can't be found.

### ISSUE THREAD

**Issue by danielmee** [DirectoryLister/DirectoryLister#57]
I'm not a programmer so am not sure what's going on but I have created an example so you can see what's happening: http://danielmee.com/dl/
If you click on /test directory and then on test2.mp3 you get a 404: "The requested URL /dl/test/test2.mp3 was not found on this server."
I note though that the URL says: `/dl/test%2Ftest2.mp3` and not `/test/test2.mp3`.
Also reported in this [google group post](https://groups.google.com/forum/#!topic/directory-lister/WjLAOlFS0zw).

**Comment by PHLAK** [comment]
I believe this was resolved.  Please comment if you notice the issue again with the latest version of DL.
