### ISSUE TITLE
template fails to render page with a broken symlink

### ISSUE THREAD

**Issue by tzlils** [DirectoryLister/DirectoryLister#573]
**Directory Lister Version**

**PHP Version**

7.4

**PHP Extensions**

https://hatebin.com/qwprurnffn

**HTTP Server**

nginx/1.18.0 (Ubuntu) 

**Describe the bug**

![image](https://user-images.githubusercontent.com/35463279/108201027-ef74bb00-7127-11eb-9771-0760277426e1.png)
DirectoryLister fails to render a page if a broken symlink is present in the directory, empty files are not affected

**Steps To Reproduce**

Create a broken symlink and attempt to view the directory with DirectoryLister

**Expected behavior**

Mark the file as broken / 0kb in size

**Additional context**

https://hatebin.com/yqepoctaou

**Comment by PHLAK** [comment]
Thanks, I'll see what I can do about this when I have some free time.

**Comment by PHLAK** [comment]
I believe I've fixed this with 8076862029e36a43213dbb2a8bd50a9c09f0a100, will be available in the next release (not sure when that will be at the moment).
