### ISSUE TITLE
Error when downloading folder

### ISSUE THREAD

**Issue by antoine2tt** [DirectoryLister/DirectoryLister#582]
Hello,

**Directory Lister Version**

Last one 

**PHP Version**

PHP 7.4.3

**PHP Extensions**

[PHP Modules]
calendar
Core
ctype
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**HTTP Server**

Nginx 1.18.0

**Describe the bug**

When i'm trying to download a foler (4 files, 650mb, 10kb, 5kb, 7kb) i got an error

**Steps To Reproduce**

Download a fodler 

Here's the screenshot of the error

![woops](https://user-images.githubusercontent.com/979136/111086651-98db8080-851d-11eb-8ff5-8ea0648c811a.png)

I don't know what to do with it :(

Thanks for your help.

**Comment by PHLAK** [comment]
How big is the folder you're attempting to download? You may need to [increase your PHP memory limit](https://www.php.net/manual/en/ini.core.php#ini.memory-limit) to account for large directories.
