### ISSUE TITLE
Search does not return results it should return

### ISSUE THREAD

**Issue by korry73** [DirectoryLister/DirectoryLister#603]
**Directory Lister Version** = 3.7.6

**PHP Version** = 7.4

**HTTP Server** = nginx latest

I am using DirectoryLister to expose my books library and have discovered the following issue: I have a file called 04 Щети.epub. When I search for "Щет", the file is found:

![image](https://user-images.githubusercontent.com/32910820/113503096-6202f400-9538-11eb-8979-c40b7365b93b.png)

However if I search for "Щети", I get no results:

![image](https://user-images.githubusercontent.com/32910820/113503137-8ced4800-9538-11eb-9cad-c7d11d7879d3.png)

Second, thing, when I click on the info icon, I see filenames wrongly encoded. It could be a setting, but I am not a developer. 

![image](https://user-images.githubusercontent.com/32910820/113503171-ca51d580-9538-11eb-85b5-415c71cc8adf.png)

The site is in Bulgarian. I have translated the app. Are you interested in the translation?

kind regards
Korry

**Comment by PHLAK** [comment]
Thanks, I will look into this. However, I suspect this may be a limitation of the [Symfony Finder](https://symfony.com/doc/current/components/finder.html) (the package used under the hood for file listing/searching).

**Comment by PHLAK** [comment]
> The site is in Bulgarian. I have translated the app. Are you interested in the translation?

Definitely! Please submit a PR with the added translation.

**Comment by korry73** [comment]
I attach the translation here. What about the encoding on the last screenshot? 
[bg.tar.gz](https://github.com/DirectoryLister/DirectoryLister/files/6276262/bg.tar.gz)

**Comment by PHLAK** [comment]
> What about the encoding on the last screenshot?

I will look into that as well.

**Comment by korry73** [comment]
I did not change anything (well, have cleared the cache several times, but should not be relevant) and now the problematic file gets found. Complete mistery :) but I think we can close this.

**Comment by PHLAK** [comment]
Interesting. Did you update Directory Lister at any point?

**Comment by korry73** [comment]
No, I did not update it. I recall I have deleted a file called CompiledContainer.php (it gets recreated automatically) but I do not know if it did fix it. Strange, but now I do not have any search related issues.
BTW, is there an update regarding the file encoding when you click on info?

**Comment by PHLAK** [comment]
> No, I did not update it.

Odd.

> is there an update regarding the file encoding when you click on info?

Not yet.
