### ISSUE TITLE
Disable Caching on read-only filesystem.

### ISSUE THREAD

**Issue by WeWin55** [DirectoryLister/DirectoryLister#613]
Hello,

Is it possible to disable the caching completely via config?
Maybe the search must be disabled too, if caching is "not working"
My scenario is an read only nfs mount inside the DirectoryLister root folder.
This way im viewing the files on the nfs share.

Im right now using an old version (2.X) and wanted to upgrade to version 3.7.7.

Here is the log output from nginx:
2021/04/12 15:10:40 [error] 10757#10757: *3885 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Compilation directory is not writable: /var/customers/webs/webroot/twitch/app/cache. in /var/customers/webs/webroot/twitch/app/vendor/php-di/php-di/src/Compiler/Compiler.php:365
Stack trace:
#0 /var/customers/webs/webroot/twitch/app/vendor/php-di/php-di/src/Compiler/Compiler.php(180): DI\Compiler\Compiler->createCompilationDirectory('/var/customers/...')
#1 /var/customers/webs/webroot/twitch/app/vendor/php-di/php-di/src/ContainerBuilder.php(182): DI\Compiler\Compiler->compile(Object(DI\Definition\Source\SourceChain), '/var/customers/...'
, 'CompiledContain...', 'DI\\CompiledCont...', true)
#2 /var/customers/webs/webroot/twitch/index.php(26): DI\ContainerBuilder->build()
#3 {main}

  thrown in /var/customers/webs/webroot/twitch/app/vendor/php-di/php-di/src/Compiler/Compiler.php on line 365" while reading response header from upstream, client: 5.10.4.70, server: web.site, request: "GET /twitch/ HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "web.site"

**Comment by PHLAK** [comment]
Adding the following environment variables to your `.env` file _should_ disable caching completely.

    CACHE_DRIVER=array
    VIEW_CACHE=false

**Comment by WeWin55** [comment]
Thanks for the fast answer. Unfortunately disabling cache didnt work.

Here is the same error message:
2021/04/12 17:55:51 [error] 10757#10757: *4316 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Compilation directory is not writable: /var/customers/webs/webroot/twitch/app/cache. in /var/customers/webs/webroot/twitch/app/vendor/php-di/php-di/src/Compiler/Compiler.php:365


Here is my config:
cat .env
# Here you can control Directory Lister configuration through environment
# varaibles. See the configuration documentation for additional information:
# https://docs.directorylister.com/configuration

APP_DEBUG=false
APP_LANGUAGE=en

# disable caching completely -> read only nfs
CACHE_DRIVER=array
VIEW_CACHE=false

DISPLAY_READMES=true
READMES_FIRST=false
ZIP_DOWNLOADS=true

GOOGLE_ANALYTICS_ID=false

MATOMO_ANALYTICS_URL=false
MATOMO_ANALYTICS_ID=false

SORT_ORDER=type
REVERSE_SORT=false

**Comment by PHLAK** [comment]
Ahh shoot, forgot about the container compilation. It is possible to disable compilation of the container by adding `APP_DEBUG=true` as well in your `.env`, however this is NOT recommended as it can cause [server data leakage](https://docs.directorylister.com/configuration/app-config-reference#debug).

I will consider adding a way to disable container compilation _without_ enabling debug in a future release but for now this is the only way to accomplish this.

**Comment by WeWin55** [comment]
Hi,
thanks for the fix.
A way without enabling debug would be nice :)

**Comment by PHLAK** [comment]
Resolved with [v3.7.8](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.7.8).

Starting with v3.7.8 you can add `COMPILE_CONTAINER=false` in your `.env` file to disable container compilation.

**Comment by FabihaBaba** [comment]
Can you do it? https://cdn.nagordola.com.bd/
