### ISSUE TITLE
Required php version raised to 7.3?

### ISSUE THREAD

**Issue by nomad-57** [DirectoryLister/DirectoryLister#623]
**Directory Lister Version**

 
3.7.2+

**PHP Version** 

 

7.2.24 on centos 8

**PHP Extensions**

[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zlib

**HTTP Server**

nginx 1.18

**Describe the bug**

``Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0".  

**Steps To Reproduce**

unzip and place directory lister in webroot
try to navigate to url

**Expected behavior**

Directorylister loads normally

**Additional context**

Versions below 3.7.2 seems to work fine.

**Comment by PHLAK** [comment]
Thanks, I'll look into this. My initial guess is one of the dependencies bumped their required version.

**Comment by PHLAK** [comment]
Fixed with [v3.7.9](https://github.com/DirectoryLister/DirectoryLister/releases/tag/3.7.90)
