### ISSUE TITLE
open_basedir causes errors when DL is ran from a sub-directory

### ISSUE THREAD

**Issue by PHLAK** [DirectoryLister/DirectoryLister#65]
With the implementation of 'open_basedir' in Directory Lister v2.5.2 and when running Directory Lister in a non-top level directory, the following errors show:

    open_basedir restriction in effect

**Comment by ecko2010** [comment]
how we can solve this error ??

**Comment by PHLAK** [comment]
For now, revert to using v2.5.1, I'll be working on fixing this soon.
