### ISSUE TITLE
hidden_files not work

### ISSUE THREAD

**Issue by yduke** [DirectoryLister/DirectoryLister#652]
**Directory Lister Version**

v3.8.3

**PHP Version**

PHP 7.3.24

**PHP Extensions**

curl
date
dom
exif
fileinfo
filter
gd
hash
imagick
json
libxml
mbstring
mysqlnd
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
readline
Reflection
session
SimpleXML
SPL
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

**HTTP Server**

 Apache 2.4

**Describe the bug**

didn't change:
`'hidden_files_list' => DI\env('HIDDEN_FILES_LIST', '.hidden'),`

But set 'hidden_files' below with:
```
    'hidden_files' => [
    'Thumbs.db', 
    ],
```
And cleared the cache folder, but it doesn't work, the thumbs.db file still presents.

**Expected behavior**

`'hidden_files'` should hide the file in the arrary.

**Comment by yduke** [comment]
I am sorry, my pc is at mess, I don't know how I labeled a "bug"tag in this. 
This might not be a real bug, please remove the label "bug" will you?  @PHLAK thank you and sorry.

**Comment by PHLAK** [comment]
The [`hidden_files`](https://docs.directorylister.com/configuration/app-config-reference#hidden_files) and [`hidden_files_list`](https://docs.directorylister.com/configuration/app-config-reference#hidden_files_list) configuration options serve different purposes. 

You can hide


Reference the [Hiding Files documentation](https://docs.directorylister.com/configuration/hiding-files) for additional information.

**Comment by yduke** [comment]
Thank you for reply @PHLAK 

I've read the documents and followed the hidden file part at the beginning.

Sorry about the title of this issue, was a rush at the moment, I did NOT change 'hidden_files_list' accturelly , but the 'hidden_files' part is still not work in my situation.

I've tried both `Thumbs.db` and `thumbs.db` in 'hidden_files', but still not work.

Below is the line 111 to line 123 now in my app.php

```
    'hidden_files_list' => DI\env('HIDDEN_FILES_LIST', '.hidden'),

/**
... 
*/

    'hidden_files' => [
    'Thumbs.db', 
    ],
```

And I had all files in app/cache deleted after changging the app.php, refreshed the web, but the Thumbs.db is still there.

![issure1](https://user-images.githubusercontent.com/4729833/126146161-ee52668b-546a-4cb4-954d-fa3f4659d7a5.png)
![issure2](https://user-images.githubusercontent.com/4729833/126146167-470a437e-6c77-4fe5-a417-d8c191a940df.png)

My file server both work on windows explorer and web end, and the automaticly generated `Thumbs.db` alone with the folder `@eaDir` is really annoring.

Is there any other way to hide a file? Thank you very much.

**Comment by PHLAK** [comment]
From your screenshot the file appears to be in the `Home/music/JoanJett` folder. You _must_ specify the full path in your hidden file definitions.

```php
'hidden_files' => [
    'Home/music/JoanJett/Thumbs.db',
],
```

If you would like to hide _all_ `Thumbs.db` files in any folder you must use a [matching expressions](https://docs.directorylister.com/configuration/hiding-files#matching-expressions).
```php
'hidden_files' => [
    '**/Thumbs.db',
],
```

**Comment by yduke** [comment]
What a fool I am.
Thank you @PHLAK , it works perfectly! Good job!
