### ISSUE TITLE
How to hide main folders

### ISSUE THREAD

**Issue by movibeast** [DirectoryLister/DirectoryLister#672]
**Is your feature request related to a problem? Please describe.**

I would like to know if there is a way to hide the main folders.
**Describe the solution you'd like**

I would like to hide the root folder and sub-folder. So If someone use the 3rd folder link (inside of sub-folder) then show the content of it)

e.g.
Root/AnotherFolder/3rdFolder

thank you

**Comment by PHLAK** [comment]
There's no way to hide the root folder. The best way to accomplish this would be to install Directory Lister in `3rdFolder` and link to it directly.
