### ISSUE TITLE
New window (I know Issue #34)

### ISSUE THREAD

**Issue by meisemma** [DirectoryLister/DirectoryLister#69]
Hello

I think the code is really really cool...thanks. Sorry for opening up issue #34 again...but I'm stuck. I'd like to use the target _blank feature as I want to use it in an iframe, and when I click say on a PDF it opens it within the iframe. I hope that's ok. I've read the readme and have made sure that the link to Directory lister is still showing.

Many thanks for your hard work

Emma

**Comment by PHLAK** [comment]
You're welcome to make this change within your own Directory Lister installation.  However, this will not be added by default.
