### ISSUE TITLE
Allow set another place as root directory

### ISSUE THREAD

**Issue by ahdung** [DirectoryLister/DirectoryLister#698]
as title said.

**Comment by PHLAK** [comment]
This is not possible for technical reasons, see #544.

**Comment by PHLAK** [comment]
Starting with the [v5.0.0 release](https://github.com/DirectoryLister/DirectoryLister/releases/tag/5.0.0) it is now possible to list any directory (even one outside of the application installation path) via the [`FILE_PATH` environment variable](https://docs.directorylister.com/configuration/app-config-reference#files_path).
