### ISSUE TITLE
SORT_ORDER set to name not working

### ISSUE THREAD

**Issue by ahdung** [DirectoryLister/DirectoryLister#699]
**Directory Lister Version**

3.8.3

**PHP Version**

7.4.23

![image](https://user-images.githubusercontent.com/12094247/133234523-66e1229c-2495-4531-ae98-009a3c7315db.png)

**Comment by PHLAK** [comment]
Internally Directory Lister uses `strcmp()` which sorts things "perfectly" alphabetical (e.g. `file1.txt`, `file10.txt`, `file2.txt`) by default. Try `natural` to sort strings  with the natural sort order algorithm instead (e.g. `file1.txt`, `file2.txt`, `file10.txt`).
