### ISSUE TITLE
[FeatureRequest]Need password

### ISSUE THREAD

**Issue by ahdung** [DirectoryLister/DirectoryLister#700]
Not full authentication system, just a password, like [Evoluted Directory Listing](https://www.evoluted.net/thinktank/web-development/php-directory-listing-script)

**Comment by PHLAK** [comment]
This is not something we will be implementing (see #131, #206, #695).

**Comment by flatblowfish** [comment]
你可以查看我的修改：[modify-directory-lister](https://github.com/flatblowfish/modify-directory-lister)
You can check my modification: [modify-directory-lister](https://github.com/flatblowfish/modify-directory-lister)

**Comment by flatblowfish** [comment]
> Not full authentication system, just a password, like [Evoluted Directory Listing](https://www.evoluted.net/thinktank/web-development/php-directory-listing-script)

一定要引用才能邮件通知吗？

**Comment by ahdung** [comment]
@flatblowfish  I have switched to **filegator**, but still thank you very much. And no need quote, I have received your first reply, just busy ~you know.

**Comment by flatblowfish** [comment]
好，call it alternative，万一那天想用DirectoryLister了呢

**Comment by ahdung** [comment]
谢谢指正。是的，无论用不用，工具变好总不是坏事
