### ISSUE TITLE
Custom colors for Dark/Lightmode

### ISSUE THREAD

**Issue by timfischbach** [DirectoryLister/DirectoryLister#710]
**Is your feature request related to a problem? Please describe.**

Well, it's not a problem, but a comfort for my eyes hahaha :) I don't know why the dark mode purpleish colors hurts my eyes, but they do. It's way to aggressive imo and dark gray / black would suit my eyes more.

**Describe the solution you'd like**

Wouldn't it be fantastic, if the user could set a custom color in the settings by, for example, a HEX code or a RGB value?
This would be a pretty, yet important enhancement for DirectoryLister :)

**Describe possible alternatives**

I've tried to dig through the code and find the color settings, but I couldn't find them (maybe because I only know python and C++ and not php haha :) )

**Additional context**

Anyways, you guys are doing a great job with DirectoryLister and I really like it. Thanks for creating such a powerful tool for http servers! Appreciate it :)

**Comment by PHLAK** [comment]
Thanks for the suggestion. At the moment the CSS is compiled before releasing so it's not easy to allow user-defined styles (colors included).

That being said I will take this into consideration for the future as I understand that different people have different visual preferences/requirements.
