### ISSUE TITLE
et.yaml Estonian translation

### ISSUE THREAD

**Issue by edmundlaugasson** [DirectoryLister/DirectoryLister#719]
Here is the [Estonian language](https://en.wikipedia.org/wiki/Estonian_language) translation
```
home: Algusesse
download: Laadi see kataloog alla
search: Otsi
file:
  name: Failinimi
  size: Suurus
  date: Kuupäev
  info: Teave
powered_by: Kasutusel
scroll_to_top: Liigu üles
toggle_theme: Lülita Hele/Tume režiim

error:
  directory_not_found: Kataloogi ei eksisteeri
  file_not_found: Faili ei leitud
  file_size_exceeded: Fail liiga suur
  no_results_found: Tulemusi ei leitud
  unexpected: Ilmnes ootamatu viga

enable_debugging: Lisateabe saamiseks lubage silumine
```

**Comment by PHLAK** [comment]
Thanks @edmundlaugasson! Can you open a [pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for this addition? This is the desired avenue for contributions and will give you proper attribution in the commit log.

**Comment by PHLAK** [comment]
Added in 2e7b7265b6b60433118b5910e63cacba6bb212f5
