### ISSUE TITLE
open_basedir prevents symlinks from working

### ISSUE THREAD

**Issue by PHLAK** [DirectoryLister/DirectoryLister#72]
When open_basedir is in effect symlinks to files/folders outside of the open_basedir path do not work.

**Comment by Blindmikey** [comment]
Fixed similar error messages by adding this to _readDirectory() after foreach ($files as $file)
```
if ($this->_isHidden($file)) {
	continue;
}
```
And then put my 'public_html' directory in the config.php's 'hidden_files' array

**Comment by Blindmikey** [comment]
For a potential solution I rearranged code in _readDirectory() method so that if '..' == $file, then we wouldn't request realPath at all. 

```
if ($file != '.') {
    if ($file == '..') {
        // Get parent directory path
        ...
        // Add file info to the array
        //... same as before, except $directoryArray['..']['mod_time'] = '-';
    }
    else {
        // Get files relative path
        ...
        // Get files absolute path
        ...
        // Determine file type by extension
        ...
        if ($this->_isHidden($relativePath)) {
            continue;
        }
        // Add all non-hidden files to the array
        ...
    }
}
```

**Comment by PHLAK** [comment]
Closing this as you should never be able to grab a file from above the scripts root directory by default, this is potentially a serious security issue that may expose your server's data.  open_basedir will stay and the unsupported method of making symlinks work will be to disable open_basedir.
