### ISSUE TITLE
Directory is a browse link even if there is an index file inside

### ISSUE THREAD

**Issue by Germain67** [DirectoryLister/DirectoryLister#73]
http://i.imgur.com/cdB0DE6.png

Part of the config that i am using ...

// Basic settings
    'hide_dot_files'     => true,
    'list_folders_first' => true,
    'list_sort_order'    => 'natcasesort',
    'theme_name'         => 'bootstrap',
'index_files' => array(
        'index.htm',
        'index.html',
        'index.php'
    ),

**Comment by PHLAK** [comment]
Hover over the link with an index file inside and you should get an icon to the right.  Click that icon to open the web link instead of the browse link.

**Comment by Germain67** [comment]
Oh i see, but is there a way to only allow browsing directories that does not contain an index ?
