### ISSUE TITLE
建议出docker版本！

### ISSUE THREAD

**Issue by star2k** [DirectoryLister/DirectoryLister#731]
建议推出docker版本！

**Comment by PHLAK** [comment]
Please see [this comment](https://github.com/DirectoryLister/DirectoryLister/issues/266#issuecomment-610699596).

**Comment by PHLAK** [comment]
FYI, starting with the [v5.0 release](https://github.com/DirectoryLister/DirectoryLister/releases/tag/5.0.0) an official Docker image is available. See the [Docker documentation](https://docs.directorylister.com/getting-started/docker) for more information.
