### ISSUE TITLE
php, html and etc. files

### ISSUE THREAD

**Issue by TOWUK** [DirectoryLister/DirectoryLister#748]
i am use your demo website*

fix PHP files:
just click on php/html file and more usability files
![image](https://user-images.githubusercontent.com/28830162/139733014-02e745c3-a6df-4d49-a49c-f52c4bff3e37.png)
![image](https://user-images.githubusercontent.com/28830162/139733032-bc4c0b39-03f4-40a4-85f4-29239bf3f783.png)
![image](https://user-images.githubusercontent.com/28830162/139733301-f511653d-2850-419c-ac9f-e4c4cb2becfa.png)

**Comment by PHLAK** [comment]
Directory Lister does not actually _serve_ files, it only _lists_ them. File serving is handled by your web server. In this case PHP files are interpreted by the PHP engine (which allows Directory Lister to run) and doesn't actually output anything to the browser.

As for the demo, we're hosting the raw application files (including PHP files) which isn't recommend for the reasoning stated above.
