### ISSUE TITLE
queueMicrotask error!

### ISSUE THREAD

**Issue by etjson** [DirectoryLister/DirectoryLister#768]
### Directory Lister Version

>3.7.9

### PHP Version

7.4

### PHP Extensions

...

### Web Server

nginx1.21

### Describe the Bug

Chrome/70.0.3538.25

Version > 3.7.9

queueMicrotask error

**Comment by PHLAK** [comment]
> queueMicrotask error

This doesn't sound like an issue with Directory Lister. Can you [enable debug](https://docs.directorylister.com/configuration/app-config-reference#debug) and see if you get any different errors.

**Comment by etjson** [comment]
![image](https://user-images.githubusercontent.com/41315967/144352557-6cc09320-539f-42b5-adcf-d465b0585fb3.png)
```text
Uncaught ReferenceError: queueMicrotask is not defined
    at app.js?id=77949cbf27b72fc88b6e:1
    at C (app.js?id=77949cbf27b72fc88b6e:1)
    at Object.scheduler (app.js?id=77949cbf27b72fc88b6e:1)
    at S.u.forEach.t (app.js?id=77949cbf27b72fc88b6e:1)
    at Set.forEach (<anonymous>)
    at S (app.js?id=77949cbf27b72fc88b6e:1)
    at Object.set (app.js?id=77949cbf27b72fc88b6e:1)
    at Object.set (app.js?id=77949cbf27b72fc88b6e:1)
    at app.js?id=77949cbf27b72fc88b6e:1
    at _ (app.js?id=77949cbf27b72fc88b6e:1)
```

User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3877.400 QQBrowser/10.8.4533.400

**Comment by etjson** [comment]
@PHLAK 
Using the latest version of Google Chrome is fine.

**Comment by etjson** [comment]
This function should be disabled for browsers that do not support queueMicrotask.

**Comment by etjson** [comment]
Now I can only use version 3.7.9, because 3.8.0 and above will add queueMicrotask.

**Comment by PHLAK** [comment]
I understand now, `queueMicrotask()` must be used in one of the JS dependencies we use. However, from what I'm seeing [it has been supported in all major browsers for some time now](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask#browser_compatibility).

As long as your browser is up to date it should work fine. We cannot guarantee support for browsers that old.

**Comment by etjson** [comment]
@PHLAK 
This is the latest version of China's mainstream browser using the Google kernel, I hope to be able to make a judgment compatible.
