### ISSUE TITLE
How to edit credits in the footer?

### ISSUE THREAD

**Issue by Hardikanand1st** [DirectoryLister/DirectoryLister#791]
### Directory Lister Version

latest

### PHP Version

	PHP 7.3 (ea-php73)

### PHP Extensions

; cPanel-generated php ini directives, do not edit
; Manual editing of this file may result in unexpected behavior.
; To make changes to this file, use the cPanel MultiPHP INI Editor (Home >> Software >> MultiPHP INI Editor)
; For more information, read our documentation (https://go.cpanel.net/EA4ModifyINI)

extension=php_intl.dll
extension=php_mcrypt.dll

### Web Server

Apache

### Describe the Bug

I have edited footer.twig but it dosent take effects

And still the credits are there?  also edited .env

**Comment by nobri** [comment]
Hi, have you tried deleting the contents of the `app/cache/views` folder?
The views are getting cached by default, so it's very likely that what you are seeing is still a cached version of the footer, before you have made any changes.

**Comment by PHLAK** [comment]
@nobri is correct, you would need to clear the view cache for changes to be reflected.

**Comment by Hardikanand1st** [comment]
tried clearing the cache 100000 times no effects :(

With cpanel

With Wp Rocket

With Cloudflare

**Comment by Hardikanand1st** [comment]
> pp/cache/views

Yes it worked thank you so much

**Comment by Hardikanand1st** [comment]
Can you guys please help me with one more thing?, please I was using an old version of directory lister where there was a option in config.php to enable/disable download button can you please guide me for that?

**Comment by nobri** [comment]
Are you using the latest version now?

**Comment by PHLAK** [comment]
Set the [`ZIP_DOWNLOADS`](https://docs.directorylister.com/configuration/app-config-reference#zip_downloads) environment variables to `false` to disable zip downloads.

**Comment by Hardikanand1st** [comment]
> Are you using the latest version now?

1000%

**Comment by Hardikanand1st** [comment]
> Set the [`ZIP_DOWNLOADS`](https://docs.directorylister.com/configuration/app-config-reference#zip_downloads) environment variable to `false` to disable zip downloads.

Thanks Very Much
