### ISSUE TITLE
realpath warning

### ISSUE THREAD

**Issue by unlocomqx** [DirectoryLister/DirectoryLister#80]
I got this warning
http://prntscr.com/73h3sv
I put the lister on the web root to get a nice hompage for my local server, as it tries to get the upper directory it runs into this warning

**Comment by PHLAK** [comment]
For security reasons DirectoryLister cannot access files outside of it's installation path by default.  If you wish to remove this restriction on your own installation open index.php and comment out or remove the following line:

    // Restrict access to current directory
    ini_set('open_basedir', getcwd());

Be warned though, it is possible this can pose a security risk to your server.
