### ISSUE TITLE
Error while listing content of symlink

### ISSUE THREAD

**Issue by ernestlp91** [DirectoryLister/DirectoryLister#804]
### Directory Lister Version

3.10.1

### PHP Version

7.3

### PHP Extensions

mbstring xml zip fpm svg dom ...

### Web Server

nginx

### Describe the Bug

 Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./debian) is not within the allowed path(s): (/srv/repos)").
Previous exceptions

    RecursiveDirectoryIterator::hasChildren(): open_basedir restriction in effect. File(./debian) is not within the allowed path(s): (/srv/repos) (2)

**Comment by PHLAK** [comment]
See https://docs.directorylister.com/help-and-support/common-issues#open_basedir-restriction-in-effect
