### ISSUE TITLE
New install won't run

### ISSUE THREAD

**Issue by EV-soft** [DirectoryLister/DirectoryLister#809]
I follow the installation instructions in Readme, but calling index-php fails:
```
require __DIR__ . '/app/vendor/autoload.php';       -> vendor folder dont exists !
Dotenv::createUnsafeImmutable(__DIR__)->safeLoad(); -> fails !
```
(Fatal error: Uncaught Error: Class "App\Bootstrap\BootManager" not found)

**Comment by PHLAK** [comment]
It sounds like you're installing it from GitHub. If so you'll need to follow the [Development Environment instructions](https://docs.directorylister.com/developers/development-environment).

The proper way to install Directory Lister is by downloading and extracting a release archive from https://www.directorylister.com/#download. You can find [installation instructions in the docs](https://docs.directorylister.com/getting-started/installation).
