### ISSUE TITLE
Warning: realpath(): open_basedir restriction in effect.

### ISSUE THREAD

**Issue by graiggy17** [DirectoryLister/DirectoryLister#81]
( ! ) Warning: realpath(): open_basedir restriction in effect. File(www) is not within the allowed path(s): (\Docs) in \resources\DirectoryLister.php on line 450
Call Stack
#	Time	Memory	Function	Location
1	0.0068	245840	{main}( )	..\index.php:0
2	0.0107	383904	DirectoryLister->listDirectory( )	..\index.php:28
3	0.0107	384568	DirectoryLister->_readDirectory( )	..\DirectoryLister.php:84
4	0.0107	386264	realpath ( )	..\DirectoryLister.php:450

**Comment by PHLAK** [comment]
This is intentional for security purposes.  See: https://github.com/DirectoryLister/DirectoryLister/issues/72#issuecomment-91121084 and https://github.com/DirectoryLister/DirectoryLister/issues/80#issuecomment-101059869
