### ISSUE TITLE
html files with ' in names don't work as links.

### ISSUE THREAD

**Issue by side24** [DirectoryLister/DirectoryLister#82]
When a .html file include ' in its name the resulting link doesn't work.

Mary's Lamb.html will be shown as a link but when used it just returns to directory listing. If any error message is shown I can't see it.

const VERSION = '2.5.3';

**Comment by fulldecent** [comment]
Expand issue: sanitize all inputs for XSS

**Comment by PHLAK** [comment]
I have been unable to reproduce this issue.
