### ISSUE TITLE
Warning: realpath() ??

### ISSUE THREAD

**Issue by asbruff** [DirectoryLister/DirectoryLister#83]
Hi guys,
i'm not a programmer, so excuse me if this question requires a basic understanding of PHP.

I followed the few instructions to install directory lister on my site, but i get an error in the page i open:
 Warning: realpath(): open_basedir restriction in effect. File(/web/htdocs/www.gr-design.it/home) is not within the allowed path(s): (/web/htdocs/www.gr-design.it/home/files) in /web/htdocs/www.gr-design.it/home/files/resources/DirectoryLister.php on line 450

Anyone could help?

**Comment by PHLAK** [comment]
Are you trying to access files above the directory you listed?  If so, this is intentional for security purposes.  See: https://github.com/DirectoryLister/DirectoryLister/issues/72#issuecomment-91121084 and https://github.com/DirectoryLister/DirectoryLister/issues/80#issuecomment-101059869

**Comment by asbruff** [comment]
No, i was trying to access the same folder where the index is uploaded.

2015-05-18 18:16 GMT+02:00 Chris Kankiewicz <notifications@github.com>:

**Comment by PHLAK** [comment]
You may also get this message if you are symlinking files from outside the project root directory.

**Comment by asbruff** [comment]
I'm not symlinking files from outside. This is a plain install.
I don't get this message if I browse sub-directories, but at the root
directory i get it.

2015-05-20 1:13 GMT+02:00 Chris Kankiewicz <notifications@github.com>:

**Comment by PHLAK** [comment]
Can you provide a link to your installation of Directory Lister?  Also, are there any more detailed messages in your PHP error log?

**Comment by asbruff** [comment]
http://www.gr-design.it/files/

I don't know where to retrieve the php error log...

2015-05-20 1:24 GMT+02:00 Chris Kankiewicz <notifications@github.com>:

**Comment by PHLAK** [comment]
I think I've identified the problem within Directory Lister.  Will have to work on a solution and push that before it's fixed.  Sorry for the confusion.

**Comment by PHLAK** [comment]
Resolved with https://github.com/DirectoryLister/DirectoryLister/commit/3bb9a69b466c5c2b6ef6cb15a510fd45b47accb1
