### ISSUE TITLE
TypeError with Vendor Packge phpdotenv

### ISSUE THREAD

**Issue by KLIGGS** [DirectoryLister/DirectoryLister#836]
### Directory Lister Version

v3.10.1

### PHP Version

7.4.22

### PHP Extensions

Fatal error: Uncaught TypeError: substr() expects parameter 1 to be string, bool given in .../public/app/vendor/vlucas/phpdotenv/src/Util/Str.php:52 Stack trace: #0 .../public/app/vendor/vlucas/phpdotenv/src/Util/Str.php(52): substr(false, 0, 3) #1 .../public/app/vendor/vlucas/phpdotenv/src/Store/File/Reader.php(76): Dotenv\Util\Str::utf8('# Here you can ...', NULL) #2 .../public/app/vendor/phpoption/phpoption/src/PhpOption/Some.php(108): Dotenv\Store\File\Reader::Dotenv\Store\File\{closure}('# Here you can ...') #3 .../public/app/vendor/vlucas/phpdotenv/src/Store/File/Reader.php(79): PhpOption\Some->flatMap(Object(Closure)) #4 .../public/app/vendor/vlucas/phpdotenv/src/Store/File/Reader.php(48): Dotenv\Store\File\Reader::readFromFile('/home/netsh1103...', NULL) #5 .../public/app/vendor/vlucas/p in .../public/app/vendor/vlucas/phpdotenv/src/Util/Str.php on line 52

### Web Server

Apache

### Describe the Bug

With PHP 8 not appearing. Testet with different conditions - standard install, and also by composer -update. Checked for .env file

**Comment by KLIGGS** [comment]
I did both from the .com domain as well by composer. By toggling to PHP 8 the error was gone.

**Comment by PHLAK** [comment]
I'm unable to reproduce this error. If you continue to have trouble try enabling debugging and sharing the relevant output here. See the [Troubleshooting documentation](https://docs.directorylister.com/help-and-support/troubleshooting) for more info.
