### ISSUE TITLE
Make `config.php` optional

### ISSUE THREAD

**Issue by fulldecent** [DirectoryLister/DirectoryLister#85]
If the file does not exist (or, in the default installation, only the `default.config.php` exists) then some default values are used.

**Comment by PHLAK** [comment]
I thought of this at one point; if the user didn't have a config.php to just have it fall back to default.config.php.  However, I'm afraid people will then just start modifying default.config.php directly at which point, when then when they update their installation, the file will be overwritten and their changes will be lost.  This also helps with version control in that you can have an authoritative, unchanging config stored in git at default.config.php and your locally modified changes go in config.php which is ignored by git.

**Comment by fulldecent** [comment]
Then I would recommend an error message ("CONFIG FILE REQUIRED"). This should be preferable to the current situation that just produces a PHP warning.

**Comment by PHLAK** [comment]
Yeah, that would be smart.

**Comment by PHLAK** [comment]
Resolved with commit https://github.com/DirectoryLister/DirectoryLister/commit/ee86b6c893ba81dac8f44142828a1b509d4a5f45
