### ISSUE TITLE
Remove `fonts` from `bootstrap`

### ISSUE THREAD

**Issue by fulldecent** [DirectoryLister/DirectoryLister#86]
They are provided by CDN anyway.

**Comment by PHLAK** [comment]
Good idea, thanks.

**Comment by fulldecent** [comment]
PR added

**Comment by PHLAK** [comment]
Resolved with commit https://github.com/DirectoryLister/DirectoryLister/commit/4c12729375be7767e0540660f5b9ca776f2d3f20
