### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by RyderCragie** [DirectoryLister/DirectoryLister#861]
Is there something wrong with my .htaccess file? I'm getting a 500 error when visiting the index.php file. Here's a txt copy of my .htaccess file: [https://RyderCragie.com/htaccess.txt](https://RyderCragie.com/htaccess.txt)

![Screenshot 2022-03-29 155718](https://user-images.githubusercontent.com/69316364/160641259-dc550c7d-a800-462d-9a34-b7563117efca.png)
![Screenshot 2022-03-29 155702](https://user-images.githubusercontent.com/69316364/160641263-a415507c-0f59-466f-973a-8c80f6863a6e.png)
.

**Comment by PHLAK** [comment]
A `500` error indicates a problem with the _web server_. The request is never getting to the application (Directory Lister) code. Check your error logs and consult the documentation for your web server for troubleshooting this issue.
