### ISSUE TITLE
White Page

### ISSUE THREAD

**Issue by NigelNapier** [DirectoryLister/DirectoryLister#876]
### Directory Lister Version

3.11.0

### PHP Version

7.4.29

### PHP Extensions

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
enchant
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imap
intl
ionCube Loader
json
ldap
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
timezonedb
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
the ionCube PHP Loader + ionCube24

### Web Server

LightSpeed

### Describe the Bug

Installed the latest version.

All I get is a white page.
Tried clearing cache from Firefox.

**Comment by PHLAK** [comment]
Please check your web server's error logs and share any relevant logs.

**Comment by NigelNapier** [comment]
There weren't as the page wasn't loading.

**Comment by PHLAK** [comment]
This sounds like an issue with the web server then as it seems the request is never reaching the application code.
