### ISSUE TITLE
Change index file name

### ISSUE THREAD

**Issue by vonflynee** [DirectoryLister/DirectoryLister#89]
Hello,
I want to change index file name from index.php to files.php. After changing filename, script still reffers to mydomain.com/?dir= instead of mydomain.com/files.php?dir= 
Where exactly in the script can I modify this?

**Comment by PHLAK** [comment]
DirectoryLister currently assumes it's running as index.php and wont work if you change the file name.  However, I can see a use for this and will keep this issue open to remind me to improve this in the future.

**Comment by GeorgeUni** [comment]
:+1:

**Comment by chrisschlitt** [comment]
I have implemented this feature with pull request https://github.com/DirectoryLister/DirectoryLister/pull/119

**Comment by vonflynee** [comment]
Thank you very much.
