### ISSUE TITLE
Wrong file Size

### ISSUE THREAD

**Issue by 9944990** [DirectoryLister/DirectoryLister#90]
I noted that the file size information reported is not accurate all the time specially for large files.

Some examples:

ISO File original size: 21,4GB
## Size displayed by script: 1,42GB

OMG File original size: 28,7 GB
Size displayed by script: 747,67MB

Server Info:
Windows Server 2012 R2
IIS 8.5
PHP 5.3 (CGI)

**Comment by PHLAK** [comment]
I will investigate this issue.

**Comment by AppFull** [comment]
Seems also affected debian 32bit system, large file shows negative value

**Comment by XeonG** [comment]
https://github.com/phillip-hopper/DirectoryLister/commit/5a74bba6159c771502a6ea6fe83992775995ef7c

**Comment by XeonG** [comment]
fix was done above.. though requires access to 'exec' to work

**Comment by venadHD** [comment]
32 bits system only can show up 3 GB, 64 bits can show up to 400 TB

**Comment by Cojad** [comment]
#142 
I suggest to use this method to fix it. This does not require to use exec function. So this will work on all 32bit platform(Windows/Linux ..etc).

**Comment by wakidanwar** [comment]
I also got this bug, the file size does not match the real one.
the file size is actually 7.5GB, while the one that appears is only -0.81GB

has this deficiency bug been fixed?

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
