### ISSUE TITLE
hidden dot files only work in root directory

### ISSUE THREAD

**Issue by danielmee** [DirectoryLister/DirectoryLister#92]
Hello. Despite having `'hide_dot_files'     => true` files starting with a dot are not hidden in sub directories. I have an example here where two images (one starting with a . and one without) have been placed at the root and in /folder: http://danielmee.com/dl/

**Comment by PHLAK** [comment]
Resolved with https://github.com/DirectoryLister/DirectoryLister/commit/476c9514eae048b5029b774f5c264085066248e7

**Comment by danielmee** [comment]
Wow! Thanks for the lightning speed fix! Feels weird to have reported an issue before going to bed and then waking up to it all being fix! :)

**Comment by PHLAK** [comment]
Caught me at a good time and the issue was relatively easy to fix.  Don't expect me to always be this responisve. =)
