### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kamranzafar** [DirectoryLister/DirectoryLister#93]
Is it possible to add pagination feature in case the folder contains too many files/folders?

**Comment by PHLAK** [comment]
This is not available as is but I will consider adding it in the future.

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
