### ISSUE TITLE
setup on gitlab

### ISSUE THREAD

**Issue by Aritz331** [DirectoryLister/DirectoryLister#935]
how do i set this up on gitlab?
btw why does the release not have the dockerfile and other files?

**Comment by PHLAK** [comment]
This has nothing to do with GitLab. I think you may have the wrong repository.

**Comment by Aritz331** [comment]
i know this is not related to gitlab but i want to host it on gitlab pages

**Comment by PHLAK** [comment]
I don't believe this is possible since GitLab Pages are static sites. They can't serve a PHP application.

**Comment by Aritz331** [comment]
ok

**Comment by Aritz331** [comment]
i can use heroku to host the page
