### ISSUE TITLE
Custom MD5 and SHA1

### ISSUE THREAD

**Issue by ghost** [DirectoryLister/DirectoryLister#95]
Hi, I want to put MD5 and SHA1 in to text file so when DirectoryLister want it will get checksum from text file but won't recalculate everytime I click info button because I have a very large file it may take very long time.

**Comment by CanadianJeff** [comment]
I am working on a way to put MD5 SHA1 of all the files in a folder into a single file (checksums.md5 or checksums.sha1) in the same format that the unix/linux command uses so you can later run and verify your MD5 SHA1 or you could send the file to someone else and they can check their hashes

**Comment by PHLAK** [comment]
Good news, Directory Lister 3 is now in beta! View the [release announcement](https://medium.com/chriskankiewicz/directory-lister-3-beta-is-here-d821236ac911) for more info.

This means all issues opened against the 2.X (currently `master`) branch will now be closed. We encourage you to to download and try the Directory Lister 3 beta and if the issue still applies, open a new issue.

If you'd like to join the discussion regarding the ongoing development of Directory Lister 3 you may do so in our [community forum](https://spectrum.chat/directory-lister).
