### ISSUE TITLE
UTF-8 Characters

### ISSUE THREAD

**Issue by alejomartinez8** [DirectoryLister/DirectoryLister#97]
We use this, but it have a problem and it isn't detect special character for spanish language for example, 'á', 'é' etc.

How can I solve it?

**Comment by happyjohann** [comment]
I have some files whose name contain Chinese, i find the the Chinese part is now displayed! It seems to be a problem of scandir() with php version 4 or older, is there any alternative solution?

**Comment by PHLAK** [comment]
Directory Lister does not officially support PHP versions older than 5.3.
If you decide to run it on an older version of PHP it may work, but there
will be no support or updates if there are issues.

On Thu, Dec 10, 2015 at 11:24 PM happyjohann <notifications@github.com>
wrote:

> I have some files whose name contain Chinese, i find the the Chinese part
> is now displayed! It seems to be a problem of scandir() with php version 4
> or older, is there any alternative solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DirectoryLister/DirectoryLister/issues/97#issuecomment-163855037>
> .
>
-- 
*Chris Kankiewicz* | Full Stack Web Developer
https://www.ChrisKankiewicz.com
