### ISSUE TITLE
Mobile version renders incorrectly

### ISSUE THREAD

**Issue by rirofal** [DirectoryLister/DirectoryLister#978]
### Directory Lister Version

3.12.0

### PHP Version

7.4.30

### Web Server

LiteSpeed V8.0.1 Cloudlinux 1.3

### Describe the Bug

When using a mobile phone with Safari or Chrome the site doesn't render as it should.

Trying to render it from my desktop using developer tools and a "mobile" view it renders OK.

Screenshot from my iPhone running Chrome:

![screenshot](https://user-images.githubusercontent.com/3245006/194094885-fab686d2-1c3d-4ec6-83bc-d013503217ea.jpg)

**Comment by PHLAK** [comment]
The [Directory Lister demo](https://demo.directorylister.com/) seems to be rendering just fine across all devices I've tested it on. This seems like an issue specific to your installation or phone. Without any additional information I'm not sure what the problem might be.

**Comment by rirofal** [comment]
Sorry... my bad, some files was probably corrupted while FTP-transfering them one by one.

Uploaded the zip and then extracted it, now it works just fine.
