### ISSUE TITLE
Script ignores index.* files

### ISSUE THREAD

**Issue by kulverstukas1** [DirectoryLister/DirectoryLister#98]
I did a basic installation, didn't change the config file, but saw that it should not list a directory if it has an index file in there, however that's not true in version 2.6.0 - directory is still getting listed completely ignoring an index file.

**Comment by dassmilytier** [comment]
same here. A Link is created behind the directory, which opens the directory in a new window. However, when selecting the directory directly, the directory is listed. At least regarding to the comment, a click on the directory should bring me to the linked folder.

**Comment by NoZomIBK** [comment]
Documentation is wrong/unclear.
![bildschirmfoto von 2015-11-22 09-50-58](https://cloud.githubusercontent.com/assets/6680114/11322847/d2ba0d08-90fe-11e5-801e-9d85db5bfc96.png)
it depends on the theme, how directories with index files are handled. default theme adds a link at the end of the line to get to the directory directly
should be configurable
